WIP: Amazon MQ throughput-optimized message brokers
hashicorp/terraform-provider-aws pull request #11459
Opened 2020-01-02 18:02 UTC by gdepuille

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #11325 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
ENHANCEMENTS:

* resource/aws_mq_broker: Add possibility to create an AmazonMQ broker with EBS (throughput optimized)
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2020-02-19 11:15 UTC, gdepuille commented
Hi @bflad, 
Can you communicate an ETA to validate this PR ?

2020-06-26 12:52 UTC, gdepuille commented
Hi,

I've rebased this development over the last release.

I've relaunched all acceptance tests and all are passed on the MQ features.

```bash
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSMq'

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSMq -timeout 120m
=== RUN   TestAccAWSMqBroker_basic
=== PAUSE TestAccAWSMqBroker_basic
=== RUN   TestAccAWSMqBroker_throughputOptimized
=== PAUSE TestAccAWSMqBroker_throughputOptimized
=== RUN   TestAccAWSMqBroker_allFieldsDefaultVpc
=== PAUSE TestAccAWSMqBroker_allFieldsDefaultVpc
=== RUN   TestAccAWSMqBroker_allFieldsCustomVpc
=== PAUSE TestAccAWSMqBroker_allFieldsCustomVpc
=== RUN   TestAccAWSMqBroker_EncryptionOptions_KmsKeyId
=== PAUSE TestAccAWSMqBroker_EncryptionOptions_KmsKeyId
=== RUN   TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled
=== PAUSE TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled
=== RUN   TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled
=== PAUSE TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled
=== RUN   TestAccAWSMqBroker_updateUsers
=== PAUSE TestAccAWSMqBroker_updateUsers
=== RUN   TestAccAWSMqBroker_updateTags
=== PAUSE TestAccAWSMqBroker_updateTags
=== RUN   TestAccAWSMqBroker_updateSecurityGroup
=== PAUSE TestAccAWSMqBroker_updateSecurityGroup
=== RUN   TestAccAWSMqBroker_disappears
=== PAUSE TestAccAWSMqBroker_disappears
=== RUN   TestAccAWSMqConfiguration_basic
=== PAUSE TestAccAWSMqConfiguration_basic
=== RUN   TestAccAWSMqConfiguration_withData
=== PAUSE TestAccAWSMqConfiguration_withData
=== RUN   TestAccAWSMqConfiguration_updateTags
=== PAUSE TestAccAWSMqConfiguration_updateTags
=== CONT  TestAccAWSMqBroker_basic
=== CONT  TestAccAWSMqBroker_updateTags
=== CONT  TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled
=== CONT  TestAccAWSMqBroker_updateUsers
=== CONT  TestAccAWSMqConfiguration_withData
=== CONT  TestAccAWSMqConfiguration_updateTags
=== CONT  TestAccAWSMqBroker_EncryptionOptions_KmsKeyId
=== CONT  TestAccAWSMqBroker_allFieldsDefaultVpc
=== CONT  TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled
=== CONT  TestAccAWSMqBroker_disappears
=== CONT  TestAccAWSMqBroker_allFieldsCustomVpc
=== CONT  TestAccAWSMqConfiguration_basic
=== CONT  TestAccAWSMqBroker_throughputOptimized
=== CONT  TestAccAWSMqBroker_updateSecurityGroup
--- PASS: TestAccAWSMqConfiguration_withData (36.82s)
--- PASS: TestAccAWSMqConfiguration_basic (61.86s)
--- PASS: TestAccAWSMqConfiguration_updateTags (89.84s)
--- PASS: TestAccAWSMqBroker_throughputOptimized (852.44s)
--- PASS: TestAccAWSMqBroker_basic (1140.31s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled (1141.84s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_KmsKeyId (1161.45s)
--- PASS: TestAccAWSMqBroker_disappears (1170.60s)
--- PASS: TestAccAWSMqBroker_updateTags (1234.79s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled (1261.30s)
--- PASS: TestAccAWSMqBroker_updateSecurityGroup (1484.36s)
--- PASS: TestAccAWSMqBroker_updateUsers (1584.28s)
--- PASS: TestAccAWSMqBroker_allFieldsDefaultVpc (2005.72s)
--- PASS: TestAccAWSMqBroker_allFieldsCustomVpc (2012.93s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2013.016s

```

2020-09-23 15:24 UTC, gdepuille commented
I've realized a rebase from 3.7.0

2020-10-28 08:18 UTC, matosf commented
Any ETA for this to be merged?

2020-11-12 16:32 UTC, ziek-za commented
@gdepuille are there any updates? Would love to be able to make use of this!

2020-12-15 16:41 UTC, gdepuille commented
@ziek-za I'm sorry that this PR is not included in the basic version. I use this in production since it's submitted. If you want to use it, it's possible to make a custom version of the provider with the commits you need. It's just you need some piece of time when new features are added in the core version.

2021-03-05 23:48 UTC, YakDriver commented
@gdepuille Thank you for this PR! We performed significant MQ reorganization in #16108. It looks like your PR may have some helpful tests beyond that. Please rebase when you have a chance.

2021-03-06 02:40 UTC, gdepuille commented
@YakDriver I've just been rebase this one. I've relaunch acceptance tests

<details>
  <summary><pre>PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1772.201s</pre></summary>

<pre>$> make testacc TEST=./aws TESTARGS=&apos;-run=TestAccAWSMq&apos;==&gt; Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSMq -timeout 120m
=== RUN   TestAccAWSMqBroker_basic
=== PAUSE TestAccAWSMqBroker_basic
=== RUN   TestAccAWSMqBroker_throughputOptimized
=== PAUSE TestAccAWSMqBroker_throughputOptimized
=== RUN   TestAccAWSMqBroker_allFieldsDefaultVpc
=== PAUSE TestAccAWSMqBroker_allFieldsDefaultVpc
=== RUN   TestAccAWSMqBroker_allFieldsCustomVpc
=== PAUSE TestAccAWSMqBroker_allFieldsCustomVpc
=== RUN   TestAccAWSMqBroker_EncryptionOptions_KmsKeyId
=== PAUSE TestAccAWSMqBroker_EncryptionOptions_KmsKeyId
=== RUN   TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled
=== PAUSE TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled
=== RUN   TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled
=== PAUSE TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled
=== RUN   TestAccAWSMqBroker_updateUsers
=== PAUSE TestAccAWSMqBroker_updateUsers
=== RUN   TestAccAWSMqBroker_updateTags
=== PAUSE TestAccAWSMqBroker_updateTags
=== RUN   TestAccAWSMqBroker_updateSecurityGroup
=== PAUSE TestAccAWSMqBroker_updateSecurityGroup
=== RUN   TestAccAWSMqBroker_disappears
=== PAUSE TestAccAWSMqBroker_disappears
=== RUN   TestAccAWSMqBroker_rabbitmq
=== PAUSE TestAccAWSMqBroker_rabbitmq
=== RUN   TestAccAWSMqConfiguration_basic
=== PAUSE TestAccAWSMqConfiguration_basic
=== RUN   TestAccAWSMqConfiguration_withData
=== PAUSE TestAccAWSMqConfiguration_withData
=== RUN   TestAccAWSMqConfiguration_updateTags
=== PAUSE TestAccAWSMqConfiguration_updateTags
=== CONT  TestAccAWSMqBroker_basic
=== CONT  TestAccAWSMqBroker_rabbitmq
=== CONT  TestAccAWSMqBroker_allFieldsDefaultVpc
=== CONT  TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled
=== CONT  TestAccAWSMqBroker_updateSecurityGroup
=== CONT  TestAccAWSMqBroker_updateTags
=== CONT  TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled
=== CONT  TestAccAWSMqBroker_EncryptionOptions_KmsKeyId
=== CONT  TestAccAWSMqConfiguration_updateTags
=== CONT  TestAccAWSMqConfiguration_withData
=== CONT  TestAccAWSMqConfiguration_basic
=== CONT  TestAccAWSMqBroker_updateUsers
=== CONT  TestAccAWSMqBroker_throughputOptimized
=== CONT  TestAccAWSMqBroker_disappears
=== CONT  TestAccAWSMqBroker_allFieldsCustomVpc
--- PASS: TestAccAWSMqConfiguration_withData (34.41s)
--- PASS: TestAccAWSMqConfiguration_basic (52.58s)
--- PASS: TestAccAWSMqConfiguration_updateTags (68.85s)
--- PASS: TestAccAWSMqBroker_rabbitmq (571.55s)
--- PASS: TestAccAWSMqBroker_throughputOptimized (861.68s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_KmsKeyId (1085.95s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled (1165.41s)
--- PASS: TestAccAWSMqBroker_disappears (1197.57s)
--- PASS: TestAccAWSMqBroker_basic (1214.57s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled (1223.27s)
--- PASS: TestAccAWSMqBroker_updateTags (1239.36s)
--- PASS: TestAccAWSMqBroker_updateSecurityGroup (1357.05s)
--- PASS: TestAccAWSMqBroker_updateUsers (1604.82s)
--- PASS: TestAccAWSMqBroker_allFieldsDefaultVpc (1710.93s)
--- PASS: TestAccAWSMqBroker_allFieldsCustomVpc (1772.14s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1772.201s
</pre>
</details>

2021-03-08 20:48 UTC, YakDriver requested changes
Thanks for your changes! There are just a few minor fixes and we should be good to go!

2021-03-08 20:48 UTC, YakDriver commented on website/docs/r/mq_broker.html.markdown
> +### Broker with EBS storage (high throughput optimized only on ActiveMQ engine type)
```suggestion
### High-throughput Optimized Example

This example shows the use of EBS storage for high-throughput optimized performance. Currently, this only works with `ActiveMQ`.
```

2021-03-08 20:48 UTC, YakDriver commented on website/docs/r/mq_broker.html.markdown
> +### Broker with EFS storage
```suggestion
### Basic Example
```

2021-03-08 20:48 UTC, YakDriver commented on website/docs/r/mq_broker.html.markdown
> +* `storage_type` - (Optional) Storage type of the broker. For `engine_type` `ActiveMQ`, the valid values are `efs` and `ebs`. When `ebs` storage type is defined, only the `mq.m5` broker instance type
```suggestion
* `storage_type` - (Optional) Storage type of the broker. For `engine_type` `ActiveMQ`, the valid values are `efs` and `ebs`. When using `ebs`, only the `mq.m5` broker instance type family is supported. For `engine_type` `RabbitMQ`, only `ebs` is supported. The AWS-default is `ebs`.
```

2021-03-08 20:48 UTC, YakDriver commented on aws/resource_aws_mq_broker_test.go
> +					resource.TestCheckResourceAttr(resourceName, "storage_type", "efs"),
```suggestion
```

This is a duplicate.

2021-03-09 19:57 UTC, gdepuille commented
@YakDriver I trust you for the documentation because it's not my native language ;-)

I've validated all your suggestion. I'm very happy this PR is near to be validated.

2021-03-09 21:02 UTC, YakDriver approved these changes
Looks good! Thanks!

Acceptance tests:
```
--- PASS: TestAccAWSMqBroker_rabbitmq (549.56s)
--- PASS: TestAccAWSMqBroker_throughputOptimized (791.92s)
--- PASS: TestAccAWSMqBroker_disappears (1138.54s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled (1182.12s)
--- PASS: TestAccAWSMqBroker_basic (1191.68s)
--- PASS: TestAccAWSMqBroker_updateTags (1199.67s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled (1225.50s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_KmsKeyId (1286.37s)
--- PASS: TestAccAWSMqBroker_updateSecurityGroup (1346.46s)
--- PASS: TestAccAWSMqBroker_updateUsers (1590.61s)
--- PASS: TestAccAWSMqBroker_allFieldsDefaultVpc (1696.42s)
--- PASS: TestAccAWSMqBroker_allFieldsCustomVpc (1748.95s)
```

2021-03-09 21:03 UTC, merged