aws_workspaces_bundle: Fix empty (private) owner
hashicorp/terraform-provider-aws pull request #14535
Opened 2020-08-10 09:07 UTC by Tensho

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
aws_workspaces_bundle: Fix empty (private) owner
```

Closes #14206.

### Acceptance Tests

```
$ AWS_WORKSPACES_BUNDLE_NAME=PerformanceLinuxBaseline AWS_DEFAULT_REGION=us-east-1 make testacc TEST=./aws TESTARGS='-run=TestAccDataSourceAwsWorkspaceBundle'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccDataSourceAwsWorkspaceBundle -timeout 120m
=== RUN   TestAccDataSourceAwsWorkspaceBundle_basic
=== PAUSE TestAccDataSourceAwsWorkspaceBundle_basic
=== RUN   TestAccDataSourceAwsWorkspaceBundle_byOwnerName
=== PAUSE TestAccDataSourceAwsWorkspaceBundle_byOwnerName
=== RUN   TestAccDataSourceAwsWorkspaceBundle_bundleIDAndNameConflict
=== PAUSE TestAccDataSourceAwsWorkspaceBundle_bundleIDAndNameConflict
=== RUN   TestAccDataSourceAwsWorkspaceBundle_privateOwner
=== PAUSE TestAccDataSourceAwsWorkspaceBundle_privateOwner
=== CONT  TestAccDataSourceAwsWorkspaceBundle_basic
=== CONT  TestAccDataSourceAwsWorkspaceBundle_privateOwner
=== CONT  TestAccDataSourceAwsWorkspaceBundle_bundleIDAndNameConflict
=== CONT  TestAccDataSourceAwsWorkspaceBundle_byOwnerName
--- PASS: TestAccDataSourceAwsWorkspaceBundle_bundleIDAndNameConflict (2.23s)
--- PASS: TestAccDataSourceAwsWorkspaceBundle_basic (20.44s)
--- PASS: TestAccDataSourceAwsWorkspaceBundle_privateOwner (20.51s)
--- PASS: TestAccDataSourceAwsWorkspaceBundle_byOwnerName (25.91s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	28.444s
```

2020-09-21 07:28 UTC, Tensho commented
@gdavison @ewbankkit Would appreciate for your review 🙇

2020-10-12 11:20 UTC, DrFaust92 requested changes
small change

2020-10-12 11:20 UTC, DrFaust92 commented on aws/data_source_aws_workspaces_bundle_test.go
> +data aws_workspaces_bundle test {
lets revert quotes.

2020-11-10 00:09 UTC, gdavison approved these changes
LGTM 🚀 

--- PASS: TestAccDataSourceAwsWorkspaceBundle_bundleIDAndNameConflict (33.06s)
--- PASS: TestAccDataSourceAwsWorkspaceBundle_privateOwner (73.64s)
--- PASS: TestAccDataSourceAwsWorkspaceBundle_basic (74.61s)
--- PASS: TestAccDataSourceAwsWorkspaceBundle_byOwnerName (76.38s)

2020-11-10 15:56 UTC, merged