New resource: aws_cloudwatch_composite_alarm
hashicorp/terraform-provider-aws pull request #15023
Opened 2020-09-03 21:17 UTC by roberth-k

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #12272

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
FEATURES:
- **New Resource:** `aws_cloudwatch_composite_alarm`
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAwsCloudWatchCompositeAlarm_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsCloudWatchCompositeAlarm_ -timeout 120m
--- PASS: TestAccAwsCloudWatchCompositeAlarm_disappears (11.52s)
--- PASS: TestAccAwsCloudWatchCompositeAlarm_basic (28.22s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       29.530s
```

2020-09-16 15:17 UTC, jvisker commented
Any updates on this?

2020-09-25 20:33 UTC, jayy-mize commented
any ETA on this feature being released?

2020-10-07 22:44 UTC, mqchau commented
@breathingdust Could you please take a look at this?

2020-10-15 16:24 UTC, breathingdust commented
Hi all 👋 . Just letting you know this is on our list for our engineers to review and will feature in an upcoming release.

2020-12-16 05:00 UTC, anGie44 requested changes
Hi @roberth-k, thank you for this PR ! Off to a really great start 👍 Please find my comments here for review. Feel free to reach out with any questions/concerns! 

Output of acceptance tests:
```
--- PASS: TestAccAwsCloudWatchCompositeAlarm_disappears (13.90s)
--- PASS: TestAccAwsCloudWatchCompositeAlarm_basic (37.54s)
```

2021-01-04 18:34 UTC, anGie44 commented
Hi @roberth-k 👋 checking in to see if you'll be able to address the changes requested here. Not a problem if you can't, we're happy to continue the work here and get it into an upcoming release, just let us know :)

2021-01-04 18:50 UTC, roberth-k commented
Hi @anGie44! I'll get it sorted some time this week.

2021-01-04 20:24 UTC, anGie44 commented
sounds great, thanks @roberth-k 👍

2021-01-09 20:16 UTC, roberth-k commented on aws/resource_aws_cloudwatch_composite_alarm.go
> +		return diag.Errorf("create composite alarm: %s", err)
Note in all cases I've retained the `%s` formatting directive, as acceptance testing with `%w` yields errors such as `aws/resource_aws_cloudwatch_composite_alarm.go:125:10: Errorf call has error-wrapping directive %w`.

2021-01-14 02:51 UTC, anGie44 commented
Hi @roberth-k 👋 Thank you again for this PR -- looked great overall! I've added a couple more acceptance tests for coverage to get this into our upcoming release. 

Output of acceptance tests:
```
--- PASS: TestAccAwsCloudWatchCompositeAlarm_disappears (183.81s)
--- PASS: TestAccAwsCloudWatchCompositeAlarm_basic (231.57s)
--- PASS: TestAccAwsCloudWatchCompositeAlarm_description (306.49s)
--- PASS: TestAccAwsCloudWatchCompositeAlarm_updateAlarmRule (325.89s)
--- PASS: TestAccAwsCloudWatchCompositeAlarm_allActions (326.25s)
--- PASS: TestAccAwsCloudWatchCompositeAlarm_actionsEnabled (326.34s)
--- PASS: TestAccAwsCloudWatchCompositeAlarm_insufficientDataActions (375.92s)
--- PASS: TestAccAwsCloudWatchCompositeAlarm_alarmActions (376.01s)
--- PASS: TestAccAwsCloudWatchCompositeAlarm_okActions (377.01s)
```

2021-01-14 02:53 UTC, anGie44 approved these changes

2021-01-14 02:53 UTC, merged