added default route table conflict warning
hashicorp/terraform-provider-aws pull request #15352
Opened 2020-09-25 12:32 UTC by philnichol

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #1699

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Updated documentation to include a conflict warning when using this resource with default_route_table
```

Output from acceptance testing:

```
N/A
```

Reasoning for Change: As pointed out in #1699 there is no warning in the docs about the issues of using this with default_route_table.  

This is my first PR to an open-source project, so apologies in advance for any issues or poor PR etiquette!

2021-02-25 19:46 UTC, breathingdust requested changes

2021-02-25 19:46 UTC, breathingdust commented on website/docs/r/main_route_table_association.html.markdown
> +
Hi @philnichol 👋  lets add this in a note section and use the same language as the `aws_default_route_table` resource referring back to that page.

```suggestion
~> **NOTE:** **Do not** use both `aws_default_route_table` to manage a default route table **and** `aws_main_route_table_association` with the same VPC due to possible route conflicts. See [aws_default_route_table][tf-default-route-table] documentation for more details.

For more information, see the Amazon VPC User Guide on [Route Tables](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Route_Tables.html). For information about managing normal route tables in Terraform, see [`aws_route_table`](/docs/providers/aws/r/route_table.html).
```

2021-02-25 19:46 UTC, breathingdust commented on website/docs/r/main_route_table_association.html.markdown
> +[tf-route-tables]: /docs/providers/aws/r/route_table.html
```suggestion
[aws-route-tables]: http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Route_Tables.html#Route_Replacing_Main_Table
[tf-route-tables]: /docs/providers/aws/r/route_table.html
[tf-default-route-table]: /docs/providers/aws/r/default_route_table.html
```

2021-06-16 21:58 UTC, breathingdust commented
Hi @philnichol! Checking back here, do you still want to add this note?

2021-06-16 22:03 UTC, philnichol commented
Hi @breathingdust, sorry I missed this. I'm guessing I deleted my original fork and recreated it since I can't edit this PR, I'll close it and raise a new one tomorrow if that's alright? Alternatively if you're able to commit the changes you suggested then feel free 😃

2021-06-17 07:53 UTC, closed without merging