adding fix for aws org feature_set update issue from #15462
hashicorp/terraform-provider-aws pull request #15473
Opened 2020-10-04 05:15 UTC by ryandeivert

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #15462

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAwsOrganizationsOrganization_FeatureSet'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsOrganizationsOrganization_FeatureSet -timeout 120m
=== RUN   TestAccAwsOrganizationsOrganization_FeatureSetForcesNew
=== RUN   TestAccAwsOrganizationsOrganization_FeatureSetUpdate
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	5.838s
```

2020-10-04 11:46 UTC, philnichol reviewed
@ryandeivert I'm not a maintainer so feel free to ignore, but looks like feature_set changes aren't yet implemented in the Read/Update functions, so this doesn't change the infra in AWS. Might need something like (I'm quite new to TF and Go so apologies if the below examples are garbage):
```hcl
// somewhere within the Read function
if err := d.Set("feature_set", org.Organization.FeatureSet); err != nil {
	return fmt.Errorf("error setting feature_set: %s", err)
}
```

```hcl
// somewhere within the Update function
if d.HasChange("feature_set") {
	o, n := d.GetChange("feature_set")
	input := &organizations.EnableAllFeaturesInput{}
	if _, err := conn.EnableAllFeatures(input); err != nil {
		return fmt.Errorf("error changing feature_set from (%s) to (%s): %s", o, n, err)
	}
}
```
Also may be worth updating docs, since when you enable "All" you still have to manually go into the AWS console and click "Finalize" once all accounts have accepted the change. Until you Finalize it's left in a state where you can still revert things.

2020-10-04 19:19 UTC, ryandeivert commented
good catch @philnichol - I added some updates and fixed a different bug in the current tests. docs are also updated now

2020-10-05 00:29 UTC, philnichol commented
@ryandeivert great stuff!

2020-10-13 21:29 UTC, ryandeivert commented
hi @anGie44 I noticed you updated the issue associated with this. is there any chance you can provide an update here?

2020-11-12 17:22 UTC, anGie44 requested changes
Hi @ryandeivert , thank you for this PR and your patience! Overall changes look great just some small changes needed.

2020-11-12 17:22 UTC, anGie44 commented on aws/resource_aws_organizations_organization.go
> +			return fmt.Errorf("error changing feature_set to ALL")
small change here: we should also return the error received with the organization id e.g.
```suggestion
			return fmt.Errorf("error enabling all features in Organization (%s): %w", d.Id(), err)
```

2020-11-12 17:22 UTC, anGie44 commented on aws/resource_aws_organizations_organization_test.go
> +func testAccAwsOrganizationsOrganization_FeatureSetForcesNew(t *testing.T) {
small nitpick here: it would be helpful to keep these new tests (ForcesNew, Update) close to the existing `FeatureSet` test above

2020-11-12 17:22 UTC, anGie44 commented on aws/resource_aws_organizations_organization_test.go
> +		if *before.Id == *after.Id {
Nit: we should unwrap these with the AWS Go SDK's method `aws.StringValue()` to prevent any unwanted panics

2020-11-12 17:22 UTC, anGie44 commented on aws/resource_aws_organizations_organization_test.go
> +			t.Fatalf("Expected change to Org ID value, but both were %v", *before.Id)
```suggestion
			return fmt.Errorf("Organization (%s) not recreated", aws.StringValue(before.Id))
```

2020-11-12 17:22 UTC, anGie44 commented on aws/resource_aws_organizations_organization_test.go
> +		}
similar nit as above:

```suggestion
		if aws.StringValue(before.Id) != aws.StringValue(after.Id) {
			return fmt.Errorf("Organization (%s) recreated", aws.StringValue(before.Id))
		}
```

2020-11-12 22:36 UTC, ryandeivert commented
hi @anGie44 - thank you for the review! I believe I have addressed all of your feedback now

2020-11-13 00:38 UTC, anGie44 approved these changes
Changes LGTM 🚀 Thanks again @ryandeivert @philnichol ! 

Output of acceptance tests:
```
--- PASS: TestFlattenOrganizationsRoots (0.00s)
--- PASS: TestAccAWSOrganizations_serial (1103.64s)
    --- PASS: TestAccAWSOrganizations_serial/Organization (217.24s)
        --- PASS: TestAccAWSOrganizations_serial/Organization/FeatureSet_ForcesNew (26.15s)
        --- PASS: TestAccAWSOrganizations_serial/Organization/DataSource (25.22s)
        --- PASS: TestAccAWSOrganizations_serial/Organization/basic (12.52s)
        --- PASS: TestAccAWSOrganizations_serial/Organization/AwsServiceAccessPrincipals (30.70s)
        --- PASS: TestAccAWSOrganizations_serial/Organization/EnabledPolicyTypes (90.92s)
        --- PASS: TestAccAWSOrganizations_serial/Organization/FeatureSet_Basic (11.43s)
        --- PASS: TestAccAWSOrganizations_serial/Organization/FeatureSet_Update (20.30s)
    --- PASS: TestAccAWSOrganizations_serial/Account (0.00s)
        --- SKIP: TestAccAWSOrganizations_serial/Account/basic (0.00s)
        --- SKIP: TestAccAWSOrganizations_serial/Account/ParentId (0.00s)
        --- SKIP: TestAccAWSOrganizations_serial/Account/Tags (0.00s)
    --- PASS: TestAccAWSOrganizations_serial/OrganizationalUnit (38.24s)
        --- PASS: TestAccAWSOrganizations_serial/OrganizationalUnit/basic (14.78s)
        --- PASS: TestAccAWSOrganizations_serial/OrganizationalUnit/Name (23.45s)
    --- PASS: TestAccAWSOrganizations_serial/OrganizationalUnits (0.00s)
        --- PASS: TestAccAWSOrganizations_serial/OrganizationalUnits/DataSource (13.49s)
    --- PASS: TestAccAWSOrganizations_serial/Policy (764.26s)
        --- PASS: TestAccAWSOrganizations_serial/Policy/Description (24.70s)
        --- PASS: TestAccAWSOrganizations_serial/Policy/Tags (321.10s)
        --- PASS: TestAccAWSOrganizations_serial/Policy/Type_SCP (296.24s)
        --- PASS: TestAccAWSOrganizations_serial/Policy/Type_Tag (13.83s)
        --- PASS: TestAccAWSOrganizations_serial/Policy/basic (25.28s)
        --- PASS: TestAccAWSOrganizations_serial/Policy/concurrent (25.83s)
        --- PASS: TestAccAWSOrganizations_serial/Policy/disappears (13.14s)
        --- PASS: TestAccAWSOrganizations_serial/Policy/Type_AI_OPT_OUT (15.99s)
        --- PASS: TestAccAWSOrganizations_serial/Policy/Type_Backup (13.66s)
        --- PASS: TestAccAWSOrganizations_serial/Policy/ImportAwsManagedPolicy (14.49s)
    --- PASS: TestAccAWSOrganizations_serial/PolicyAttachment (70.41s)
        --- PASS: TestAccAWSOrganizations_serial/PolicyAttachment/OrganizationalUnit (19.30s)
        --- PASS: TestAccAWSOrganizations_serial/PolicyAttachment/Root (18.89s)
        --- PASS: TestAccAWSOrganizations_serial/PolicyAttachment/Account (32.22s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1106.033s
```

2020-11-13 00:49 UTC, merged