Add aws_codestarconnections_connection resource
hashicorp/terraform-provider-aws pull request #15990
Opened 2020-11-02 23:52 UTC by shuheiktgw

Co-authored-by: Kévin Sénéchal <kevin.senechal@gmail.com>

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates https://github.com/hashicorp/terraform-provider-aws/issues/15453, https://github.com/hashicorp/terraform-provider-aws/pull/15960
Closes https://github.com/hashicorp/terraform-provider-aws/pull/12637, https://github.com/hashicorp/terraform-provider-aws/issues/11389

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* **New Resource:** `aws_codestarconnections_connection`
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSCodeStarConnectionsConnection_Basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSCodeStarConnectionsConnection_Basic -timeout 120m
=== RUN   TestAccAWSCodeStarConnectionsConnection_Basic
=== PAUSE TestAccAWSCodeStarConnectionsConnection_Basic
=== CONT  TestAccAWSCodeStarConnectionsConnection_Basic
--- PASS: TestAccAWSCodeStarConnectionsConnection_Basic (37.72s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	39.914s
```

This is the second part of a PR to add `aws_codestarconnections_connection` resource (the first part: https://github.com/hashicorp/terraform-provider-aws/pull/15960). This PR originally came from https://github.com/hashicorp/terraform-provider-aws/pull/12637. Thank you for your review!

2020-11-03 00:20 UTC, shuheiktgw commented
@bflad I've created the second part of the PR to support `aws_codestarconnections_connection` resource so would you review the PR?

2020-12-12 01:08 UTC, gdavison requested changes
Thanks for the PR, @shuheiktgw, it's looking good. I have a few suggestions for additions to the resource

2020-12-12 01:08 UTC, gdavison commented on aws/resource_aws_codestarconnections_connection.go
> +	if err != nil {
This should also handle the case where the CodeStar connection is not found by returning immediately

2020-12-12 01:08 UTC, gdavison commented on aws/resource_aws_codestarconnections_connection_test.go
> +
In order to test the ability of the provider to handle the resource being deleted outside of Terraform, this should include a "Disappears" test, as documented at https://github.com/hashicorp/terraform-provider-aws/blob/master/docs/contributing/running-and-writing-acceptance-tests.md#disappears-acceptance-tests

2020-12-14 00:07 UTC, shuheiktgw commented
@gdavison Thank you for your review! Let me fix them quickly 👍

2020-12-15 10:54 UTC, shuheiktgw commented
@gdavison Thank you for your great reviews! I believe I fixed them up so would you review the PR again? 😄 
I also reran the acc tests so please check the results below.

```
$ make testacc TESTARGS='-run=TestAccAWSCodeStarConnectionsConnection_*'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSCodeStarConnectionsConnection_* -timeout 120m
=== RUN   TestAccAWSCodeStarConnectionsConnection_Basic
=== PAUSE TestAccAWSCodeStarConnectionsConnection_Basic
=== RUN   TestAccAWSCodeStarConnectionsConnection_disappears
=== PAUSE TestAccAWSCodeStarConnectionsConnection_disappears
=== CONT  TestAccAWSCodeStarConnectionsConnection_disappears
=== CONT  TestAccAWSCodeStarConnectionsConnection_Basic
--- PASS: TestAccAWSCodeStarConnectionsConnection_disappears (36.78s)
--- PASS: TestAccAWSCodeStarConnectionsConnection_Basic (49.39s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	51.265s
```

2020-12-15 19:36 UTC, gdavison commented on aws/resource_aws_codestarconnections_connection_test.go
> +			if err != nil && !isAWSErr(err, codestarconnections.ErrCodeResourceNotFoundException, "") {
A note for future reference: `isAWSErr()` and the error checking functions at https://github.com/hashicorp/aws-sdk-go-base/blob/master/tfawserr/awserr.go can handle a `nil` error, so `err != nil` isn't technically needed

2020-12-15 19:57 UTC, gdavison approved these changes
Thanks for the updates, @shuheiktgw! LGTM 🚀 

--- PASS: TestAccAWSCodeStarConnectionsConnection_disappears (10.42s)
--- PASS: TestAccAWSCodeStarConnectionsConnection_Basic (14.08s)

2020-12-15 23:23 UTC, merged