tests/provider: Fixes for testing provider re-configuration
hashicorp/terraform-provider-aws pull request #16018
Opened 2020-11-04 18:00 UTC by bflad

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Reference: https://github.com/hashicorp/terraform-provider-aws/issues/8316
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/15737
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/15791

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Applies two fixes for provider re-configuration issues:

* The `testAccProviderFactories` map should always return a new provider instance every invocation, otherwise concurrent testing with differing provider configurations can overwrite each other since the testing framework can reuse the same underlying  provider instance address across multiple gRPC plugin configurations.
* The `testAccPreCheck()` function is invoked for every test and unnecessarily verifies and reconfigures the "main" provider instance every time to the same configuration.

Adds comments around all this functionality to hopefully make this section of the code clearer for future travelers.

Output from acceptance testing (provided as smoke testing with differing provider configurations in the same testing invocation):

```
--- PASS: TestAccAWSEIPAssociation_instance (94.34s)
--- PASS: TestAccAWSEIPAssociation_ec2Classic (218.07s)
```

2020-11-10 22:13 UTC, YakDriver commented
Is this expected on GovCloud for now?

```
    provider_test.go:213: [{0 error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.
        	status code: 403, request id: 987c445a-d887-4e7e-aacd-d98e84e3b7d6  []}]
--- FAIL: TestAccAWSEIPAssociation_ec2Classic (0.21s)
--- PASS: TestAccAWSEIPAssociation_instance (105.15s)
```

2020-11-10 22:19 UTC, YakDriver requested changes
Locally, I'm consistently getting errors on commercials (same thing on 3 runs):

```
    resource_aws_eip_association_test.go:103: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        An execution plan has been generated and is shown below.
        Resource actions are indicated with the following symbols:
        -/+ destroy and then create replacement
        
        Terraform will perform the following actions:
        
          # aws_eip_association.test must be replaced
        -/+ resource "aws_eip_association" "test" {
              + allocation_id        = (known after apply)
              ~ id                   = "107.20.142.12" -> (known after apply)
              + instance_id          = "i-04820728183b496a3"
              + network_interface_id = (known after apply)
              + private_ip_address   = (known after apply)
                public_ip            = "107.20.142.12"
            }
        
        Plan: 1 to add, 0 to change, 1 to destroy.
--- FAIL: TestAccAWSEIPAssociation_ec2Classic (81.04s)
```

2020-11-11 00:03 UTC, bflad commented
I was probably testing with the fixes from https://github.com/hashicorp/terraform-provider-aws/pull/16032 too, really any testing working covering this since its critical path for every test.

2020-11-12 20:25 UTC, YakDriver commented
@bflad Apologies for the force push, just a rebase. With it, this PR is now passing.

GovCloud:
```
    ec2_classic_test.go:54: this test can only run in EC2-Classic, platforms available in us-gov-west-1: ["VPC"]
--- SKIP: TestAccAWSEIPAssociation_ec2Classic (2.80s)
--- PASS: TestAccAWSEIPAssociation_instance (85.07s)
```

Commercial:
```
--- PASS: TestAccAWSEIPAssociation_ec2Classic (212.95s)
--- PASS: TestAccAWSEIPAssociation_instance (90.99s)
```

2020-11-12 20:27 UTC, YakDriver approved these changes
Utmärkt arbete! 💯

2020-11-13 13:00 UTC, merged