tests/provider: Enable S1039 check for unnecessary fmt.Sprint()/fmt.S…
hashicorp/terraform-provider-aws pull request #16741
Opened 2020-12-13 21:58 UTC by mattburgess

…printf() usage

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #14376

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2020-12-15 03:22 UTC, bflad requested changes
Thank you for submitting this, @mattburgess, just a few things along with verifying the acceptance tests pass, then we should be able to get this in. Please see the [Contributing Guide section on running the acceptance tests](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/contributing/running-and-writing-acceptance-tests.md) or reach out if you have any questions.

2020-12-15 03:22 UTC, bflad commented on aws/data_source_aws_codeartifact_authorization_token_test.go
> +		`data "aws_codeartifact_authorization_token" "test" {
Configurations should include an initial newline:

```suggestion
		`
data "aws_codeartifact_authorization_token" "test" {
```

2020-12-15 03:22 UTC, bflad commented on aws/data_source_aws_directory_service_directory_test.go
> +		`resource "aws_directory_service_directory" "test" {
Similarly:

```suggestion
		`
resource "aws_directory_service_directory" "test" {
```

2020-12-15 03:22 UTC, bflad commented on aws/data_source_aws_docdb_engine_version_test.go
> +	return `data "aws_docdb_engine_version" "test" {}`
```suggestion
	return `
data "aws_docdb_engine_version" "test" {}
`
```

2020-12-15 03:22 UTC, bflad commented on aws/data_source_aws_neptune_engine_version_test.go
> +	return `data "aws_neptune_engine_version" "test" {}`
```suggestion
	return `
data "aws_neptune_engine_version" "test" {}
`
```

2020-12-15 03:22 UTC, bflad commented on aws/resource_aws_emr_cluster_test.go
> +	return `data "aws_partition" "current" {}`
```suggestion
	return `
data "aws_partition" "current" {}
`
```

2020-12-15 18:44 UTC, mattburgess commented
Thanks for the review @bflad - no issues running the acceptance tests; I'm just pulling a list together of the affected ones to minimise testing time/feedback cycle. I'll hopefully have results back in a couple of hours.

2020-12-16 09:04 UTC, mattburgess commented
I've run the tests for all affected data sources and resources. Gist at https://gist.github.com/mattburgess/e38a1de6d2dbed899b48636580d6efbc

They're somewhat masked by my account not being correctly configured in terms of low resource (VPC, EIP, etc.) limits and lack of default VPC/subnets. I'll try to get those sorted so that future acceptance test runs are much clearer.

2020-12-17 12:30 UTC, mattburgess commented
@bflad I've re-run the acceptance tests and they're looking much cleaner now. Current failures look to be either repeatable on upstream master or, in the case of EMR in particular, I'm still not meeting the pre-reqs. So, in short, I'm pretty confident the PR's good.

```matthewburgess@kyoto:~/dev/go/terraform-provider-aws (td-staticcheck-s1039$% u=)$ grep FAIL test.log 
--- FAIL: TestAccAwsAutoScalingGroupDataSource_basic (12.11s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	42.822s
FAIL
--- FAIL: TestAccAWSCodeArtifactAuthorizationTokenDataSource_basic (6.32s)
--- FAIL: TestAccAWSCodeArtifactAuthorizationTokenDataSource_duration (6.37s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	44.759s
FAIL
--- FAIL: TestAccAWSCodeArtifactRepositoryEndpointDataSource_basic (7.24s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	44.989s
FAIL
--- FAIL: TestAccAWSInstanceDataSource_keyPair (9.24s)
--- FAIL: TestAccAWSInstanceDataSource_tags (9.28s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	800.298s
FAIL
--- FAIL: TestAccAWSRouteDataSource_basic (122.36s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	370.837s
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	7200.086s
FAIL
--- FAIL: TestAccAWSEc2TransitGatewayVpcAttachmentAccepter_Tags (0.03s)
--- FAIL: TestAccAWSEc2TransitGatewayVpcAttachmentAccepter_TransitGatewayDefaultRouteTableAssociationAndPropagation (0.02s)
--- FAIL: TestAccAWSEc2TransitGatewayVpcAttachmentAccepter_basic (0.03s)
--- FAIL: TestAccAWSEc2TransitGatewayVpcAttachment_SharedTransitGateway (0.02s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	1606.062s
FAIL
--- FAIL: TestAccAWSEMRCluster_Step_Basic (79.65s)
--- FAIL: TestAccAWSEMRCluster_ebs_config (79.51s)
--- FAIL: TestAccAWSEMRCluster_step_concurrency_level (76.64s)
--- FAIL: TestAccAWSEMRCluster_CoreInstanceGroup_Name (77.42s)
--- FAIL: TestAccAWSEMRCluster_MasterInstanceGroup_Name (76.70s)
--- FAIL: TestAccAWSEMRCluster_MasterInstanceGroup_InstanceType (78.49s)
--- FAIL: TestAccAWSEMRCluster_MasterInstanceGroup_InstanceCount (75.78s)
--- FAIL: TestAccAWSEMRCluster_MasterInstanceGroup_BidPrice (74.18s)
--- FAIL: TestAccAWSEMRCluster_Kerberos_ClusterDedicatedKdc (73.24s)
--- FAIL: TestAccAWSEMRCluster_Ec2Attributes_DefaultManagedSecurityGroups (72.90s)
--- FAIL: TestAccAWSEMRCluster_CoreInstanceGroup_AutoscalingPolicy (74.12s)
--- FAIL: TestAccAWSEMRCluster_CoreInstanceGroup_InstanceType (75.45s)
--- FAIL: TestAccAWSEMRCluster_CoreInstanceGroup_InstanceCount (73.93s)
--- FAIL: TestAccAWSEMRCluster_CoreInstanceGroup_BidPrice (73.29s)
--- FAIL: TestAccAWSEMRCluster_s3Logging (72.89s)
--- FAIL: TestAccAWSEMRCluster_Step_Multiple (74.01s)
--- FAIL: TestAccAWSEMRCluster_Step_ConfigMode (75.68s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	2780.495s
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	7200.064s
FAIL
--- FAIL: TestAccAWSInstance_volumeTagsComputed (212.75s)
--- FAIL: TestAccAWSInstanceDataSource_keyPair (9.34s)
--- FAIL: TestAccAWSInstanceDataSource_tags (11.17s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	4582.044s
FAIL
--- FAIL: TestAccAWSRouteTable_IPv4_To_VpcEndpoint (163.43s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	854.387s
FAIL
--- FAIL: TestAccAWSRoute53ResolverRuleDataSource_SharedWithMe (0.02s)
--- FAIL: TestAccAWSRoute53ZoneDataSource_name (5.11s)
--- FAIL: TestAccAWSRouteDataSource_basic (134.82s)
--- FAIL: TestAccAWSRoute53ResolverRuleDataSource_SharedByMe (0.02s)
--- FAIL: TestAccAWSRoute53VpcAssociationAuthorization_disappears (0.02s)
--- FAIL: TestAccAWSRoute53VpcAssociationAuthorization_basic (0.03s)
--- FAIL: TestAccAWSRoute53ResolverRuleDataSource_basic (7.14s)
--- FAIL: TestAccAWSRoute53ZoneAssociation_CrossAccount (0.03s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	4681.272s
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	913.368s
FAIL
```

2021-01-05 15:27 UTC, bflad approved these changes
Looks good to me. 🚀 

Output from acceptance testing:

```
--- PASS: TestAccAwsAutoScalingGroupDataSource_launchTemplate (71.46s)

--- PASS: TestAccAWSCodeArtifactAuthorizationTokenDataSource_basic (45.57s)
--- PASS: TestAccAWSCodeArtifactAuthorizationTokenDataSource_duration (43.00s)
--- PASS: TestAccAWSCodeArtifactAuthorizationTokenDataSource_owner (44.32s)

--- PASS: TestAccAWSCodeArtifactRepositoryEndpointDataSource_owner (45.34s)

--- PASS: TestAccDataSourceAWSDirectoryServiceDirectory_connector (1041.15s)

--- PASS: TestAccAWSDocDBEngineVersionDataSource_basic (44.56s)
--- PASS: TestAccAWSDocDBEngineVersionDataSource_defaultOnly (45.64s)
--- PASS: TestAccAWSDocDBEngineVersionDataSource_preferred (46.09s)

--- PASS: TestAccDataSourceAwsEbsSnapshotIds_basic (63.09s)

--- PASS: TestAccAwsEc2SpotPriceDataSource_basic (42.29s)
--- PASS: TestAccAwsEc2SpotPriceDataSource_Filter (45.38s)

--- PASS: TestAccAWSInstanceDataSource_AzUserData (212.88s)
--- PASS: TestAccAWSInstanceDataSource_creditSpecification (185.06s)
--- PASS: TestAccAWSInstanceDataSource_privateIP (85.76s)
--- PASS: TestAccAWSInstanceDataSource_secondaryPrivateIPs (189.66s)
--- PASS: TestAccAWSInstanceDataSource_VPC (205.07s)
--- PASS: TestAccAWSInstanceDataSource_VPCSecurityGroups (92.95s)

--- PASS: TestAccAWSNeptuneEngineVersionDataSource_defaultOnly (12.65s)
--- PASS: TestAccAWSNeptuneEngineVersionDataSource_preferred (13.93s)

--- PASS: TestAccAWSRDSEngineVersionDataSource_defaultOnly (13.03s)
--- PASS: TestAccAWSRDSEngineVersionDataSource_preferred (15.70s)
--- PASS: TestAccAWSRDSEngineVersionDataSource_upgradeTargets (13.12s)

--- PASS: TestAccAWSRdsOrderableDbInstanceDataSource_supportsEnhancedMonitoring (525.11s)
--- PASS: TestAccAWSRdsOrderableDbInstanceDataSource_supportsIAMDatabaseAuthentication (492.15s)
--- PASS: TestAccAWSRdsOrderableDbInstanceDataSource_supportsIops (535.42s)
--- PASS: TestAccAWSRdsOrderableDbInstanceDataSource_supportsKerberosAuthentication (652.41s)
--- PASS: TestAccAWSRdsOrderableDbInstanceDataSource_supportsPerformanceInsights (508.39s)
--- PASS: TestAccAWSRdsOrderableDbInstanceDataSource_supportsStorageAutoscaling (506.70s)
--- PASS: TestAccAWSRdsOrderableDbInstanceDataSource_supportsStorageEncryption (534.73s)

--- SKIP: TestAccAWSRouteDataSource_LocalGatewayID (1.92s) # approving on consistent update

--- FAIL: TestAccDataSourceAwsWorkspacesWorkspace_byDirectoryID_userName (1706.32s) # failure unrelated
--- PASS: TestAccDataSourceAwsWorkspacesWorkspace_byWorkspaceID (1719.05s)
--- PASS: TestAccDataSourceAwsWorkspacesWorkspace_workspaceIDAndDirectoryIDConflict (1.85s)

--- PASS: TestAccAWSAPIGatewayV2Integration_basicHttp (15.34s)
--- PASS: TestAccAWSAPIGatewayV2Integration_VpcLinkHttp (344.36s)

--- PASS: TestAccAWSAutoScalingGroup_ALB_TargetGroups (143.07s)
--- PASS: TestAccAWSAutoScalingGroup_ALB_TargetGroups_ELBCapacity (286.38s)
--- PASS: TestAccAWSAutoScalingGroup_autoGeneratedName (37.38s)
--- PASS: TestAccAWSAutoScalingGroup_basic (219.39s)
--- PASS: TestAccAWSAutoScalingGroup_classicVpcZoneIdentifier (41.62s)
--- PASS: TestAccAWSAutoScalingGroup_enablingMetrics (142.46s)
--- PASS: TestAccAWSAutoScalingGroup_initialLifecycleHook (240.82s)
--- PASS: TestAccAWSAutoScalingGroup_InstanceRefresh_Basic (242.09s)
--- PASS: TestAccAWSAutoScalingGroup_InstanceRefresh_Start (324.08s)
--- PASS: TestAccAWSAutoScalingGroup_InstanceRefresh_Triggers (215.58s)
--- PASS: TestAccAWSAutoScalingGroup_launchTemplate (35.83s)
--- PASS: TestAccAWSAutoScalingGroup_LaunchTemplate_IAMInstanceProfile (74.82s)
--- PASS: TestAccAWSAutoScalingGroup_launchTemplate_update (150.10s)
--- PASS: TestAccAWSAutoScalingGroup_launchTempPartitionNum (59.45s)
--- PASS: TestAccAWSAutoScalingGroup_LoadBalancers (338.56s)
--- PASS: TestAccAWSAutoScalingGroup_MaxInstanceLifetime (73.46s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy (43.53s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_CapacityRebalance (73.57s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstancesDistribution_OnDemandAllocationStrategy (55.63s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstancesDistribution_OnDemandBaseCapacity (70.28s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstancesDistribution_OnDemandPercentageAboveBaseCapacity (63.03s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstancesDistribution_SpotAllocationStrategy (34.64s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstancesDistribution_SpotInstancePools (79.24s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstancesDistribution_SpotMaxPrice (77.73s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstancesDistribution_UpdateToZeroOnDemandBaseCapacity (53.73s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_LaunchTemplate_LaunchTemplateSpecification_LaunchTemplateName (45.06s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_LaunchTemplate_LaunchTemplateSpecification_Version (59.23s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_LaunchTemplate_Override_InstanceType (57.68s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_LaunchTemplate_Override_WeightedCapacity (145.54s)
--- PASS: TestAccAWSAutoScalingGroup_namePrefix (35.86s)
--- PASS: TestAccAWSAutoScalingGroup_serviceLinkedRoleARN (37.84s)
--- PASS: TestAccAWSAutoScalingGroup_suspendingProcesses (257.34s)
--- PASS: TestAccAWSAutoScalingGroup_tags (207.12s)
--- PASS: TestAccAWSAutoScalingGroup_TargetGroupArns (193.09s)
--- PASS: TestAccAWSAutoScalingGroup_terminationPolicies (100.30s)
--- PASS: TestAccAWSAutoScalingGroup_VpcUpdates (56.24s)
--- PASS: TestAccAWSAutoScalingGroup_WithLoadBalancer (239.70s)
--- PASS: TestAccAWSAutoScalingGroup_WithLoadBalancer_ToTargetGroup (387.49s)
--- PASS: TestAccAWSAutoScalingGroup_withMetrics (61.63s)
--- PASS: TestAccAWSAutoScalingGroup_withPlacementGroup (143.46s)

--- PASS: TestAccAWSDataSyncLocationFsxWindows_basic (3417.93s)
--- PASS: TestAccAWSDataSyncLocationFsxWindows_disappears (3289.14s)

--- PASS: TestAccAWSDBInstance_basic (480.72s)
--- PASS: TestAccAWSDBInstance_CACertificateIdentifier (448.65s)
--- PASS: TestAccAWSDBInstance_generatedName (458.42s)
--- PASS: TestAccAWSDBInstance_namePrefix (356.64s)

--- PASS: TestAccAWSDocDBSubnetGroup_generatedName (15.15s)
--- PASS: TestAccAWSDocDBSubnetGroup_namePrefix (30.02s)

--- FAIL: TestAccAWSEc2TransitGatewayRoute_disappears (374.20s) # failure unrelated
--- PASS: TestAccAWSEc2TransitGatewayRoute_basic (375.92s)
--- PASS: TestAccAWSEc2TransitGatewayRoute_basic_ipv6 (396.16s)
--- PASS: TestAccAWSEc2TransitGatewayRoute_blackhole (436.56s)
--- PASS: TestAccAWSEc2TransitGatewayRoute_disappears_TransitGatewayAttachment (356.37s)

--- PASS: TestAccAWSEc2TransitGatewayVpcAttachment_basic (369.17s)
--- PASS: TestAccAWSEc2TransitGatewayVpcAttachment_disappears (367.31s)
--- PASS: TestAccAWSEc2TransitGatewayVpcAttachment_SubnetIds (487.91s)
--- PASS: TestAccAWSEc2TransitGatewayVpcAttachment_TransitGatewayDefaultRouteTableAssociationAndPropagationDisabled (300.37s)

--- PASS: TestAccAWSEIPAssociation_instance (84.67s)

--- PASS: TestAccAWSELBAttachment_basic (182.22s)
--- PASS: TestAccAWSELBAttachment_drift (94.31s)

--- PASS: TestAccAWSEMRCluster_additionalInfo (410.13s)
--- PASS: TestAccAWSEMRCluster_basic (346.72s)
--- PASS: TestAccAWSEMRCluster_bootstrap_ordering (1321.76s)
--- PASS: TestAccAWSEMRCluster_configurationsJson (415.35s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_AutoscalingPolicy (483.21s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_BidPrice (1024.69s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_InstanceCount (542.38s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_InstanceType (837.66s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_Name (902.34s)
--- PASS: TestAccAWSEMRCluster_custom_ami_id (475.88s)
--- PASS: TestAccAWSEMRCluster_disappears (408.45s)
--- PASS: TestAccAWSEMRCluster_ebs_config (465.12s)
--- PASS: Tes [...]

2021-01-05 15:27 UTC, merged