resource/aws_emr_cluster Add support for subnet_ids attribute
hashicorp/terraform-provider-aws pull request #17219
Opened 2021-01-21 19:02 UTC by kristerjaanhold

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note

```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2021-04-01 11:47 UTC, kasparg commented
Hey @gdavison :wave: We're wondering if there's something we can do to bump this up? Checks are passing, code is there, this would be really useful to many people :slightly_smiling_face:

2021-04-01 23:53 UTC, gdavison requested changes
Thanks for the PR, @kristerjaanhold.

The new acceptance test step is currently failing, showing a plan difference. To run the specific test, you can run

```console
$ make testacc TESTARGS='-run=TestAccAWSEMRCluster_basic'
```

To run all of the EMR Cluster tests, run

```console
$ make testacc TESTARGS='-run=TestAccAWSEMRCluster_'
```

I've also added a number of changes to consider.

2021-04-01 23:53 UTC, gdavison commented on aws/resource_aws_emr_cluster_test.go
> +			{
This should have an Import test after the first step, as well as after, to ensure that `terraform import` will work in both cases

2021-04-01 23:53 UTC, gdavison commented on aws/resource_aws_emr_cluster_test.go
> +					testAccCheckAWSEmrClusterExists(resourceName, &cluster),
For completeness, this step should include a call to `testAccCheckAWSEmrClusterRecreated()`, since both `subnet_id` and `subnet_ids` are `ForceNew`

2021-04-01 23:53 UTC, gdavison commented on aws/resource_aws_emr_cluster_test.go
> +					resource.TestCheckResourceAttr(resourceName, "bootstrap_action.#", "0"),
This should test that `ec2_attributes.0. subnet_ids` has the correct number of values and that the correct values are set and that `ec2_attributes.0. subnet_id` is not set. `TypeSet` values can be checked using `resource.TestCheckTypeSetElemAttrPair`.

In addition, in the first test step, the test should confirm that `ec2_attributes.0. subnet_id` is set to the correct value and that `ec2_attributes.0. subnet_ids` has zero elements.

2021-04-09 17:43 UTC, gdavison commented
Hi @kristerjaanhold. We've had a lot of requests for this PR, so we'd like to get it merged in. If you'd like to continue working on it, let me know. Otherwise, I'll pick it up from here and make the needed changes, probably Monday, 12 April, Pacific time (UTC-7). I'll make sure that your contributions are still credited 🙂

2021-04-12 07:38 UTC, kristerjaanhold commented
Hi @gdavison, feel free to pick it up from here. Thanks!

2021-04-15 23:06 UTC, gdavison approved these changes
Acceptance test results

--- PASS: TestAccAWSEMRCluster_disappears (836.36s)
--- PASS: TestAccAWSEMRCluster_configurationsJson (943.43s)
--- PASS: TestAccAWSEMRCluster_security_config (948.97s)
--- PASS: TestAccAWSEMRCluster_basic (987.39s)
--- PASS: TestAccAWSEMRCluster_Step_Basic (1009.17s)
--- PASS: TestAccAWSEMRCluster_InstanceFleet_master_only (1020.61s)
--- PASS: TestAccAWSEMRCluster_custom_ami_id (1055.85s)
--- PASS: TestAccAWSEMRCluster_Kerberos_ClusterDedicatedKdc (1071.61s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_AutoscalingPolicy (1119.10s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_InstanceCount (1157.16s)
--- PASS: TestAccAWSEMRCluster_MasterInstanceGroup_InstanceType (1200.88s)
--- PASS: TestAccAWSEMRCluster_Ec2Attributes_DefaultManagedSecurityGroups (1303.71s)
--- PASS: TestAccAWSEMRCluster_tags (1308.94s)
--- PASS: TestAccAWSEMRCluster_additionalInfo (451.51s)
--- PASS: TestAccAWSEMRCluster_MasterInstanceGroup_BidPrice (1432.37s)
--- PASS: TestAccAWSEMRCluster_ebs_config (644.82s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_InstanceType (1504.15s)
--- PASS: TestAccAWSEMRCluster_MasterInstanceGroup_InstanceCount (1518.15s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_BidPrice (1527.34s)
--- PASS: TestAccAWSEMRCluster_Step_Multiple (521.91s)
--- PASS: TestAccAWSEMRCluster_step_concurrency_level (576.21s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_Name (1614.24s)
--- PASS: TestAccAWSEMRCluster_s3Logging (637.90s)
--- PASS: TestAccAWSEMRCluster_terminationProtected (664.23s)
--- PASS: TestAccAWSEMRCluster_MasterInstanceGroup_Name (1673.52s)
--- PASS: TestAccAWSEMRCluster_keepJob (559.41s)
--- PASS: TestAccAWSEMRCluster_InstanceFleet_basic (1780.47s)
--- PASS: TestAccAWSEMRCluster_root_volume_size (972.90s)
--- PASS: TestAccAWSEMRCluster_visibleToAllUsers (912.02s)
--- PASS: TestAccAWSEMRCluster_Step_ConfigMode (1087.24s)
--- PASS: TestAccAWSEMRCluster_bootstrap_ordering (1454.59s)

2021-04-15 23:14 UTC, merged