CloudFront Origin Request Policy
hashicorp/terraform-provider-aws pull request #17342
Opened 2021-01-28 20:20 UTC by bill-rich

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #14373
Output from acceptance testing:

```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSCloudFrontOriginRequestPolicy -timeout 120m
=== RUN   TestAccAWSCloudFrontOriginRequestPolicy_basic
=== PAUSE TestAccAWSCloudFrontOriginRequestPolicy_basic
=== RUN   TestAccAWSCloudFrontOriginRequestPolicy_update
=== PAUSE TestAccAWSCloudFrontOriginRequestPolicy_update
=== RUN   TestAccAWSCloudFrontOriginRequestPolicy_noneBehavior
=== PAUSE TestAccAWSCloudFrontOriginRequestPolicy_noneBehavior
=== CONT  TestAccAWSCloudFrontOriginRequestPolicy_basic
=== CONT  TestAccAWSCloudFrontOriginRequestPolicy_noneBehavior
=== CONT  TestAccAWSCloudFrontOriginRequestPolicy_update
--- PASS: TestAccAWSCloudFrontOriginRequestPolicy_noneBehavior (14.52s)
--- PASS: TestAccAWSCloudFrontOriginRequestPolicy_basic (14.60s)
--- PASS: TestAccAWSCloudFrontOriginRequestPolicy_update (24.22s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	24.268s
```

2021-01-29 20:17 UTC, YakDriver requested changes
Looks good. Just a few minor changes needed.

2021-01-29 20:17 UTC, YakDriver commented on website/docs/r/cloudfront_origin_request_policy.html.markdown
> +`cookies` - (Optional) An object that contains a list of cookie names. See [Items](#items) for more information.
```suggestion
`cookies` - (Optional) Object that contains a list of cookie names. See [Items](#items) for more information.
```

2021-01-29 20:17 UTC, YakDriver commented on website/docs/r/cloudfront_origin_request_policy.html.markdown
> +`headers` - (Optional) An object that contains a list of header names. See [Items](#items) for more information.
```suggestion
`headers` - (Optional) Object that contains a list of header names. See [Items](#items) for more information.
```

2021-01-29 20:17 UTC, YakDriver commented on website/docs/r/cloudfront_origin_request_policy.html.markdown
> +`query_strings` - (Optional) An object that contains a list of query string names. See [Items](#items) for more information.
```suggestion
`query_strings` - (Optional) Object that contains a list of query string names. See [Items](#items) for more information.
```

2021-01-29 20:17 UTC, YakDriver commented on website/docs/r/cloudfront_origin_request_policy.html.markdown
> +`items` - (Required) A list of item names (cookies, headers, or query strings).
```suggestion
`items` - (Required) List of item names (cookies, headers, or query strings).
```

2021-01-29 20:17 UTC, YakDriver commented on website/docs/r/cloudfront_origin_request_policy.html.markdown
> +* `etag` - The current version of the origin request policy.
```suggestion
* `etag` - Current version of the origin request policy.
```

2021-01-29 20:17 UTC, YakDriver commented on website/docs/r/cloudfront_origin_request_policy.html.markdown
> +* `id` - The identifier for the origin request policy.
```suggestion
* `id` - Identifier for the origin request policy.
```

2021-01-29 20:17 UTC, YakDriver commented on website/docs/d/cloudfront_origin_request_policy.html.markdown
> +  Determines the values that CloudFront includes in requests that it sends to the origin.
```suggestion
  Provides information that CloudFront includes in requests that it sends to the origin.
```

2021-01-29 20:17 UTC, YakDriver commented on website/docs/d/cloudfront_origin_request_policy.html.markdown
> +
```suggestion

Provides an origin request policy, and other metadata, for Amazon CloudFront.

```

2021-01-29 20:17 UTC, YakDriver commented on website/docs/d/cloudfront_origin_request_policy.html.markdown
> +The following example below creates a CloudFront origin request policy.
```suggestion
The following example gets an CloudFront origin request policy.
```

2021-01-29 20:17 UTC, YakDriver commented on website/docs/r/cloudfront_origin_request_policy.html.markdown
> +  Determines the values that CloudFront includes in requests that it sends to the origin.
```suggestion
  Manages an origin request policy for Amazon CloudFront.
```

2021-01-29 20:17 UTC, YakDriver commented on website/docs/r/cloudfront_origin_request_policy.html.markdown
> +
```suggestion

Manages an origin request policy for Amazon CloudFront. After you create an origin request policy, you can attach it to one or more cache behaviors. When it’s attached to a cache behavior, the origin request policy determines the values that CloudFront includes in requests that it sends to the origin.

```

2021-01-29 20:17 UTC, YakDriver commented on website/docs/d/cloudfront_origin_request_policy.html.markdown
> +`query_strings` - An object that contains a list of query string names. See [Items](#items) for more information.
```suggestion
`query_strings` - Object that contains a list of query string names. See [Items](#items) for more information.
```

2021-01-29 20:17 UTC, YakDriver commented on website/docs/d/cloudfront_origin_request_policy.html.markdown
> +`headers` - An object that contains a list of header names. See [Items](#items) for more information.
```suggestion
`headers` - Object that contains a list of header names. See [Items](#items) for more information.
```

2021-01-29 20:17 UTC, YakDriver commented on website/docs/d/cloudfront_origin_request_policy.html.markdown
> +`cookies` - An object that contains a list of cookie names. See [Items](#items) for more information.
```suggestion
`cookies` - Object that contains a list of cookie names. See [Items](#items) for more information.
```

2021-01-29 20:17 UTC, YakDriver commented on website/docs/d/cloudfront_origin_request_policy.html.markdown
> +* `query_strings_config` - An object that determines whether any URL query strings in viewer requests (and if so, which query strings) are included in the origin request key and automatically include
```suggestion
* `query_strings_config` - Object that determines whether any URL query strings in viewer requests (and if so, which query strings) are included in the origin request key and automatically included in requests that CloudFront sends to the origin. See [Query Strings Config](#query-strings-config) for more information.
```

2021-01-29 20:17 UTC, YakDriver commented on website/docs/d/cloudfront_origin_request_policy.html.markdown
> +* `headers_config` - An object that determines whether any HTTP headers (and if so, which headers) are included in the origin request key and automatically included in requests that CloudFront sends
```suggestion
* `headers_config` - Object that determines whether any HTTP headers (and if so, which headers) are included in the origin request key and automatically included in requests that CloudFront sends to the origin. See [Headers Config](#headers-config) for more information.
```

2021-01-29 20:17 UTC, YakDriver commented on website/docs/d/cloudfront_origin_request_policy.html.markdown
> +* `cookies_config` - An object that determines whether any cookies in viewer requests (and if so, which cookies) are included in the origin request key and automatically included in requests that Clo
```suggestion
* `cookies_config` - Object that determines whether any cookies in viewer requests (and if so, which cookies) are included in the origin request key and automatically included in requests that CloudFront sends to the origin. See [Cookies Config](#cookies-config) for more information.
```

2021-01-29 20:17 UTC, YakDriver commented on website/docs/d/cloudfront_origin_request_policy.html.markdown
> +* `comment` - A comment to describe the origin request policy.
```suggestion
* `comment` - Comment to describe the origin request policy.
```

2021-02-04 16:51 UTC, YakDriver approved these changes
This is looking good. Few minors things left (especially `d.IsNewResource()`) and it's good to go!

GovCloud:
```
--- SKIP: TestAccAWSCloudFrontOriginRequestPolicy_basic (1.16s)
--- SKIP: TestAccAWSCloudFrontOriginRequestPolicy_noneBehavior (1.16s)
--- SKIP: TestAccAWSCloudFrontOriginRequestPolicy_update (1.16s)
```

`us-west-2`:
```
--- PASS: TestAccAWSCloudFrontOriginRequestPolicy_basic (10.76s)
--- PASS: TestAccAWSCloudFrontOriginRequestPolicy_noneBehavior (10.77s)
--- PASS: TestAccAWSCloudFrontOriginRequestPolicy_update (17.53s)
```

2021-02-04 16:51 UTC, YakDriver commented on aws/data_source_aws_cloudfront_origin_request_policy.go
> +			return fmt.Errorf("Unable to find origin request policy by name: %s", err.Error())
```suggestion
			return fmt.Errorf("unable to find origin request policy by name: %s", err.Error())
```

2021-02-04 16:51 UTC, YakDriver commented on aws/data_source_aws_cloudfront_origin_request_policy.go
> +			return fmt.Errorf("Unable to retrieve origin request policy with ID %s: %s", d.Id(), err.Error())
```suggestion
			return fmt.Errorf("unable to retrieve origin request policy with ID %s: %s", d.Id(), err.Error())
```

2021-02-04 18:55 UTC, merged

2021-02-14 00:59 UTC, vaskevich commented on aws/resource_aws_cloudfront_distribution.go
> +						"origin_request_policy_id": {
It seems that this new parameter was never added to the documentation.