docs/contributing: Provides correct values for max and min capacity with PostgreSQL
hashicorp/terraform-provider-aws pull request #17551
Opened 2021-02-10 16:48 UTC by lmammino

This PR updates the `Resource: aws_rds_cluster` documentation page with the correct list of accepted values for `min_capacity ` and `max_capacity ` when using PostgreSQL.

From the AWS docs: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless.setting-capacity.html

![Screenshot 2021-02-10 at 16 43 54](https://user-images.githubusercontent.com/205629/107542081-b8e6ef80-6bbf-11eb-86b4-0a8a79b573c2.png)

2021-02-11 16:16 UTC, breathingdust requested changes

2021-02-11 16:16 UTC, breathingdust commented on website/docs/r/rds_cluster.html.markdown
> +* `max_capacity` - (Optional) The maximum capacity. The maximum capacity must be greater than or equal to the minimum capacity. Valid capacity values are `1`, `2`, `4`, `8`, `16`, `32`, `64`, `128`,
Thanks for this @lmammino, looking at the docs though it looks like 1 is not a valid capacity value for PostgreSQL and its likely better we are explicit that it applies to Aurora.

```suggestion
* `max_capacity` - (Optional) The maximum capacity for an Aurora DB cluster in `serverless` DB engine mode. The maximum capacity must be greater than or equal to the minimum capacity. Valid Aurora MySQL capacity values are `1`, `2`, `4`, `8`, `16`, `32`, `64`, `128`, `256`. Valid Aurora PostgreSQL capacity values are (`2`, `4`, `8`, `16`, `32`, `64`, `192`, and `384`). Defaults to `16`.
```

2021-02-11 16:16 UTC, breathingdust commented on website/docs/r/rds_cluster.html.markdown
> +* `min_capacity` - (Optional) The minimum capacity. The minimum capacity must be lesser than or equal to the maximum capacity. Valid capacity values are `1`, `2`, `4`, `8`, `16`, `32`, `64`, `128`, a
```suggestion
* `min_capacity` - (Optional) The minimum capacity for an Aurora DB cluster in `serverless` DB engine mode. The minimum capacity must be lesser than or equal to the maximum capacity. Valid Aurora MySQL capacity values are `1`, `2`, `4`, `8`, `16`, `32`, `64`, `128`, `256`. Valid Aurora PostgreSQL capacity values are (`2`, `4`, `8`, `16`, `32`, `64`, `192`, and `384`). Defaults to `1`.
```

2021-02-11 23:48 UTC, breathingdust commented
LGTM 🚀 Thanks @lmammino!

2021-02-11 23:48 UTC, merged

2021-02-12 10:16 UTC, lmammino commented
Happy that this was useful! Thanks for the great review, @breathingdust !

When is this going to be relesed?