Update provider development docs to include development overrides
hashicorp/terraform-provider-aws pull request #17664
Opened 2021-02-17 17:36 UTC by korenyoni

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

### Documentation Updates for Provider Development

1. Document use of [development overrides for provider developers](https://www.terraform.io/docs/cli/config/config-file.html#development-overrides-for-provider-developers) for using the Terraform Provider for AWS which was built from source.

2021-03-18 21:59 UTC, anGie44 commented on docs/DEVELOPMENT.md
> +To do this, populate a Terraform CLI configuration file can be created (in `~/.terraformrc` for all platforms other than Windows; in `terraform.rc` in the `%APPDATA%` directory when using Windows) wi
```suggestion
To do this, populate a Terraform CLI configuration file (`~/.terraformrc` for all platforms other than Windows; `terraform.rc` in the `%APPDATA%` directory when using Windows) with at least the following options:
```

2021-03-18 22:01 UTC, anGie44 commented on docs/DEVELOPMENT.md
> +```
```suggestion
```hcl
provider_installation {
  dev_overrides {
    "hashicorp/aws" = "[REPLACE WITH GOPATH]/bin"
  }
  direct {}
}
```
```

2021-03-18 22:02 UTC, anGie44 requested changes
Love this addition @korenyoni , just a couple nit's for review !

2021-03-19 05:49 UTC, korenyoni commented
Thanks for the review @anGie44! I've addressed your review.

2021-04-02 20:43 UTC, anGie44 approved these changes
Apologies for the delay @korenyoni , changes look great 🚀 !

2021-04-02 20:44 UTC, merged