[WIP] r/aws_globalaccelerator_accelerator: Correctly update flow log attributes when enabled
hashicorp/terraform-provider-aws pull request #17739
Opened 2021-02-21 23:43 UTC by ewbankkit

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #14185.

Output from acceptance testing:

```
TODO
```

2021-02-25 22:49 UTC, DrFaust92 requested changes
Changelog comment otherwise LGTM:


messed up output but all tests passed :D
```
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       2636.305s
```

2021-02-26 13:55 UTC, ewbankkit commented on .changelog/17739.txt
> +```
Done.

2021-02-26 13:56 UTC, DrFaust92 approved these changes
LGTM!

2021-03-04 18:31 UTC, breathingdust commented
LGTM :rocket: Thanks @ewbankkit!

Verified Acceptance Tests in Commercial (us-west-2)

```console
ACCTEST_PARALLELISM=2 make testacc TEST=./aws/ TESTARGS='-run=TestAccAwsGlobalAcceleratorEndpointGroup_\|TestAccAwsGlobalAcceleratorListener_\|TestAccAwsGlobalAcceleratorAccelerator_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAwsGlobalAcceleratorEndpointGroup_\|TestAccAwsGlobalAcceleratorListener_\|TestAccAwsGlobalAcceleratorAccelerator_ -timeout 120m
=== RUN   TestAccAwsGlobalAcceleratorAccelerator_basic
=== PAUSE TestAccAwsGlobalAcceleratorAccelerator_basic
=== RUN   TestAccAwsGlobalAcceleratorAccelerator_disappears
=== PAUSE TestAccAwsGlobalAcceleratorAccelerator_disappears
=== RUN   TestAccAwsGlobalAcceleratorAccelerator_update
=== PAUSE TestAccAwsGlobalAcceleratorAccelerator_update
=== RUN   TestAccAwsGlobalAcceleratorAccelerator_attributes
=== PAUSE TestAccAwsGlobalAcceleratorAccelerator_attributes
=== RUN   TestAccAwsGlobalAcceleratorAccelerator_tags
=== PAUSE TestAccAwsGlobalAcceleratorAccelerator_tags
=== RUN   TestAccAwsGlobalAcceleratorEndpointGroup_basic
=== PAUSE TestAccAwsGlobalAcceleratorEndpointGroup_basic
=== RUN   TestAccAwsGlobalAcceleratorEndpointGroup_disappears
=== PAUSE TestAccAwsGlobalAcceleratorEndpointGroup_disappears
=== RUN   TestAccAwsGlobalAcceleratorEndpointGroup_ALBEndpoint_ClientIP
=== PAUSE TestAccAwsGlobalAcceleratorEndpointGroup_ALBEndpoint_ClientIP
=== RUN   TestAccAwsGlobalAcceleratorEndpointGroup_InstanceEndpoint
=== PAUSE TestAccAwsGlobalAcceleratorEndpointGroup_InstanceEndpoint
=== RUN   TestAccAwsGlobalAcceleratorEndpointGroup_MultiRegion
=== PAUSE TestAccAwsGlobalAcceleratorEndpointGroup_MultiRegion
=== RUN   TestAccAwsGlobalAcceleratorEndpointGroup_PortOverrides
=== PAUSE TestAccAwsGlobalAcceleratorEndpointGroup_PortOverrides
=== RUN   TestAccAwsGlobalAcceleratorEndpointGroup_TCPHealthCheckProtocol
=== PAUSE TestAccAwsGlobalAcceleratorEndpointGroup_TCPHealthCheckProtocol
=== RUN   TestAccAwsGlobalAcceleratorEndpointGroup_Update
=== PAUSE TestAccAwsGlobalAcceleratorEndpointGroup_Update
=== RUN   TestAccAwsGlobalAcceleratorListener_basic
=== PAUSE TestAccAwsGlobalAcceleratorListener_basic
=== RUN   TestAccAwsGlobalAcceleratorListener_disappears
=== PAUSE TestAccAwsGlobalAcceleratorListener_disappears
=== RUN   TestAccAwsGlobalAcceleratorListener_update
=== PAUSE TestAccAwsGlobalAcceleratorListener_update
=== CONT  TestAccAwsGlobalAcceleratorAccelerator_basic
=== CONT  TestAccAwsGlobalAcceleratorEndpointGroup_MultiRegion
--- PASS: TestAccAwsGlobalAcceleratorAccelerator_basic (67.36s)
=== CONT  TestAccAwsGlobalAcceleratorListener_update
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_MultiRegion (181.51s)
=== CONT  TestAccAwsGlobalAcceleratorListener_disappears
--- PASS: TestAccAwsGlobalAcceleratorListener_update (160.94s)
=== CONT  TestAccAwsGlobalAcceleratorListener_basic
--- PASS: TestAccAwsGlobalAcceleratorListener_disappears (174.83s)
=== CONT  TestAccAwsGlobalAcceleratorEndpointGroup_Update
--- PASS: TestAccAwsGlobalAcceleratorListener_basic (164.28s)
=== CONT  TestAccAwsGlobalAcceleratorEndpointGroup_TCPHealthCheckProtocol
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_Update (211.11s)
=== CONT  TestAccAwsGlobalAcceleratorEndpointGroup_PortOverrides
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_TCPHealthCheckProtocol (175.23s)
=== CONT  TestAccAwsGlobalAcceleratorEndpointGroup_basic
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_basic (237.50s)
=== CONT  TestAccAwsGlobalAcceleratorEndpointGroup_InstanceEndpoint
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_PortOverrides (273.92s)
=== CONT  TestAccAwsGlobalAcceleratorEndpointGroup_ALBEndpoint_ClientIP
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_InstanceEndpoint (553.56s)
=== CONT  TestAccAwsGlobalAcceleratorEndpointGroup_disappears
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_ALBEndpoint_ClientIP (699.12s)
=== CONT  TestAccAwsGlobalAcceleratorAccelerator_attributes
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_disappears (182.40s)
=== CONT  TestAccAwsGlobalAcceleratorAccelerator_tags
--- PASS: TestAccAwsGlobalAcceleratorAccelerator_tags (87.64s)
=== CONT  TestAccAwsGlobalAcceleratorAccelerator_update
--- PASS: TestAccAwsGlobalAcceleratorAccelerator_update (165.20s)
=== CONT  TestAccAwsGlobalAcceleratorAccelerator_disappears
--- PASS: TestAccAwsGlobalAcceleratorAccelerator_attributes (292.03s)
--- PASS: TestAccAwsGlobalAcceleratorAccelerator_disappears (71.46s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1868.914s
```

2021-03-04 18:31 UTC, merged