Add CodeStar Connection data source
hashicorp/terraform-provider-aws pull request #18129
Opened 2021-03-16 22:57 UTC by shuheiktgw

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates https://github.com/hashicorp/terraform-provider-aws/issues/15453

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2021-03-19 00:19 UTC, bflad requested changes
Some minor testing updates, otherwise this is looking really good, thank you @shuheiktgw 🎉

2021-03-19 00:19 UTC, bflad commented on aws/data_source_aws_codestarconnections_connection_test.go
> +		Providers: testAccProviders,
We are currently in the process of adding `ErrorCheck` to each of the acceptance tests. Reference: https://github.com/hashicorp/terraform-provider-aws/issues/18175

Can you please add this here? Thank you!

```suggestion
		PreCheck:   func() { testAccPreCheck(t); testAccPartitionHasServicePreCheck(codestarconnections.EndpointsID, t) },
		ErrorCheck: testAccErrorCheck(t, codestarconnections.EndpointsID),
		Providers:  testAccProviders,
```

2021-03-19 00:19 UTC, bflad commented on aws/data_source_aws_codestarconnections_connection_test.go
> +					resource.TestCheckResourceAttr(resourceName, "connection_status", codestarconnections.ConnectionStatusPending),
For data source testing, we prefer using `resource.TestCheckResourceAttrPair()` where possible to simplify it. 👍  Reference: https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/running-and-writing-acceptance-tests.md#data-source-acceptance-testing

```suggestion
					resource.TestCheckResourceAttrPair(dataSourceName, "arn", resourceName, "arn"),
					resource.TestCheckResourceAttrPair(dataSourceName, "connection_status", resourceName, "connection_status"),
					resource.TestCheckResourceAttrPair(dataSourceName, "id", resourceName, "id"),
					resource.TestCheckResourceAttrPair(dataSourceName, "provider_type", resourceName, "provider_type"),
					resource.TestCheckResourceAttrPair(dataSourceName, "name", resourceName, "name"),
					resource.TestCheckResourceAttrPair(dataSourceName, "tags.%", resourceName, "tags.%"),
```

2021-03-19 00:19 UTC, bflad commented on aws/data_source_aws_codestarconnections_connection_test.go
> +	resourceName := "data.aws_codestarconnections_connection.test"
Similarly:

```suggestion
	dataSourceName := "data.aws_codestarconnections_connection.test"
	resourceName := "aws_codestarconnections_connection.test"
```

2021-03-19 00:19 UTC, bflad commented on aws/data_source_aws_codestarconnections_connection_test.go
> +		Providers: testAccProviders,
Similarly:

```suggestion
		PreCheck:   func() { testAccPreCheck(t); testAccPartitionHasServicePreCheck(codestarconnections.EndpointsID, t) },
		ErrorCheck: testAccErrorCheck(t, codestarconnections.EndpointsID),
		Providers:  testAccProviders,
```

2021-03-19 02:41 UTC, shuheiktgw commented
Thanks, @bflad! Updated the tests, so would you review the PR again?

```
$ make testacc TESTARGS='-run=TestAccDataSourceAwsCodeStarConnectionsConnection_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccDataSourceAwsCodeStarConnectionsConnection_ -timeout 180m
go: downloading github.com/hashicorp/go-multierror v1.1.1
=== RUN   TestAccDataSourceAwsCodeStarConnectionsConnection_basic
=== PAUSE TestAccDataSourceAwsCodeStarConnectionsConnection_basic
=== RUN   TestAccDataSourceAwsCodeStarConnectionsConnection_tags
=== PAUSE TestAccDataSourceAwsCodeStarConnectionsConnection_tags
=== CONT  TestAccDataSourceAwsCodeStarConnectionsConnection_basic
=== CONT  TestAccDataSourceAwsCodeStarConnectionsConnection_tags
--- PASS: TestAccDataSourceAwsCodeStarConnectionsConnection_basic (45.73s)
--- PASS: TestAccDataSourceAwsCodeStarConnectionsConnection_tags (68.08s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	69.859s
```

2021-03-19 13:16 UTC, bflad approved these changes
Looks good to me 🚀  (Forgot to mention adding a changelog entry before 😅  will do so on merge)

Output from acceptance testing:

```
--- PASS: TestAccDataSourceAwsCodeStarConnectionsConnection_basic (19.66s)
--- PASS: TestAccDataSourceAwsCodeStarConnectionsConnection_tags (19.69s)

--- PASS: TestAccAWSCodeStarConnectionsConnection_disappears (12.08s)
--- PASS: TestAccAWSCodeStarConnectionsConnection_Basic (16.27s)
--- PASS: TestAccAWSCodeStarConnectionsConnection_Tags (35.69s)
```

2021-03-19 13:17 UTC, merged

2021-03-21 05:18 UTC, shuheiktgw commented
Thank you for your review, @bflad!