Add support for aws_cloudwatch_metric_stream
hashicorp/terraform-provider-aws pull request #18870
Opened 2021-04-14 23:41 UTC by gcacace

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #18525

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSCloudWatchMetricStream'
```

2021-04-16 18:29 UTC, YakDriver commented
@gcacace After a quick scan, this PR is looking good. Overall, the neatness and completeness, with implementation, docs, tests, is great! Thank you for submitting it! I may point out a few minor items. Also, I encourage you to check the "allow edits by maintainers" box to facilitate getting this merged more quickly.

2021-04-16 19:05 UTC, YakDriver requested changes
Thanks for you time on this!

2021-04-16 19:05 UTC, YakDriver commented on website/docs/r/cloudwatch_metric_stream.html.markdown
> +The following arguments are supported:
Split args into two lists:

The following arguments are required:

* `firehose_arn` 
* ...

The following arguments are optional:

* `exclude_filter`...
* ...

2021-04-16 19:05 UTC, YakDriver commented on website/docs/r/cloudwatch_metric_stream.html.markdown
> +### Nested fields
```suggestion
```

2021-04-16 19:05 UTC, YakDriver commented on website/docs/r/cloudwatch_metric_stream.html.markdown
> +#### `exclude_filter`
```suggestion
### `exclude_filter`
```

2021-04-16 19:05 UTC, YakDriver commented on website/docs/r/cloudwatch_metric_stream.html.markdown
> +#### `include_filter`
```suggestion
### `include_filter`
```

2021-04-16 19:05 UTC, YakDriver commented on website/docs/r/cloudwatch_metric_stream.html.markdown
> +* `arn` - The Amazon Resource Name (ARN) of the metric stream.
```suggestion
* `arn` - ARN of the metric stream.
```
Here and everywhere, fully spelled out is not necessary.

2021-04-16 19:05 UTC, YakDriver commented on website/docs/r/cloudwatch_metric_stream.html.markdown
> +* `output_format` - (Required) The output format for the stream. For more information about metric stream output formats, see [Metric streams output formats](https://docs.aws.amazon.com/AmazonCloudWa
```suggestion
* `output_format` - (Required) Output format for the stream. For more information about metric stream output formats, see [Metric streams output formats](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-metric-streams-formats.html).
```
Here and everywhere. Best practice is to drop the first article ("The", "A", "An) after either "(Optional)" or "(Required)".

2021-04-16 22:26 UTC, gcacace commented on aws/resource_aws_cloudwatch_metric_stream.go
> +func resourceAwsCloudWatchMetricStreamPut(d *schema.ResourceData, meta interface{}) error {
I can change the method to be `Create`. Would it then be ok to use that `Create` method for both `Create` and `Update` terraform actions? (Metric Streams don't have an Update API method, they use `PutMetricStream` to both create/update.

2021-04-16 23:40 UTC, gcacace commented on aws/resource_aws_cloudwatch_metric_stream.go
> +			"arn": {
You're welcome!

2021-04-17 06:51 UTC, gcacace commented on aws/resource_aws_cloudwatch_metric_stream.go
> +	resp, err := conn.GetMetricStream(&params)
Done!

2021-04-17 06:51 UTC, gcacace commented on aws/resource_aws_cloudwatch_metric_stream.go
> +	if resp.IncludeFilters != nil && len(resp.IncludeFilters) > 0 {
Done!

2021-04-19 22:00 UTC, gcacace commented
Hi @YakDriver, wondering if I've missed anything here apart from your comments that I've addressed in the latest revision.

2021-04-28 13:43 UTC, frankreno commented
Hi Folks, is there any eta on when this will be merged, released, and supported by TF? This is a great add we are ourselves waiting on.

2021-05-05 14:02 UTC, gcacace commented
@YakDriver it has been almost 20 days since I've replied and fix all the review comments. Is there any chance we can get this merged?

2021-05-18 01:20 UTC, YakDriver commented
@gcacace I was unable to push to your branch to fix remaining issues. I'm not sure if you "allow edits by maintainers" or if it fails because your branch name is "main." It is best to name branches following the convention of `f-` prefix for features, like a new resource (`d-` for docs, `td-` for technical debt, `b-` for bugs). One thing I notice that you'll need is to add, since the resource has tags, is the default tags capability. All resources should now have them. You can find examples in any resource with tags. Fixes needed for default tags:

1. `tags_all` addition to schema
2. Create: `defaultTagsConfig` addition, calculate `tags` var with `MergeTags()`, `tags.IgnoreAWS()...`
3. Read: `defaultTagsConfig`, `ignoreTagsConfig` additions, `if err := d.Set("tags"...`, `if err := d.Set("tags_all"...`
4. Update: `if d.HasChang("tags_all")...`

2021-05-18 19:40 UTC, YakDriver commented
This will be superceded by #19429

2021-05-19 01:55 UTC, closed without merging