resource/aws_appsync_graphql_api: Add `lambda_authorizer_config` argument
hashicorp/terraform-provider-aws pull request #20857
Opened 2021-09-09 15:54 UTC by Pharb

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #20644

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSAppsyncGraphqlApi_'                                  
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAppsyncGraphqlApi_ -timeout 180m
=== RUN   TestAccAWSAppsyncGraphqlApi_basic
=== PAUSE TestAccAWSAppsyncGraphqlApi_basic
=== RUN   TestAccAWSAppsyncGraphqlApi_disappears
=== PAUSE TestAccAWSAppsyncGraphqlApi_disappears
=== RUN   TestAccAWSAppsyncGraphqlApi_Schema
=== PAUSE TestAccAWSAppsyncGraphqlApi_Schema
=== RUN   TestAccAWSAppsyncGraphqlApi_AuthenticationType
=== PAUSE TestAccAWSAppsyncGraphqlApi_AuthenticationType
=== RUN   TestAccAWSAppsyncGraphqlApi_AuthenticationType_APIKey
=== PAUSE TestAccAWSAppsyncGraphqlApi_AuthenticationType_APIKey
=== RUN   TestAccAWSAppsyncGraphqlApi_AuthenticationType_AWSIAM
=== PAUSE TestAccAWSAppsyncGraphqlApi_AuthenticationType_AWSIAM
=== RUN   TestAccAWSAppsyncGraphqlApi_AuthenticationType_AmazonCognitoUserPools
=== PAUSE TestAccAWSAppsyncGraphqlApi_AuthenticationType_AmazonCognitoUserPools
=== RUN   TestAccAWSAppsyncGraphqlApi_AuthenticationType_OpenIDConnect
=== PAUSE TestAccAWSAppsyncGraphqlApi_AuthenticationType_OpenIDConnect
=== RUN   TestAccAWSAppsyncGraphqlApi_AuthenticationType_AwsLambda
=== PAUSE TestAccAWSAppsyncGraphqlApi_AuthenticationType_AwsLambda
=== RUN   TestAccAWSAppsyncGraphqlApi_LogConfig
=== PAUSE TestAccAWSAppsyncGraphqlApi_LogConfig
=== RUN   TestAccAWSAppsyncGraphqlApi_LogConfig_FieldLogLevel
=== PAUSE TestAccAWSAppsyncGraphqlApi_LogConfig_FieldLogLevel
=== RUN   TestAccAWSAppsyncGraphqlApi_LogConfig_ExcludeVerboseContent
=== PAUSE TestAccAWSAppsyncGraphqlApi_LogConfig_ExcludeVerboseContent
=== RUN   TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_AuthTTL
=== PAUSE TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_AuthTTL
=== RUN   TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_ClientID
=== PAUSE TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_ClientID
=== RUN   TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_IatTTL
=== PAUSE TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_IatTTL
=== RUN   TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_Issuer
=== PAUSE TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_Issuer
=== RUN   TestAccAWSAppsyncGraphqlApi_Name
=== PAUSE TestAccAWSAppsyncGraphqlApi_Name
=== RUN   TestAccAWSAppsyncGraphqlApi_UserPoolConfig_AwsRegion
=== PAUSE TestAccAWSAppsyncGraphqlApi_UserPoolConfig_AwsRegion
=== RUN   TestAccAWSAppsyncGraphqlApi_UserPoolConfig_DefaultAction
=== PAUSE TestAccAWSAppsyncGraphqlApi_UserPoolConfig_DefaultAction
=== RUN   TestAccAWSAppsyncGraphqlApi_LambdaAuthorizerConfig_AuthorizerUri
=== PAUSE TestAccAWSAppsyncGraphqlApi_LambdaAuthorizerConfig_AuthorizerUri
=== RUN   TestAccAWSAppsyncGraphqlApi_LambdaAuthorizerConfig_IdentityValidationExpression
=== PAUSE TestAccAWSAppsyncGraphqlApi_LambdaAuthorizerConfig_IdentityValidationExpression
=== RUN   TestAccAWSAppsyncGraphqlApi_LambdaAuthorizerConfig_AuthorizerResultTtlInSeconds
=== PAUSE TestAccAWSAppsyncGraphqlApi_LambdaAuthorizerConfig_AuthorizerResultTtlInSeconds
=== RUN   TestAccAWSAppsyncGraphqlApi_Tags
=== PAUSE TestAccAWSAppsyncGraphqlApi_Tags
=== RUN   TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_APIKey
=== PAUSE TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_APIKey
=== RUN   TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_AWSIAM
=== PAUSE TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_AWSIAM
=== RUN   TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_CognitoUserPools
=== PAUSE TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_CognitoUserPools
=== RUN   TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_OpenIDConnect
=== PAUSE TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_OpenIDConnect
=== RUN   TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_AwsLambda
=== PAUSE TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_AwsLambda
=== RUN   TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_Multiple
=== PAUSE TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_Multiple
=== RUN   TestAccAWSAppsyncGraphqlApi_XrayEnabled
=== PAUSE TestAccAWSAppsyncGraphqlApi_XrayEnabled
=== CONT  TestAccAWSAppsyncGraphqlApi_basic
=== CONT  TestAccAWSAppsyncGraphqlApi_Name
=== CONT  TestAccAWSAppsyncGraphqlApi_XrayEnabled
=== CONT  TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_AuthTTL
=== CONT  TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_AWSIAM
=== CONT  TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_AwsLambda
=== CONT  TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_OpenIDConnect
=== CONT  TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_Multiple
=== CONT  TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_CognitoUserPools
=== CONT  TestAccAWSAppsyncGraphqlApi_UserPoolConfig_DefaultAction
=== CONT  TestAccAWSAppsyncGraphqlApi_LambdaAuthorizerConfig_AuthorizerUri
=== CONT  TestAccAWSAppsyncGraphqlApi_AuthenticationType_AwsLambda
=== CONT  TestAccAWSAppsyncGraphqlApi_LogConfig_ExcludeVerboseContent
=== CONT  TestAccAWSAppsyncGraphqlApi_LogConfig_FieldLogLevel
=== CONT  TestAccAWSAppsyncGraphqlApi_LambdaAuthorizerConfig_IdentityValidationExpression
=== CONT  TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_APIKey
=== CONT  TestAccAWSAppsyncGraphqlApi_UserPoolConfig_AwsRegion
=== CONT  TestAccAWSAppsyncGraphqlApi_Tags
=== CONT  TestAccAWSAppsyncGraphqlApi_LogConfig
=== CONT  TestAccAWSAppsyncGraphqlApi_LambdaAuthorizerConfig_AuthorizerResultTtlInSeconds
--- PASS: TestAccAWSAppsyncGraphqlApi_basic (147.72s)
=== CONT  TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_IatTTL
--- PASS: TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_AWSIAM (148.24s)
=== CONT  TestAccAWSAppsyncGraphqlApi_AuthenticationType_APIKey
--- PASS: TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_APIKey (149.20s)
=== CONT  TestAccAWSAppsyncGraphqlApi_AuthenticationType_OpenIDConnect
--- PASS: TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_OpenIDConnect (149.32s)
=== CONT  TestAccAWSAppsyncGraphqlApi_AuthenticationType_AmazonCognitoUserPools
--- PASS: TestAccAWSAppsyncGraphqlApi_LogConfig (153.51s)
=== CONT  TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_Issuer
--- PASS: TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_CognitoUserPools (173.33s)
=== CONT  TestAccAWSAppsyncGraphqlApi_Schema
--- PASS: TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_AwsLambda (196.04s)
=== CONT  TestAccAWSAppsyncGraphqlApi_AuthenticationType
--- PASS: TestAccAWSAppsyncGraphqlApi_AdditionalAuthentication_Multiple (204.38s)
=== CONT  TestAccAWSAppsyncGraphqlApi_AuthenticationType_AWSIAM
--- PASS: TestAccAWSAppsyncGraphqlApi_XrayEnabled (214.18s)
=== CONT  TestAccAWSAppsyncGraphqlApi_disappears
--- PASS: TestAccAWSAppsyncGraphqlApi_Name (215.34s)
=== CONT  TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_ClientID
--- PASS: TestAccAWSAppsyncGraphqlApi_AuthenticationType_AwsLambda (221.80s)
--- PASS: TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_AuthTTL (235.05s)
--- PASS: TestAccAWSAppsyncGraphqlApi_Tags (236.82s)
--- PASS: TestAccAWSAppsyncGraphqlApi_UserPoolConfig_AwsRegion (242.45s)
--- PASS: TestAccAWSAppsyncGraphqlApi_LogConfig_ExcludeVerboseContent (250.77s)
--- PASS: TestAccAWSAppsyncGraphqlApi_UserPoolConfig_DefaultAction (250.94s)
--- PASS: TestAccAWSAppsyncGraphqlApi_AuthenticationType_APIKey (116.05s)
--- PASS: TestAccAWSAppsyncGraphqlApi_AuthenticationType_OpenIDConnect (115.22s)
--- PASS: TestAccAWSAppsyncGraphqlApi_AuthenticationType_AmazonCognitoUserPools  [...]

2021-09-13 10:19 UTC, Pharb commented
There might be one `tflint` failure in the pipeline, but this should be fixed by updating it with https://github.com/terraform-linters/tflint-ruleset-aws/commit/dd2461d27a19a26f4fe95ab9885e90ac4588277b (for now I wouldn't add this to this PR, as I'm not familiar with the dependency update process and don't want to provoke merge conflicts).

2021-09-28 19:25 UTC, grgizem commented
nice work @Pharb ! <3

@justinretzolk is there any ETA on this pull request?

2021-09-30 21:05 UTC, justinretzolk commented
Hey @grgizem 👋 Thank you for your interest in this PR! Unfortunately, I'm not able to provide an exact timeline for review/merge, however, if you've not already, please do make sure to leave a ":thumbsup:" reaction to the initial PR as it helps the team to prioritize work based on community feedback!

2021-11-10 11:40 UTC, filipjakubowski commented
@Pharb - do you need help with resolving conflicts?

2021-11-11 14:48 UTC, Pharb commented
> do you need help with resolving conflicts?

@filipjakubowski Thanks for your support, but as far as I understood the instructions I would just wait until a maintainer picks this PR up next:

> [...] resolving these conflicts in no way affects the prioritization of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

2021-11-11 15:47 UTC, filipjakubowski commented
Great.... I would really want to have Lambda Authoriser in Terraform. I have to set this manually after each run of `terraform apply`

2021-11-21 18:25 UTC, lescaudr commented
Can you please check the conflicts? I would love to use this feature :)

2021-12-03 22:47 UTC, AdamTylerLynch commented
LGTM :rocket:

2021-12-09 21:46 UTC, AdamTylerLynch requested changes

2021-12-10 14:57 UTC, Pharb commented on internal/service/appsync/graphql_api.go
> +			"lambda_authorizer_config": flattenAppsyncGraphqlApiLambdaAuthorizerConfig(provider.LambdaAuthorizerConfig),
Thanks for reviewing! 👍 I updated the sorting here.

2021-12-10 23:10 UTC, breathingdust commented
LGTM 🚀 Thanks @Pharb for the contribution 🙌 

Verified Acceptance Tests in Commerical (us-west-2)

```console
make testacc TESTARGS='-run=TestAccAppSync_serial' PKG_NAME=internal/service/appsync
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/appsync/... -v -count 1 -parallel 20 -run=TestAccAppSync_serial -timeout 180m
=== RUN   TestAccAppSync_serial
=== RUN   TestAccAppSync_serial/APIKey
=== RUN   TestAccAppSync_serial/APIKey/basic
=== RUN   TestAccAppSync_serial/APIKey/description
=== RUN   TestAccAppSync_serial/APIKey/expires
=== RUN   TestAccAppSync_serial/DataSource
=== RUN   TestAccAppSync_serial/DataSource/type
=== RUN   TestAccAppSync_serial/DataSource/Type_dynamoDB
=== RUN   TestAccAppSync_serial/DataSource/Type_http
=== RUN   TestAccAppSync_serial/DataSource/Type_none
=== RUN   TestAccAppSync_serial/DataSource/DynamoDB_region
=== RUN   TestAccAppSync_serial/DataSource/HTTP_endpoint
=== RUN   TestAccAppSync_serial/DataSource/DynamoDB_useCallerCredentials
=== RUN   TestAccAppSync_serial/DataSource/Type_lambda
=== RUN   TestAccAppSync_serial/DataSource/basic
=== RUN   TestAccAppSync_serial/DataSource/description
=== RUN   TestAccAppSync_serial/GraphQLAPI
=== RUN   TestAccAppSync_serial/GraphQLAPI/name
=== RUN   TestAccAppSync_serial/GraphQLAPI/AdditionalAuthentication_openIDConnect
=== RUN   TestAccAppSync_serial/GraphQLAPI/UserPool_defaultAction
=== RUN   TestAccAppSync_serial/GraphQLAPI/AuthenticationType_apiKey
=== RUN   TestAccAppSync_serial/GraphQLAPI/AuthenticationType_openIDConnect
=== RUN   TestAccAppSync_serial/GraphQLAPI/Log_excludeVerboseContent
=== RUN   TestAccAppSync_serial/GraphQLAPI/AdditionalAuthentication_cognitoUserPools
=== RUN   TestAccAppSync_serial/GraphQLAPI/basic
=== RUN   TestAccAppSync_serial/GraphQLAPI/disappears
=== RUN   TestAccAppSync_serial/GraphQLAPI/AdditionalAuthentication_awsLambda
=== PAUSE TestAccAppSync_serial/GraphQLAPI/AdditionalAuthentication_awsLambda
=== RUN   TestAccAppSync_serial/GraphQLAPI/AuthenticationType_amazonCognitoUserPools
=== RUN   TestAccAppSync_serial/GraphQLAPI/AdditionalAuthentication_apiKey
=== RUN   TestAccAppSync_serial/GraphQLAPI/OpenIDConnect_issuer
=== RUN   TestAccAppSync_serial/GraphQLAPI/UserPool_awsRegion
=== RUN   TestAccAppSync_serial/GraphQLAPI/AdditionalAuthentication_awsIAM
=== RUN   TestAccAppSync_serial/GraphQLAPI/AuthenticationType_awsLambda
=== PAUSE TestAccAppSync_serial/GraphQLAPI/AuthenticationType_awsLambda
=== RUN   TestAccAppSync_serial/GraphQLAPI/OpenIDConnect_authTTL
=== RUN   TestAccAppSync_serial/GraphQLAPI/AdditionalAuthentication_multiple
=== RUN   TestAccAppSync_serial/GraphQLAPI/xrayEnabled
=== RUN   TestAccAppSync_serial/GraphQLAPI/authenticationType
=== RUN   TestAccAppSync_serial/GraphQLAPI/tags
=== RUN   TestAccAppSync_serial/GraphQLAPI/log
=== RUN   TestAccAppSync_serial/GraphQLAPI/Log_fieldLogLevel
=== RUN   TestAccAppSync_serial/GraphQLAPI/LambdaAuthorizerConfig_authorizerResultTtlInSeconds
=== PAUSE TestAccAppSync_serial/GraphQLAPI/LambdaAuthorizerConfig_authorizerResultTtlInSeconds
=== RUN   TestAccAppSync_serial/GraphQLAPI/schema
=== RUN   TestAccAppSync_serial/GraphQLAPI/AuthenticationType_awsIAM
=== RUN   TestAccAppSync_serial/GraphQLAPI/LambdaAuthorizerConfig_authorizerUri
=== PAUSE TestAccAppSync_serial/GraphQLAPI/LambdaAuthorizerConfig_authorizerUri
=== RUN   TestAccAppSync_serial/GraphQLAPI/LambdaAuthorizerConfig_identityValidationExpression
=== PAUSE TestAccAppSync_serial/GraphQLAPI/LambdaAuthorizerConfig_identityValidationExpression
=== RUN   TestAccAppSync_serial/GraphQLAPI/OpenIDConnect_clientID
=== RUN   TestAccAppSync_serial/GraphQLAPI/OpenIDConnect_iatTTL
=== CONT  TestAccAppSync_serial/GraphQLAPI/AdditionalAuthentication_awsLambda
=== CONT  TestAccAppSync_serial/GraphQLAPI/LambdaAuthorizerConfig_identityValidationExpression
=== CONT  TestAccAppSync_serial/GraphQLAPI/LambdaAuthorizerConfig_authorizerResultTtlInSeconds
=== CONT  TestAccAppSync_serial/GraphQLAPI/AuthenticationType_awsLambda
=== CONT  TestAccAppSync_serial/GraphQLAPI/LambdaAuthorizerConfig_authorizerUri
=== RUN   TestAccAppSync_serial/Function
=== RUN   TestAccAppSync_serial/Function/basic
=== RUN   TestAccAppSync_serial/Function/disappears
=== RUN   TestAccAppSync_serial/Function/description
=== RUN   TestAccAppSync_serial/Function/responseMappingTemplate
=== RUN   TestAccAppSync_serial/Resolver
=== RUN   TestAccAppSync_serial/Resolver/requestTemplate
=== RUN   TestAccAppSync_serial/Resolver/responseTemplate
=== RUN   TestAccAppSync_serial/Resolver/multipleResolvers
=== RUN   TestAccAppSync_serial/Resolver/caching
=== RUN   TestAccAppSync_serial/Resolver/dataSource
=== RUN   TestAccAppSync_serial/Resolver/disappears
=== RUN   TestAccAppSync_serial/Resolver/DataSource_lambda
=== RUN   TestAccAppSync_serial/Resolver/pipeline
=== RUN   TestAccAppSync_serial/Resolver/basic
--- PASS: TestAccAppSync_serial (1713.37s)
    --- PASS: TestAccAppSync_serial/APIKey (94.93s)
        --- PASS: TestAccAppSync_serial/APIKey/basic (26.62s)
        --- PASS: TestAccAppSync_serial/APIKey/description (30.42s)
        --- PASS: TestAccAppSync_serial/APIKey/expires (37.89s)
    --- PASS: TestAccAppSync_serial/DataSource (379.69s)
        --- PASS: TestAccAppSync_serial/DataSource/type (30.85s)
        --- PASS: TestAccAppSync_serial/DataSource/Type_dynamoDB (32.42s)
        --- PASS: TestAccAppSync_serial/DataSource/Type_http (17.82s)
        --- PASS: TestAccAppSync_serial/DataSource/Type_none (21.20s)
        --- PASS: TestAccAppSync_serial/DataSource/DynamoDB_region (53.17s)
        --- PASS: TestAccAppSync_serial/DataSource/HTTP_endpoint (41.18s)
        --- PASS: TestAccAppSync_serial/DataSource/DynamoDB_useCallerCredentials (82.27s)
        --- PASS: TestAccAppSync_serial/DataSource/Type_lambda (41.80s)
        --- PASS: TestAccAppSync_serial/DataSource/basic (25.94s)
        --- PASS: TestAccAppSync_serial/DataSource/description (33.02s)
    --- PASS: TestAccAppSync_serial/GraphQLAPI (678.57s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/name (28.76s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/AdditionalAuthentication_openIDConnect (14.91s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/UserPool_defaultAction (34.11s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/AuthenticationType_apiKey (14.92s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/AuthenticationType_openIDConnect (16.46s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/Log_excludeVerboseContent (64.91s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/AdditionalAuthentication_cognitoUserPools (18.75s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/basic (14.65s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/disappears (13.25s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/AuthenticationType_amazonCognitoUserPools (22.29s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/AdditionalAuthentication_apiKey (21.97s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/OpenIDConnect_issuer (29.87s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/UserPool_awsRegion (32.46s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/AdditionalAuthentication_awsIAM (18.46s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/OpenIDConnect_authTTL (34.68s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/AdditionalAuthentication_multiple (39.03s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/xrayEnabled (28.16s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/authenticationType (30.57s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/tags (32.40s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/log (25.42s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/Log_fieldLogLevel (46.74s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/schema (31.25s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/AuthenticationType_awsIAM (13.92s)
        --- PASS: TestAccAppSync_serial/GraphQLAPI/OpenIDConnect_clientID (25.70s)
        - [...]

2021-12-10 23:10 UTC, merged

2021-12-16 16:06 UTC, ouadie-lahdioui commented
Any ETA?