:alien: add support for aws_autoscaling_group filters
hashicorp/terraform-provider-aws pull request #21966
Opened 2021-11-30 17:09 UTC by danquack

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #3534

Output from acceptance testing:

```
~ make testacc TESTARGS="-run=TestAccAutoScalingGroupsDataSource_basic" PKG_NAME="./internal/service/autoscaling" ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ././internal/service/autoscaling/... -v -count 1 -parallel 3 -run=TestAccAutoScalingGroupsDataSource_basic -timeout 180m
=== RUN   TestAccAutoScalingGroupsDataSource_basic
=== PAUSE TestAccAutoScalingGroupsDataSource_basic
=== CONT  TestAccAutoScalingGroupsDataSource_basic
--- PASS: TestAccAutoScalingGroupsDataSource_basic (75.92s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/autoscaling        79.298s
```

2021-11-30 17:18 UTC, danquack commented on internal/service/autoscaling/groups_data_source_test.go
> -				Config: testAccCheckGroupsWithDataSourceConfig(sdkacctest.RandInt(), sdkacctest.RandInt(), sdkacctest.RandInt()),
The resources were not being created with this function, but rather using the `testAccCheckGroupsConfig` above resources. Therefore, I removed some of this cruft.

2021-11-30 17:53 UTC, drewmullen requested changes
great work! thanks for your contribution. 1 🎨  stylistic change requested

2021-11-30 17:53 UTC, drewmullen commented on internal/service/autoscaling/filters.go
> +func buildFiltersDataSource(set *schema.Set) []*autoscaling.Filter {
🎨  unless the functions are being reused, we prefer to keep them as close to the relevant files as possible. these can be moved directly into the data_source file

2021-11-30 18:35 UTC, drewmullen approved these changes
lgtm! 🚀

2021-12-01 13:57 UTC, ewbankkit approved these changes
LGTM :rocket:.

```console
% make testacc TESTARGS="-run=TestAccAutoScalingGroupsDataSource_basic" PKG_NAME="./internal/service/autoscaling"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ././internal/service/autoscaling/... -v -count 1 -parallel 20 -run=TestAccAutoScalingGroupsDataSource_basic -timeout 180m
=== RUN   TestAccAutoScalingGroupsDataSource_basic
=== PAUSE TestAccAutoScalingGroupsDataSource_basic
=== CONT  TestAccAutoScalingGroupsDataSource_basic
--- PASS: TestAccAutoScalingGroupsDataSource_basic (47.78s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/autoscaling	51.526s
```

2021-12-01 13:59 UTC, ewbankkit commented
@danquack Thanks for the contribution.
In general the changes look great. I went ahead and simplified the acceptance testing configuration(s) even more, consolidating into a single generating function (the fact that the data sources weren't referencing or depending on any of the autoscaling group resources may lead to intermittent tests failures).

2021-12-01 15:22 UTC, merged