Add support for AWS Direct Connect Sitelink #22187
hashicorp/terraform-provider-aws pull request #22350
Opened 2021-12-26 14:49 UTC by NetDevAutomate

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTS=TestAccXXX PKG=ec2

...
```

2021-12-27 13:13 UTC, drewmullen requested changes
great work! looking forward to seeing the tests

Can you also please update the docs which are located in `website/docs/{r,d}/`

When youre ready can you also please create a [change log file](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/pullrequest-submission-and-lifecycle.md#pull-request-types-to-changelog): `.changelog/22350.txt`

2021-12-27 13:49 UTC, NetDevAutomate commented
> great work! looking forward to seeing the tests
> 
> Can you also please update the docs which are located in `website/docs/{r,d}/`
> 
> When youre ready can you also please create a [change log file](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/pullrequest-submission-and-lifecycle.md#pull-request-types-to-changelog): `.changelog/22350.txt`

Website docs (r) modified and changelog file created. Many thanks

2022-01-03 12:35 UTC, ewbankkit commented on internal/service/directconnect/vif.go
> +	if d.HasChanges("mtu") {
If you are making separate calls to [`UpdateVirtualInterfaceAttributes`](https://docs.aws.amazon.com/directconnect/latest/APIReference/API_UpdateVirtualInterfaceAttributes.html) then please keep `d.HasChange()`.

2022-01-03 12:36 UTC, ewbankkit commented
@drewmullen Would you be able to verify acceptance tests for this?

2022-01-03 12:56 UTC, NetDevAutomate commented
> @ ewbankkit  Many thanks, I have corrected this.

Many thanks for spotting this, much appreciated.

2022-01-03 12:56 UTC, drewmullen commented
> @drewmullen Would you be able to verify acceptance tests for this?

There is a unique quota requirement for the service and I believe Andy is still waiting for the update to his account before he can run the tests.  We'll make sure to add the quota update to the CI accounts as well.

2022-01-03 13:07 UTC, NetDevAutomate commented
> 

I hope to get my account permissions sorted by Thursday 6th Jan and can then run the final tests. Manual testing has not shown any issues, so all being well, I'll update with positive results this week.

2022-01-03 13:10 UTC, ewbankkit commented
@NetDevAutomate Thanks. Apart from the `terrafmt` linter error, LGTM.

2022-01-03 13:16 UTC, ewbankkit commented
Will also need a [CHANGELOG entry](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/pullrequest-submission-and-lifecycle.md#changelog-process).

2022-01-03 13:30 UTC, NetDevAutomate commented
> Will also need a [CHANGELOG entry](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/pullrequest-submission-and-lifecycle.md#changelog-process).

Many thanks again, changelog entry created and formatting issue corrected.

2022-01-05 17:36 UTC, NetDevAutomate commented
$ make testacc TESTARGS='-run=TestAccTransitVirtualInterfaceSiteLink_basic' ACCTEST_PARALLELISM=5 PKG=directconnect
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/directconnect/... -v -count 1 -parallel 5 -run=TestAccTransitVirtualInterfaceSiteLink_basic -timeout 180m
=== RUN   TestAccTransitVirtualInterfaceSiteLink_basic
--- PASS: TestAccTransitVirtualInterfaceSiteLink_basic (964.55s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/directconnect	969.526s

$ make testacc TESTARGS='-run=TestAccDirectConnectPrivateVirtualInterfaceSiteLink_basic' ACCTEST_PARALLELISM=5 PKG=directconnect
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/directconnect/... -v -count 1 -parallel 5 -run=TestAccDirectConnectPrivateVirtualInterfaceSiteLink_basic -timeout 180m
=== RUN   TestAccDirectConnectPrivateVirtualInterfaceSiteLink_basic
=== PAUSE TestAccDirectConnectPrivateVirtualInterfaceSiteLink_basic
=== CONT  TestAccDirectConnectPrivateVirtualInterfaceSiteLink_basic
--- PASS: TestAccDirectConnectPrivateVirtualInterfaceSiteLink_basic (947.63s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/directconnect	952.053s

2022-01-05 20:28 UTC, NetDevAutomate commented
$ make testacc TESTARGS='-run=TestAccDirectConnectTransitVirtualInterface_serial' ACCTEST_PARALLELISM=5 PKG=directconnect
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/directconnect/... -v -count 1 -parallel 5 -run=TestAccDirectConnectTransitVirtualInterface_serial -timeout 180m
=== RUN   TestAccDirectConnectTransitVirtualInterface_serial
=== RUN   TestAccDirectConnectTransitVirtualInterface_serial/basic
=== RUN   TestAccDirectConnectTransitVirtualInterface_serial/tags
=== RUN   TestAccDirectConnectTransitVirtualInterface_serial/sitelink
--- PASS: TestAccDirectConnectTransitVirtualInterface_serial (2713.20s)
    --- PASS: TestAccDirectConnectTransitVirtualInterface_serial/basic (1049.07s)
    --- PASS: TestAccDirectConnectTransitVirtualInterface_serial/tags (671.71s)
    --- PASS: TestAccDirectConnectTransitVirtualInterface_serial/sitelink (992.43s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/directconnect	2716.781s

2022-01-05 21:47 UTC, ewbankkit commented
@NetDevAutomate @drewmullen Once this goes green are you OK for me to merge? Thanks.

2022-01-05 21:49 UTC, NetDevAutomate commented
> @NetDevAutomate @drewmullen Once this goes green are you OK for me to merge? Thanks.

That would be great, many thanks.

2022-01-05 22:35 UTC, merged