Update Firehose documentation with dynamic_partitioning_configuration
hashicorp/terraform-provider-aws pull request #22779
Opened 2022-01-26 21:10 UTC by a-mroz

Looks like documentation for `dynamic_partitioning_configuration` in the Firehose resource was missed in #20769.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #20769

2022-01-27 18:48 UTC, justinretzolk requested changes
Looking at the [AWS Go SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/firehose/#DynamicPartitioningConfiguration) and the [resource definition](https://github.com/hashicorp/terraform-provider-aws/blob/6f623165b909564e959a9b9fce1491be988f7b76/internal/service/firehose/delivery_stream.go#L61-L82), this looks good to me! I had one suggestion (just removing a bit of extra whitespace) but after that, we should be good to get this merged in. Thank you for your contribution! 🚀

2022-01-27 18:48 UTC, justinretzolk commented on website/docs/r/kinesis_firehose_delivery_stream.html.markdown
> +
Removing extra whitespace

```suggestion
```

2022-01-28 17:07 UTC, justinretzolk approved these changes
Looks good to me! Thank you again for your contribution! I'll get this merged in as soon as the checks finish up. 🚀

2022-02-20 11:37 UTC, a-mroz commented
@justinretzolk a reminder. I'm afraid this one was forgotten

2022-02-22 22:07 UTC, justinretzolk commented
Hey @a-mroz 👋 Apologies, you're totally correct; I'm not sure how this fell off of my radar, but I appreciate you following up! I'll get this merged now.

2022-02-22 22:07 UTC, merged