d/glue_catalog_table
hashicorp/terraform-provider-aws pull request #23256
Opened 2022-02-17 22:26 UTC by chris922

This is my first contribution, hope I did everything as expected. If not please let me know :) 

I added a data source for a glue catalog table and more or less copied and adapted many things from the regular resource. I was unsure if it is desired to have one generic "read" function and use this one in the resource and data source, but for simplicity, I now started with separate functions as for other resources it looks similar.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccGlueDataCatalogDataSource*' ACCTEST_PARALLELISM=5 PKG=glue
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/glue/... -v -count 1 -parallel 5  -run=TestAccGlueDataCatalogDataSource* -timeout 180m
=== RUN   TestAccGlueDataCatalogDataSource_basic
=== PAUSE TestAccGlueDataCatalogDataSource_basic
=== CONT  TestAccGlueDataCatalogDataSource_basic
--- PASS: TestAccGlueDataCatalogDataSource_basic (29.75s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/glue       29.790s
...
```

2022-08-01 20:45 UTC, bschaatsbergen commented
Hi @chris922, thanks for raising this pull request. I've noted it down to review this in the coming days.

2022-08-13 13:02 UTC, bschaatsbergen requested changes
Thanks for your contribution @chris922 , overall it looks good to m. I've used the data source and ran the tests on your fork - which seemed 👍 . 

```
bruno@bruno ~/g/f/chris992-terraform-provider-aws (feature/glue-data-catalog-table-datasource)> make testacc TESTARGS='-run=TestAccGlueDataCatalogDataSource*' ACCTEST_PARALLELISM=5 PKG=glue
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/glue/... -v -count 1 -parallel 5  -run=TestAccGlueDataCatalogDataSource* -timeout 180m
=== RUN   TestAccGlueDataCatalogDataSource_basic
=== PAUSE TestAccGlueDataCatalogDataSource_basic
=== CONT  TestAccGlueDataCatalogDataSource_basic
--- PASS: TestAccGlueDataCatalogDataSource_basic (26.60s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/glue       28.114s
```

If you could address the few comments we can get this 🚢  shipped!

2022-08-13 13:02 UTC, bschaatsbergen commented on website/docs/d/glue_catalog_table.html.markdown
> +* `ser_de_info` - Configuration block for serialization and deserialization ("SerDe") information. See [`ser_de_info`](#ser_de_info) below.
Lets create some consistency between the paragraph references, I noticed diferent ways being used.

>  See [`ser_de_info`](#ser_de_info) below
> See [Schema Reference](#schema-reference) below

2022-10-03 17:57 UTC, chris922 commented
Thanks @bschaatsbergen for the review! Please have a look at my changes and resolve the threads if they match your expectation.

2022-10-03 18:03 UTC, chris922 commented
Hmm, I squashed and rebased it... but the pipeline still fails, any ideas?

2022-10-03 18:57 UTC, bschaatsbergen commented
I'll take a look at this tomorrow.

2022-12-06 18:21 UTC, chris922 commented
@bschaatsbergen : I rebased my changes onto the main and it looks better for now

2022-12-06 21:16 UTC, bschaatsbergen commented
@ewbankkit would you mind checking this PR out :) ?

2022-12-08 14:04 UTC, ewbankkit approved these changes
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccGlueCatalogTableDataSource_' PKG=glue ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/glue/... -v -count 1 -parallel 2  -run=TestAccGlueCatalogTableDataSource_ -timeout 180m
=== RUN   TestAccGlueCatalogTableDataSource_basic
=== PAUSE TestAccGlueCatalogTableDataSource_basic
=== CONT  TestAccGlueCatalogTableDataSource_basic
--- PASS: TestAccGlueCatalogTableDataSource_basic (17.94s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/glue	23.130s
```

2022-12-08 15:10 UTC, merged

2022-12-09 15:59 UTC, chris922 commented
Great, thanks a lot!