Improve formmating for ses_identity_notification_topic doc
hashicorp/terraform-provider-aws pull request #23832
Opened 2022-03-23 17:59 UTC by multani

This pull request improves slightly the rendering of [the `aws_ses_identity_notification_topic` resource's documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ses_identity_notification_topic).

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

2022-03-24 18:51 UTC, justinretzolk requested changes
Thank you for your contribution! This looks good to me overall. Suggested changes are to move from double backticks to single backticks to match [markdown syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code). I think double backticks technically _does_ work, but single backticks falls in line with what Is done elsewhere in the documentation.

2022-03-24 18:51 UTC, justinretzolk commented on website/docs/r/ses_identity_notification_topic.markdown
> +* `topic_arn` - (Optional) The Amazon Resource Name (ARN) of the Amazon SNS topic. Can be set to ``""`` (an empty string) to disable publishing.
```suggestion
* `topic_arn` - (Optional) The Amazon Resource Name (ARN) of the Amazon SNS topic. Can be set to `""` (an empty string) to disable publishing.
```

2022-03-24 18:51 UTC, justinretzolk commented on website/docs/r/ses_identity_notification_topic.markdown
> +* `notification_type` - (Required) The type of notifications that will be published to the specified Amazon SNS topic. Valid Values: ``Bounce``, ``Complaint`` or ``Delivery``.
```suggestion
* `notification_type` - (Required) The type of notifications that will be published to the specified Amazon SNS topic. Valid Values: `Bounce`, `Complaint` or `Delivery`.
```

2022-03-24 18:51 UTC, justinretzolk commented on website/docs/r/ses_identity_notification_topic.markdown
> +* `include_original_headers` - (Optional) Whether SES should include original email headers in SNS notifications of this type. ``false`` by default.
```suggestion
* `include_original_headers` - (Optional) Whether SES should include original email headers in SNS notifications of this type. `false` by default.
```

2022-03-25 08:17 UTC, multani commented
> Suggested changes are to move from double backticks to single backticks to match [markdown syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code). I think double backticks technically _does_ work, but single backticks falls in line with what Is done elsewhere in the documentation.

:facepalm: you are totally right, this is fixed now :+1: (I spent too much time with [reStructuredText](https://docutils.sourceforge.io/docs/user/rst/quickref.html#inline-markup) in the past I think...)

2022-03-25 17:15 UTC, justinretzolk approved these changes
Looks good to me now! Thank you again for the contribution! Once the checks finish up, I'll get this merged in 🚀

2022-03-25 19:16 UTC, merged