r/aws_cloudwatchevidently_project
hashicorp/terraform-provider-aws pull request #24263
Opened 2022-04-15 13:32 UTC by GlennChia

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #22624

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccProject' PKG=cloudwatchevidently
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/cloudwatchevidently/... -v -count 1 -parallel 20  -run=TestAccProject -timeout 180m
=== RUN   TestAccProject_basic
=== PAUSE TestAccProject_basic
=== RUN   TestAccProject_updateTags
=== PAUSE TestAccProject_updateTags
=== RUN   TestAccProject_updateDataDelivery
=== PAUSE TestAccProject_updateDataDelivery
=== RUN   TestAccProject_disappears
=== PAUSE TestAccProject_disappears
=== CONT  TestAccProject_basic
=== CONT  TestAccProject_updateDataDelivery
=== CONT  TestAccProject_updateTags
=== CONT  TestAccProject_disappears
--- PASS: TestAccProject_disappears (17.73s)
--- PASS: TestAccProject_updateDataDelivery (25.60s)
--- PASS: TestAccProject_basic (36.35s)
--- PASS: TestAccProject_updateTags (51.93s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloudwatchevidently        51.976s

...
```

2022-06-18 18:56 UTC, DrFaust92 requested changes

2022-06-18 18:56 UTC, DrFaust92 commented on internal/service/cloudwatchevidently/project_test.go
> +		resp, err := conn.GetProject(input)
extract to finder and use it instead in all places where GetProject is used

2022-06-18 18:56 UTC, DrFaust92 commented on internal/service/cloudwatchevidently/project_test.go
> +					resource.TestCheckResourceAttrSet(resourceName, "arn"),
use acctest.CheckResourceAttrRegionalARN

2022-06-18 18:56 UTC, DrFaust92 commented on internal/service/cloudwatchevidently/project_test.go
> +func TestAccProject_updateTags(t *testing.T) {
follow https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/contribution-checklists.md#resource-tagging-acceptance-testing-implementation conevntion

2022-06-18 18:58 UTC, DrFaust92 commented
See linting errors, package and resource name should be `evidently` without the cloudwatch prefix

2022-06-19 12:08 UTC, GlennChia commented
Thanks @DrFaust92 for the review, refactored the functions, naming, and tests accordingly. Acceptance test results:

```
$ make testacc TESTARGS='-run=TestAccEvidentlyProject' PKG=evidently
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/evidently/... -v -count 1 -parallel 20  -run=TestAccEvidentlyProject -timeout 180m
=== RUN   TestAccEvidentlyProject_basic
=== PAUSE TestAccEvidentlyProject_basic
=== RUN   TestAccEvidentlyProject_tags
=== PAUSE TestAccEvidentlyProject_tags
=== RUN   TestAccEvidentlyProject_updateDataDelivery
=== PAUSE TestAccEvidentlyProject_updateDataDelivery
=== RUN   TestAccEvidentlyProject_disappears
=== PAUSE TestAccEvidentlyProject_disappears
=== CONT  TestAccEvidentlyProject_basic
=== CONT  TestAccEvidentlyProject_updateDataDelivery
=== CONT  TestAccEvidentlyProject_tags
=== CONT  TestAccEvidentlyProject_disappears
--- PASS: TestAccEvidentlyProject_disappears (17.41s)
--- PASS: TestAccEvidentlyProject_updateDataDelivery (27.17s)
--- PASS: TestAccEvidentlyProject_basic (37.38s)
--- PASS: TestAccEvidentlyProject_tags (54.36s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/evidently  54.422s
```

2022-06-25 09:27 UTC, DrFaust92 approved these changes
LGTM

2022-08-25 10:54 UTC, GlennChia commented
Most recent test results after changes

```bash
$ make testacc TESTARGS='-run=TestAccEvidentlyProject' PKG=evidently
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/evidently/... -v -count 1 -parallel 20  -run=TestAccEvidentlyProject -timeout 180m
=== RUN   TestAccEvidentlyProject_basic
=== PAUSE TestAccEvidentlyProject_basic
=== RUN   TestAccEvidentlyProject_tags
=== PAUSE TestAccEvidentlyProject_tags
=== RUN   TestAccEvidentlyProject_updateDataDeliveryCloudWatchLogGroup
=== PAUSE TestAccEvidentlyProject_updateDataDeliveryCloudWatchLogGroup
=== RUN   TestAccEvidentlyProject_updateDataDeliveryS3Bucket
=== PAUSE TestAccEvidentlyProject_updateDataDeliveryS3Bucket
=== RUN   TestAccEvidentlyProject_updateDataDeliveryS3Prefix
=== PAUSE TestAccEvidentlyProject_updateDataDeliveryS3Prefix
=== RUN   TestAccEvidentlyProject_updateDataDeliveryCloudWatchToS3
=== PAUSE TestAccEvidentlyProject_updateDataDeliveryCloudWatchToS3
=== RUN   TestAccEvidentlyProject_disappears
=== PAUSE TestAccEvidentlyProject_disappears
=== CONT  TestAccEvidentlyProject_basic
=== CONT  TestAccEvidentlyProject_updateDataDeliveryS3Prefix
=== CONT  TestAccEvidentlyProject_disappears
=== CONT  TestAccEvidentlyProject_tags
=== CONT  TestAccEvidentlyProject_updateDataDeliveryCloudWatchLogGroup
=== CONT  TestAccEvidentlyProject_updateDataDeliveryS3Bucket
=== CONT  TestAccEvidentlyProject_updateDataDeliveryCloudWatchToS3
--- PASS: TestAccEvidentlyProject_disappears (18.96s)
--- PASS: TestAccEvidentlyProject_basic (40.58s)
--- PASS: TestAccEvidentlyProject_updateDataDeliveryCloudWatchLogGroup (49.93s)
--- PASS: TestAccEvidentlyProject_updateDataDeliveryCloudWatchToS3 (53.82s)
--- PASS: TestAccEvidentlyProject_updateDataDeliveryS3Prefix (55.10s)
--- PASS: TestAccEvidentlyProject_updateDataDeliveryS3Bucket (55.52s)
--- PASS: TestAccEvidentlyProject_tags (59.43s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/evidently  59.499s
```

2022-10-05 19:15 UTC, ewbankkit approved these changes
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccEvidentlyProject_' PKG=evidently ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/evidently/... -v -count 1 -parallel 2  -run=TestAccEvidentlyProject_ -timeout 180m
=== RUN   TestAccEvidentlyProject_basic
=== PAUSE TestAccEvidentlyProject_basic
=== RUN   TestAccEvidentlyProject_tags
=== PAUSE TestAccEvidentlyProject_tags
=== RUN   TestAccEvidentlyProject_updateDataDeliveryCloudWatchLogGroup
=== PAUSE TestAccEvidentlyProject_updateDataDeliveryCloudWatchLogGroup
=== RUN   TestAccEvidentlyProject_updateDataDeliveryS3Bucket
=== PAUSE TestAccEvidentlyProject_updateDataDeliveryS3Bucket
=== RUN   TestAccEvidentlyProject_updateDataDeliveryS3Prefix
=== PAUSE TestAccEvidentlyProject_updateDataDeliveryS3Prefix
=== RUN   TestAccEvidentlyProject_updateDataDeliveryCloudWatchToS3
=== PAUSE TestAccEvidentlyProject_updateDataDeliveryCloudWatchToS3
=== RUN   TestAccEvidentlyProject_disappears
=== PAUSE TestAccEvidentlyProject_disappears
=== CONT  TestAccEvidentlyProject_basic
=== CONT  TestAccEvidentlyProject_updateDataDeliveryS3Prefix
--- PASS: TestAccEvidentlyProject_basic (40.47s)
=== CONT  TestAccEvidentlyProject_updateDataDeliveryCloudWatchLogGroup
--- PASS: TestAccEvidentlyProject_updateDataDeliveryS3Prefix (52.68s)
=== CONT  TestAccEvidentlyProject_updateDataDeliveryS3Bucket
--- PASS: TestAccEvidentlyProject_updateDataDeliveryCloudWatchLogGroup (47.96s)
=== CONT  TestAccEvidentlyProject_tags
--- PASS: TestAccEvidentlyProject_updateDataDeliveryS3Bucket (51.97s)
=== CONT  TestAccEvidentlyProject_disappears
--- PASS: TestAccEvidentlyProject_disappears (16.88s)
=== CONT  TestAccEvidentlyProject_updateDataDeliveryCloudWatchToS3
--- PASS: TestAccEvidentlyProject_tags (58.53s)
--- PASS: TestAccEvidentlyProject_updateDataDeliveryCloudWatchToS3 (48.69s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/evidently	176.417s
```

2022-10-05 19:15 UTC, ewbankkit commented
@GlennChia Thanks for the contribution :tada: :clap:.

2022-10-05 19:36 UTC, merged