doc and test of security_group for change name use-case
hashicorp/terraform-provider-aws pull request #24381
Opened 2022-04-24 16:25 UTC by bigmikes

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

### Changes
1. Added a new Acceptance Test to make sure that user can change `name` or `name-prefix` arguments to Security Group resource when they specify `create_before_destroy = true` property.
2. Extended Security Group documentation to provide this use-case as example. 

Closes #23708

Output from acceptance testing:

```
$ make testacc TESTS=TestAccEC2SecurityGroup_name_change PKG=ec2 ACCTEST_PARALLELISM=2  | tee test_output.txt
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 2 -run='TestAccEC2SecurityGroup_name_change'  -timeout 180m
=== RUN   TestAccEC2SecurityGroup_name_change
=== PAUSE TestAccEC2SecurityGroup_name_change
=== CONT  TestAccEC2SecurityGroup_name_change
--- PASS: TestAccEC2SecurityGroup_name_change (281.59s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	283.749s
```

2022-04-27 14:29 UTC, AdamTylerLynch requested changes
Small formatting changes requested. Thank you for providing clear documentation on how to get around this issue!

2022-04-27 14:29 UTC, AdamTylerLynch commented on website/docs/r/security_group.html.markdown
> +So, it is required to invert the default behavior of Terraform. That is, first the new Security Group resource must be created, then associated to possible Network Interface resources and finally the
Please remove the word "So,".

2022-04-27 14:29 UTC, AdamTylerLynch commented on website/docs/r/security_group.html.markdown
> +The `name` and `name-prefix` arguments force the creation of a new Security Group resource when they change value. In that case, Terraform first deletes the existing Security Group resource and then
If you can link to AWS public documentation to cite this, that would be a welcomed addition (but not required).

2022-04-27 14:29 UTC, AdamTylerLynch commented on website/docs/r/security_group.html.markdown
> +	  # Necessary if changing 'name' or 'name_prefix' properties.
Tab again, please change to spaces.

2022-05-02 13:54 UTC, closed without merging

2022-05-02 22:26 UTC, bigmikes commented
New PR: https://github.com/hashicorp/terraform-provider-aws/pull/24508