d/aws_route53_resolver_rules: add new name_regex filter argument
hashicorp/terraform-provider-aws pull request #24582
Opened 2022-05-05 15:03 UTC by Tailzip

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Add new `name_regex` filter argument for `aws_route53_resolver_rules` datasource. Given this isn't supported natively by [AWS API](https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_Filter.html), filtering is performed locally after retrieving results from the API.

Output from acceptance testing:

```
❯ make testacc TESTS=TestAccRoute53ResolverRulesDataSource PKG=route53resolver
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/route53resolver/... -v -count 1 -parallel 20 -run='TestAccRoute53ResolverRulesDataSource'  -timeout 180m
=== RUN   TestAccRoute53ResolverRulesDataSource_basic
=== PAUSE TestAccRoute53ResolverRulesDataSource_basic
=== RUN   TestAccRoute53ResolverRulesDataSource_resolverEndpointID
=== PAUSE TestAccRoute53ResolverRulesDataSource_resolverEndpointID
=== RUN   TestAccRoute53ResolverRulesDataSource_nameRegex
=== PAUSE TestAccRoute53ResolverRulesDataSource_nameRegex
=== RUN   TestAccRoute53ResolverRulesDataSource_nonExistentNameRegex
=== PAUSE TestAccRoute53ResolverRulesDataSource_nonExistentNameRegex
=== CONT  TestAccRoute53ResolverRulesDataSource_basic
=== CONT  TestAccRoute53ResolverRulesDataSource_nameRegex
=== CONT  TestAccRoute53ResolverRulesDataSource_resolverEndpointID
=== CONT  TestAccRoute53ResolverRulesDataSource_nonExistentNameRegex
--- PASS: TestAccRoute53ResolverRulesDataSource_basic (6.72s)
--- PASS: TestAccRoute53ResolverRulesDataSource_nonExistentNameRegex (7.97s)
--- PASS: TestAccRoute53ResolverRulesDataSource_nameRegex (29.14s)
--- PASS: TestAccRoute53ResolverRulesDataSource_resolverEndpointID (205.15s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/route53resolver    206.737s

...
```

2022-05-06 10:07 UTC, Tailzip commented
Acceptance tests output after force-push:
```sh
❯ make testacc TESTS=TestAccRoute53ResolverRulesDataSource PKG=route53resolver
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/route53resolver/... -v -count 1 -parallel 20 -run='TestAccRoute53ResolverRulesDataSource'  -timeout 180m
=== RUN   TestAccRoute53ResolverRulesDataSource_basic
=== PAUSE TestAccRoute53ResolverRulesDataSource_basic
=== RUN   TestAccRoute53ResolverRulesDataSource_resolverEndpointID
=== PAUSE TestAccRoute53ResolverRulesDataSource_resolverEndpointID
=== RUN   TestAccRoute53ResolverRulesDataSource_nameRegex
=== PAUSE TestAccRoute53ResolverRulesDataSource_nameRegex
=== RUN   TestAccRoute53ResolverRulesDataSource_nonExistentNameRegex
=== PAUSE TestAccRoute53ResolverRulesDataSource_nonExistentNameRegex
=== CONT  TestAccRoute53ResolverRulesDataSource_basic
=== CONT  TestAccRoute53ResolverRulesDataSource_nameRegex
=== CONT  TestAccRoute53ResolverRulesDataSource_nonExistentNameRegex
=== CONT  TestAccRoute53ResolverRulesDataSource_resolverEndpointID
--- PASS: TestAccRoute53ResolverRulesDataSource_basic (7.74s)
--- PASS: TestAccRoute53ResolverRulesDataSource_nonExistentNameRegex (8.23s)
--- PASS: TestAccRoute53ResolverRulesDataSource_nameRegex (29.64s)
--- PASS: TestAccRoute53ResolverRulesDataSource_resolverEndpointID (205.48s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/route53resolver    207.060s
```

2022-05-06 15:25 UTC, drewmullen commented
I believe you'd want to implement this feature as it behaves more natively with the api, by adding a `filters` block argument. Here is an example of the implementation, should be fairly straight-forward to adapt: https://github.com/hashicorp/terraform-provider-aws/blob/ca81d173a8590e75b1c05eaf6df8105464ac67da/internal/service/ec2/ipam_pool_data_source.go#L20

2022-05-06 15:27 UTC, drewmullen requested changes
I believe you'd want to implement this feature as it behaves more natively with the api, by adding a `filters` block argument instead of individual arguments for each filter type. Here is an example of the implementation on another data source: https://github.com/hashicorp/terraform-provider-aws/blob/ca81d173a8590e75b1c05eaf6df8105464ac67da/internal/service/ec2/ipam_pool_data_source.go#L20

2022-05-07 10:38 UTC, Tailzip commented
> I believe you'd want to implement this feature as it behaves more natively with the api, by adding a `filters` block argument instead of individual arguments for each filter type. Here is an example of the implementation on another data source.

Hi @drewmullen, which API are you referring to: provider's or Route53Resolver service's ? Name regex filtering isn't supported by Route53Resolver API.

2022-05-07 12:42 UTC, drewmullen commented
> > I believe you'd want to implement this feature as it behaves more natively with the api, by adding a `filters` block argument instead of individual arguments for each filter type. Here is an example of the implementation on another data source.
> 
> Hi @drewmullen, which API are you referring to: provider's or Route53Resolver service's ? Name regex filtering isn't supported by Route53Resolver API.

Oh jeesh. Ha - sorry about that! Let me take a closer look next week

2022-05-10 20:49 UTC, gdavison requested changes
Thanks for the PR, @Tailzip. It looks good, though I have a few suggestions for changes.

2022-05-10 20:49 UTC, gdavison commented on website/docs/d/route53_resolver_rules.html.markdown
> +### Retrieving forward rule(s) shared with me
For stylistic reasons, we prefer `rules`

```suggestion
### Retrieving forward rules shared with me
```

2022-05-10 20:49 UTC, gdavison commented on website/docs/d/route53_resolver_rules.html.markdown
> +### Retrieving the default resolver rule
Thanks for adding the headings

2022-05-10 20:49 UTC, gdavison commented on website/docs/d/route53_resolver_rules.html.markdown
> +### Retrieving rule(s) by name regex
```suggestion
### Retrieving rules by name regex
```

2022-05-10 20:49 UTC, gdavison commented on website/docs/d/route53_resolver_rules.html.markdown
> +  options to narrow down the list AWS returns.
Some suggested changes to the argument description

```suggestion
* `name_regex` - (Optional) A regex string to filter resolver rule names.
  The filtering is done locally, so could have a performance impact if the result is large.
  This argument should be used along with other arguments to limit the number of results returned.
```

2022-05-11 19:00 UTC, Tailzip commented
Thanks for the review @gdavison, I've implemented the requested changes 😄 

New acceptance tests output:
```sh
❯ make testacc TESTS=TestAccRoute53ResolverRulesDataSource PKG=route53resolver
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/route53resolver/... -v -count 1 -parallel 20 -run='TestAccRoute53ResolverRulesDataSource'  -timeout 180m
=== RUN   TestAccRoute53ResolverRulesDataSource_basic
=== PAUSE TestAccRoute53ResolverRulesDataSource_basic
=== RUN   TestAccRoute53ResolverRulesDataSource_resolverEndpointID
=== PAUSE TestAccRoute53ResolverRulesDataSource_resolverEndpointID
=== RUN   TestAccRoute53ResolverRulesDataSource_nameRegex
=== PAUSE TestAccRoute53ResolverRulesDataSource_nameRegex
=== RUN   TestAccRoute53ResolverRulesDataSource_nonExistentNameRegex
=== PAUSE TestAccRoute53ResolverRulesDataSource_nonExistentNameRegex
=== CONT  TestAccRoute53ResolverRulesDataSource_basic
=== CONT  TestAccRoute53ResolverRulesDataSource_nameRegex
=== CONT  TestAccRoute53ResolverRulesDataSource_resolverEndpointID
=== CONT  TestAccRoute53ResolverRulesDataSource_nonExistentNameRegex
--- PASS: TestAccRoute53ResolverRulesDataSource_nonExistentNameRegex (8.42s)
--- PASS: TestAccRoute53ResolverRulesDataSource_basic (8.44s)
--- PASS: TestAccRoute53ResolverRulesDataSource_nameRegex (30.37s)
--- PASS: TestAccRoute53ResolverRulesDataSource_resolverEndpointID (216.33s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/route53resolver    217.901s
```

2022-05-18 22:30 UTC, merged