F aws route53 resolver firewall domain list
hashicorp/terraform-provider-aws pull request #25509
Opened 2022-06-21 13:24 UTC by silvaalbert

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
* 
Closes #25492

Output from acceptance testing:

```
$ make testacc TESTS='TestAccRoute53ResolverFirewallDomainListDataSource_basic' PKG=route53resolver TESTARGS=-short
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/route53resolver/... -v -count 1 -parallel 20 -run='TestAccRoute53ResolverFirewallDomainListDataSource_basic' -short -timeout 180m
=== RUN   TestAccRoute53ResolverFirewallDomainListDataSource_basic
--- PASS: TestAccRoute53ResolverFirewallDomainListDataSource_basic (97.34s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/route53resolver	100.808s

...
```

2022-06-21 19:37 UTC, AdamTylerLynch requested changes
A few changes requested.

I would like to get @ewbankkit's opinion:

The ResourceFirewallDomainList exposes a list of domains, I feel that should be exposed in the following ways in the data source.

1. Domains attribute for the selected FirewallDomainList
2. Ability to filter FirewallDomainList(s) by associated Domain (www.example.com).

Thoughts?

2022-06-21 19:37 UTC, AdamTylerLynch commented on internal/service/route53resolver/firewall_domain_list_data_source.go
> +func DataSourceResolverFirewallDomainList() *schema.Resource {
"Resolver" is inferred from the package name. Also, the datasource name should match the corresponding Resource. In this case ResourceFirewallDomainList.

```suggestion
func DataSourceFirewallDomainList() *schema.Resource {
```

2022-06-21 19:37 UTC, AdamTylerLynch commented on internal/service/route53resolver/firewall_domain_list_data_source.go
> +	d.SetId(aws.StringValue(output.FirewallDomainList.Id))
There are multiple attributes here that are not present in `ResourceFirewallDomainList`. I would recommend an additional PR to add these attributes to `ResourceFirewallDomainList`.

2022-06-21 19:37 UTC, AdamTylerLynch commented on internal/service/route53resolver/firewall_domain_list_data_source.go
> +		return fmt.Errorf("no  Route53 Firewall Domain List found matching criteria; try different search")
Please remove double spacing.

2022-06-21 19:37 UTC, AdamTylerLynch commented on internal/service/route53resolver/firewall_domain_list_data_source.go
> +func dataSourceResolverFirewallDomainListRead(d *schema.ResourceData, meta interface{}) error {
Rename to match datasource and associated resource:

```suggestion
func dataSourceFirewallDomainListRead(d *schema.ResourceData, meta interface{}) error {
```

2022-11-09 19:15 UTC, ewbankkit approved these changes
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccRoute53ResolverFirewallDomainListDataSource_' PKG=route53resolver ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/route53resolver/... -v -count 1 -parallel 2  -run=TestAccRoute53ResolverFirewallDomainListDataSource_ -timeout 180m
=== RUN   TestAccRoute53ResolverFirewallDomainListDataSource_basic
--- PASS: TestAccRoute53ResolverFirewallDomainListDataSource_basic (90.40s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/route53resolver	96.375s
```

2022-11-09 19:15 UTC, ewbankkit commented
@silvaalbert Thanks for the contribution :tada: :clap:.

2022-11-09 19:15 UTC, merged