service/iam: iam_principal_policy_simulation data source
hashicorp/terraform-provider-aws pull request #25569
Opened 2022-06-25 01:12 UTC by apparentlymart

This data source wraps the IAM policy simulation API. This was previously a data source with little utility in Terraform, but with the introduction of preconditions and postconditions in Terraform v1.2.3 it can be potentially useful as a way for a configuration to either pre-verify that it seems to be running with credentials that confer sufficient access or to self-check a policy it declares itself to get earlier warning if the policy seems insufficient for its intended purpose.

Unfortunately the IAM policy simulator is pretty low-level and requires the caller to figure out all of the relevant details of how a real AWS service would make requests to IAM at runtime in order to construct a fully-realistic simulation, but thankfully in practice it seems like authors could make do with relatively-simple "naive" simulations unless they know they are using more complex IAM policy features, such as custom conditions or interpolations. I included some hopefully-realistic examples in the documentation.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Output from acceptance testing:

```
=== RUN   TestAccDataSourcePrincipalPolicySimulation
=== PAUSE TestAccDataSourcePrincipalPolicySimulation
=== CONT  TestAccDataSourcePrincipalPolicySimulation
--- PASS: TestAccDataSourcePrincipalPolicySimulation (21.45s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/iam        23.029s
```

2022-06-25 09:22 UTC, DrFaust92 requested changes

2022-06-25 09:22 UTC, DrFaust92 commented on internal/service/iam/principal_policy_simulation_data_source.go
> +			"caller_arn": {
add validation for arn?

2022-06-25 09:22 UTC, DrFaust92 commented on internal/service/iam/principal_policy_simulation_data_source.go
> +			"permissions_boundary_policies_json": {
add validation for valid json?

2022-06-25 09:22 UTC, DrFaust92 commented on internal/service/iam/principal_policy_simulation_data_source.go
> +			"additional_policies_json": {
add validation for valid json

2022-06-25 09:22 UTC, DrFaust92 commented on internal/service/iam/principal_policy_simulation_data_source.go
> +			"policy_source_arn": {
add validation for valid arn

2022-06-25 09:22 UTC, DrFaust92 commented on internal/service/iam/principal_policy_simulation_data_source.go
> +			"resource_arns": {
add validations for arn

2022-06-25 09:22 UTC, DrFaust92 commented on internal/service/iam/principal_policy_simulation_data_source.go
> +			"resource_owner_account_id": {
add validation for valid account id

2022-06-25 09:22 UTC, DrFaust92 commented on internal/service/iam/principal_policy_simulation_data_source.go
> +			"resource_policy_json": {
json validation

2023-06-05 19:23 UTC, ewbankkit approved these changes
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccIAMPrincipalPolicySimulationDataSource' PKG=iam
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/iam/... -v -count 1 -parallel 20  -run=TestAccIAMPrincipalPolicySimulationDataSource -timeout 180m
=== RUN   TestAccIAMPrincipalPolicySimulationDataSource_basic
=== PAUSE TestAccIAMPrincipalPolicySimulationDataSource_basic
=== CONT  TestAccIAMPrincipalPolicySimulationDataSource_basic
--- PASS: TestAccIAMPrincipalPolicySimulationDataSource_basic (27.03s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/iam	32.824s
```

2023-06-05 20:22 UTC, ewbankkit commented
@apparentlymart Thanks for the contribution :tada: :clap:.

2023-06-05 20:22 UTC, merged