Update data.aws_ecs_task_definition arn attribute
hashicorp/terraform-provider-aws pull request #25763
Opened 2022-07-11 05:04 UTC by ndench

The `aws_ecs_task_definition` data source exposes the `id` attribute (not the `arn` attribute) which is actually the `ARN` of the Task Definition.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTS=TestAccXXX PKG=ec2

...
```

2022-07-21 18:13 UTC, justinretzolk requested changes
It looks like both `id` and `arn` are exported and are both the ARN of the task definition, based on the [data source code](https://github.com/hashicorp/terraform-provider-aws/blob/135dcc40af9835b7ed7dcd3eaf408d84174813ab/internal/service/ecs/task_definition_data_source.go#L70-L71).

In other places (for example, the [`aws_ecs_cluster` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_cluster#attributes-reference)), both `id` and `arn` are documented, so I think it makes sense to do the same here.

2022-07-21 18:13 UTC, justinretzolk commented on website/docs/d/ecs_task_definition.html.markdown
> +* `id` - The ARN of the task definition
```suggestion
* `id` - The ARN of the task definition
* `arn` - The ARN of the task definition
```

2022-07-24 22:45 UTC, ndench commented
Ah, good pickup @justinretzolk. I still have v3.68 so the `arn` property didn't work for me (it was added in v3.71 from the looks of it). Regardless, I've updated with your suggestion.

2022-07-25 20:54 UTC, justinretzolk approved these changes
Looks good to me! Thank you for adding the suggested changes! I'll get this merged once the checks finish up 🚀

2022-07-25 20:54 UTC, merged