Changing Lambda Integration Type to AWS_MOCK
hashicorp/terraform-provider-aws pull request #25848
Opened 2022-07-17 00:23 UTC by fishcharlie

2022-07-17 00:23 UTC, fishcharlie reviewed
Changing the integration type to AWS_MOCK.

2022-07-28 18:19 UTC, justinretzolk requested changes
Thank you for taking the time to raise this PR! I had one note that I'd like us to take a look at before we get this merged in.

2022-07-28 18:19 UTC, justinretzolk commented on website/docs/r/apigatewayv2_integration.html.markdown
> +  integration_type = "AWS_MOCK"
Unless I'm misunderstanding, based on the [document you linked in the PR](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-api-integration-types.html), it seems that this should instead be `AWS_PROXY`. It doesn't appear that `AWS_MOCK` is a valid integration type, and `MOCK` appears to be used only for testing. If I've misunderstood, I'd be happy to take another look! 🙂 

```suggestion
  integration_type = "AWS_PROXY"
```

2022-07-28 21:26 UTC, fishcharlie commented
@justinretzolk You are correct. My bad. Just committed that change.

2022-08-09 17:30 UTC, justinretzolk approved these changes
Looks good to me! Thank you for your contribution!

2022-08-09 19:53 UTC, merged