r/aws_connect_phone_number
hashicorp/terraform-provider-aws pull request #26364
Opened 2022-08-18 02:59 UTC by GlennChia

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #26015

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccConnect_serial/PhoneNumber' PKG=connect
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/connect/... -v -count 1 -parallel 20  -run=TestAccConnect_serial/PhoneNumber -timeout 180m
=== RUN   TestAccConnect_serial
=== RUN   TestAccConnect_serial/PhoneNumber
=== RUN   TestAccConnect_serial/PhoneNumber/prefix
=== RUN   TestAccConnect_serial/PhoneNumber/targetARN
=== RUN   TestAccConnect_serial/PhoneNumber/basic
=== RUN   TestAccConnect_serial/PhoneNumber/disappears
=== RUN   TestAccConnect_serial/PhoneNumber/tags
=== RUN   TestAccConnect_serial/PhoneNumber/description
--- PASS: TestAccConnect_serial (616.97s)
    --- PASS: TestAccConnect_serial/PhoneNumber (616.97s)
        --- PASS: TestAccConnect_serial/PhoneNumber/prefix (97.80s)
        --- PASS: TestAccConnect_serial/PhoneNumber/targetARN (116.53s)
        --- PASS: TestAccConnect_serial/PhoneNumber/basic (94.70s)
        --- PASS: TestAccConnect_serial/PhoneNumber/disappears (90.76s)
        --- PASS: TestAccConnect_serial/PhoneNumber/tags (122.56s)
        --- PASS: TestAccConnect_serial/PhoneNumber/description (94.62s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/connect    617.031s

...
```

2022-10-21 22:00 UTC, schuylr requested changes
Thanks for the PR! I think this is a great first pass, but there are some levels of control that are being restricted from the Terraform operator.

I believe the core thing to allow would be the option to provide a full `phone_number` per the [ClaimPhoneNumber](https://docs.aws.amazon.com/connect/latest/APIReference/API_ClaimPhoneNumber.html) API.

More than happy to contribute to this with access provided to your branch.

2022-10-21 22:00 UTC, schuylr commented on internal/service/connect/phone_number.go
> +		ClientToken:   aws.String(uuid),
```suggestion
		ClientToken:   resource.UniqueId(),
```

2022-10-21 22:00 UTC, schuylr commented on internal/service/connect/phone_number.go
> +			ClientToken:   aws.String(uuid),
```suggestion
			ClientToken:   resource.UniqueId(),
```

2022-10-21 22:00 UTC, schuylr commented on internal/service/connect/phone_number.go
> +		ClientToken: aws.String(uuid), // can't use aws.String(resource.UniqueId()), because not a valid uuid
I don't believe there's a required UUID format for ClientToken: https://docs.aws.amazon.com/connect/latest/APIReference/API_ClaimPhoneNumber.html#API_ClaimPhoneNumber_RequestSyntax 

As long as it's less than 500 characters.

2022-10-21 22:21 UTC, schuylr commented on internal/service/connect/phone_number.go
> +	uuid, err := uuid.GenerateUUID()
Suggest this be turned into a common function for the service

2022-10-21 22:44 UTC, schuylr approved these changes
Discussed offline with @GlennChia about proceeding with this functionality for now. Will create another fast-follow issue to allow support for direct `phone_number` supplying.

Will also need to create two data sources which also depend on this PR. Will link issues as pending from this PR as well!

Thanks for the awesome discussion!

2022-10-21 22:45 UTC, schuylr commented on internal/service/connect/phone_number.go
> +	uuid, err := uuid.GenerateUUID()
Agreed offline that the `err` needs to be handled within the function as a return out.

2022-10-22 00:12 UTC, schuylr approved these changes
Quick linter fix suggestion

2022-10-22 00:12 UTC, schuylr commented on internal/service/connect/phone_number.go
> +
```suggestion
```

2022-11-03 15:06 UTC, ewbankkit commented
@GlennChia Thanks for the contribution :tada: :clap:.

2022-11-03 15:06 UTC, merged