Add support for target failover, flow stickiness for GWLB target group
hashicorp/terraform-provider-aws pull request #27334
Opened 2022-10-19 19:08 UTC by ddericco

### Description

Add support for `target_failover` and `stickiness` attributes for GENEVE protocol target groups for Gateway Load Balancer (GWLB)

### Relations

Closes #27153 

### References

https://docs.aws.amazon.com/elasticloadbalancing/latest/gateway/target-groups.html#target-group-attributes

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccELBV2TargetGroup_Geneve_Sticky PKG=elbv2                         
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/elbv2/... -v -count 1 -parallel 20 -run='TestAccELBV2TargetGroup_Geneve_Sticky'  -timeout 180m
=== RUN   TestAccELBV2TargetGroup_Geneve_Sticky
=== PAUSE TestAccELBV2TargetGroup_Geneve_Sticky
=== CONT  TestAccELBV2TargetGroup_Geneve_Sticky
--- PASS: TestAccELBV2TargetGroup_Geneve_Sticky (23.75s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elbv2      26.841s

$ make testacc TESTS=TestAccELBV2TargetGroup_Geneve_targetFailover PKG=elbv2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/elbv2/... -v -count 1 -parallel 20 -run='TestAccELBV2TargetGroup_Geneve_targetFailover'  -timeout 180m
=== RUN   TestAccELBV2TargetGroup_Geneve_targetFailover
=== PAUSE TestAccELBV2TargetGroup_Geneve_targetFailover
=== CONT  TestAccELBV2TargetGroup_Geneve_targetFailover
--- PASS: TestAccELBV2TargetGroup_Geneve_targetFailover (29.90s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elbv2      32.684s
...
```

2022-10-20 22:21 UTC, schuylr approved these changes
LGTM

2022-10-22 00:39 UTC, gdavison requested changes
Thanks for the PR, @ddericco. I have a few suggestions for changes

2022-10-22 00:39 UTC, gdavison commented on internal/service/elbv2/target_group_test.go
> +			{
In order to confirm that this configuration can be imported and also to validate that the configuration matches what is live in AWS, we should add an import check here, e.g.

```suggestion
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
			{
```

2022-10-22 00:39 UTC, gdavison commented on internal/service/elbv2/target_group_test.go
> +		},
Add an import check here as well

```suggestion
		},
		{
			ResourceName:      resourceName,
			ImportState:       true,
			ImportStateVerify: true,
		},
```

2022-10-22 00:39 UTC, gdavison commented on internal/service/elbv2/target_group.go
> +							Optional: true,
Since these parameters must both be present if `target_failover` is defined, they should be marked as `Required`

2022-10-22 00:39 UTC, gdavison commented on website/docs/r/lb_target_group.html.markdown
> +* `target_failover` - (Optional) Target failover block. Detailed below. Only applicable for Gateway Load Balancer target groups.
It's helpful for readers of the documentation to have a link to the block documentation below. We also prefer that "See below" sections come as the last sentence

```suggestion
* `target_failover` - (Optional) Target failover block. Only applicable for Gateway Load Balancer target groups. See [target_failover](#target_failover) for more information. 
```

2022-11-02 20:11 UTC, ewbankkit approved these changes
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccELBV2TargetGroup_' PKG=elbv2 ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/elbv2/... -v -count 1 -parallel 2  -run=TestAccELBV2TargetGroup_ -timeout 180m
=== RUN   TestAccELBV2TargetGroup_backwardsCompatibility
=== PAUSE TestAccELBV2TargetGroup_backwardsCompatibility
=== RUN   TestAccELBV2TargetGroup_ProtocolVersion_basic
=== PAUSE TestAccELBV2TargetGroup_ProtocolVersion_basic
=== RUN   TestAccELBV2TargetGroup_ProtocolVersion_grpcHealthCheck
=== PAUSE TestAccELBV2TargetGroup_ProtocolVersion_grpcHealthCheck
=== RUN   TestAccELBV2TargetGroup_ProtocolVersion_grpcUpdate
=== PAUSE TestAccELBV2TargetGroup_ProtocolVersion_grpcUpdate
=== RUN   TestAccELBV2TargetGroup_HealthCheck_tcp
=== PAUSE TestAccELBV2TargetGroup_HealthCheck_tcp
=== RUN   TestAccELBV2TargetGroup_ipAddressType
=== PAUSE TestAccELBV2TargetGroup_ipAddressType
=== RUN   TestAccELBV2TargetGroup_tls
=== PAUSE TestAccELBV2TargetGroup_tls
=== RUN   TestAccELBV2TargetGroup_HealthCheck_tcpHTTPS
=== PAUSE TestAccELBV2TargetGroup_HealthCheck_tcpHTTPS
=== RUN   TestAccELBV2TargetGroup_attrsOnCreate
=== PAUSE TestAccELBV2TargetGroup_attrsOnCreate
=== RUN   TestAccELBV2TargetGroup_basic
=== PAUSE TestAccELBV2TargetGroup_basic
=== RUN   TestAccELBV2TargetGroup_udp
=== PAUSE TestAccELBV2TargetGroup_udp
=== RUN   TestAccELBV2TargetGroup_ForceNew_name
=== PAUSE TestAccELBV2TargetGroup_ForceNew_name
=== RUN   TestAccELBV2TargetGroup_ForceNew_port
=== PAUSE TestAccELBV2TargetGroup_ForceNew_port
=== RUN   TestAccELBV2TargetGroup_ForceNew_protocol
=== PAUSE TestAccELBV2TargetGroup_ForceNew_protocol
=== RUN   TestAccELBV2TargetGroup_ForceNew_vpc
=== PAUSE TestAccELBV2TargetGroup_ForceNew_vpc
=== RUN   TestAccELBV2TargetGroup_Defaults_application
=== PAUSE TestAccELBV2TargetGroup_Defaults_application
=== RUN   TestAccELBV2TargetGroup_Defaults_network
=== PAUSE TestAccELBV2TargetGroup_Defaults_network
=== RUN   TestAccELBV2TargetGroup_HealthCheck_enable
=== PAUSE TestAccELBV2TargetGroup_HealthCheck_enable
=== RUN   TestAccELBV2TargetGroup_Name_generated
=== PAUSE TestAccELBV2TargetGroup_Name_generated
=== RUN   TestAccELBV2TargetGroup_Name_prefix
=== PAUSE TestAccELBV2TargetGroup_Name_prefix
=== RUN   TestAccELBV2TargetGroup_NetworkLB_targetGroup
=== PAUSE TestAccELBV2TargetGroup_NetworkLB_targetGroup
=== RUN   TestAccELBV2TargetGroup_networkLB_TargetGroupWithConnectionTermination
=== PAUSE TestAccELBV2TargetGroup_networkLB_TargetGroupWithConnectionTermination
=== RUN   TestAccELBV2TargetGroup_NetworkLB_targetGroupWithProxy
=== PAUSE TestAccELBV2TargetGroup_NetworkLB_targetGroupWithProxy
=== RUN   TestAccELBV2TargetGroup_preserveClientIPValid
=== PAUSE TestAccELBV2TargetGroup_preserveClientIPValid
=== RUN   TestAccELBV2TargetGroup_Geneve_basic
=== PAUSE TestAccELBV2TargetGroup_Geneve_basic
=== RUN   TestAccELBV2TargetGroup_Geneve_notSticky
=== PAUSE TestAccELBV2TargetGroup_Geneve_notSticky
=== RUN   TestAccELBV2TargetGroup_Geneve_Sticky
=== PAUSE TestAccELBV2TargetGroup_Geneve_Sticky
=== RUN   TestAccELBV2TargetGroup_Geneve_targetFailover
=== PAUSE TestAccELBV2TargetGroup_Geneve_targetFailover
=== RUN   TestAccELBV2TargetGroup_Stickiness_defaultALB
=== PAUSE TestAccELBV2TargetGroup_Stickiness_defaultALB
=== RUN   TestAccELBV2TargetGroup_Stickiness_defaultNLB
=== PAUSE TestAccELBV2TargetGroup_Stickiness_defaultNLB
=== RUN   TestAccELBV2TargetGroup_Stickiness_invalidALB
=== PAUSE TestAccELBV2TargetGroup_Stickiness_invalidALB
=== RUN   TestAccELBV2TargetGroup_Stickiness_invalidNLB
=== PAUSE TestAccELBV2TargetGroup_Stickiness_invalidNLB
=== RUN   TestAccELBV2TargetGroup_Stickiness_validALB
=== PAUSE TestAccELBV2TargetGroup_Stickiness_validALB
=== RUN   TestAccELBV2TargetGroup_Stickiness_validNLB
=== PAUSE TestAccELBV2TargetGroup_Stickiness_validNLB
=== RUN   TestAccELBV2TargetGroup_tags
=== PAUSE TestAccELBV2TargetGroup_tags
=== RUN   TestAccELBV2TargetGroup_Stickiness_updateAppEnabled
=== PAUSE TestAccELBV2TargetGroup_Stickiness_updateAppEnabled
=== RUN   TestAccELBV2TargetGroup_HealthCheck_update
=== PAUSE TestAccELBV2TargetGroup_HealthCheck_update
=== RUN   TestAccELBV2TargetGroup_Stickiness_updateEnabled
=== PAUSE TestAccELBV2TargetGroup_Stickiness_updateEnabled
=== RUN   TestAccELBV2TargetGroup_HealthCheck_without
=== PAUSE TestAccELBV2TargetGroup_HealthCheck_without
=== RUN   TestAccELBV2TargetGroup_ALBAlias_basic
=== PAUSE TestAccELBV2TargetGroup_ALBAlias_basic
=== RUN   TestAccELBV2TargetGroup_ALBAlias_changeNameForceNew
=== PAUSE TestAccELBV2TargetGroup_ALBAlias_changeNameForceNew
=== RUN   TestAccELBV2TargetGroup_ALBAlias_changePortForceNew
=== PAUSE TestAccELBV2TargetGroup_ALBAlias_changePortForceNew
=== RUN   TestAccELBV2TargetGroup_ALBAlias_changeProtocolForceNew
=== PAUSE TestAccELBV2TargetGroup_ALBAlias_changeProtocolForceNew
=== RUN   TestAccELBV2TargetGroup_ALBAlias_changeVPCForceNew
=== PAUSE TestAccELBV2TargetGroup_ALBAlias_changeVPCForceNew
=== RUN   TestAccELBV2TargetGroup_ALBAlias_generatedName
=== PAUSE TestAccELBV2TargetGroup_ALBAlias_generatedName
=== RUN   TestAccELBV2TargetGroup_ALBAlias_lambda
=== PAUSE TestAccELBV2TargetGroup_ALBAlias_lambda
=== RUN   TestAccELBV2TargetGroup_ALBAlias_lambdaMultiValueHeadersEnabled
=== PAUSE TestAccELBV2TargetGroup_ALBAlias_lambdaMultiValueHeadersEnabled
=== RUN   TestAccELBV2TargetGroup_ALBAlias_missingPortProtocolVPC
=== PAUSE TestAccELBV2TargetGroup_ALBAlias_missingPortProtocolVPC
=== RUN   TestAccELBV2TargetGroup_ALBAlias_namePrefix
=== PAUSE TestAccELBV2TargetGroup_ALBAlias_namePrefix
=== RUN   TestAccELBV2TargetGroup_ALBAlias_setAndUpdateSlowStart
=== PAUSE TestAccELBV2TargetGroup_ALBAlias_setAndUpdateSlowStart
=== RUN   TestAccELBV2TargetGroup_ALBAlias_tags
=== PAUSE TestAccELBV2TargetGroup_ALBAlias_tags
=== RUN   TestAccELBV2TargetGroup_ALBAlias_updateHealthCheck
=== PAUSE TestAccELBV2TargetGroup_ALBAlias_updateHealthCheck
=== RUN   TestAccELBV2TargetGroup_ALBAlias_updateLoadBalancingAlgorithmType
=== PAUSE TestAccELBV2TargetGroup_ALBAlias_updateLoadBalancingAlgorithmType
=== RUN   TestAccELBV2TargetGroup_ALBAlias_updateStickinessEnabled
=== PAUSE TestAccELBV2TargetGroup_ALBAlias_updateStickinessEnabled
=== CONT  TestAccELBV2TargetGroup_backwardsCompatibility
=== CONT  TestAccELBV2TargetGroup_Stickiness_invalidALB
--- PASS: TestAccELBV2TargetGroup_backwardsCompatibility (20.55s)
=== CONT  TestAccELBV2TargetGroup_Defaults_application
--- PASS: TestAccELBV2TargetGroup_Defaults_application (19.96s)
=== CONT  TestAccELBV2TargetGroup_Stickiness_defaultNLB
--- PASS: TestAccELBV2TargetGroup_Stickiness_invalidALB (40.78s)
=== CONT  TestAccELBV2TargetGroup_Stickiness_defaultALB
--- PASS: TestAccELBV2TargetGroup_Stickiness_defaultALB (20.06s)
=== CONT  TestAccELBV2TargetGroup_Geneve_targetFailover
--- PASS: TestAccELBV2TargetGroup_Stickiness_defaultNLB (51.80s)
=== CONT  TestAccELBV2TargetGroup_Geneve_Sticky
--- PASS: TestAccELBV2TargetGroup_Geneve_targetFailover (40.65s)
=== CONT  TestAccELBV2TargetGroup_Geneve_notSticky
--- PASS: TestAccELBV2TargetGroup_Geneve_Sticky (35.70s)
=== CONT  TestAccELBV2TargetGroup_Geneve_basic
--- PASS: TestAccELBV2TargetGroup_Geneve_notSticky (35.62s)
=== CONT  TestAccELBV2TargetGroup_preserveClientIPValid
--- PASS: TestAccELBV2TargetGroup_Geneve_basic (23.69s)
=== CONT  TestAccELBV2TargetGroup_NetworkLB_targetGroupWithProxy
--- PASS: TestAccELBV2TargetGroup_preserveClientIPValid (34.74s)
=== CONT  TestAccELBV2TargetGroup_networkLB_TargetGroupWithConnectionTermination
--- PASS: TestAccELBV2TargetGroup_NetworkLB_targetGroupWithProxy (33.99s)
=== CONT  TestAccELBV2TargetGroup_NetworkLB_targetGroup
--- PASS: TestAccELBV2TargetGroup_networkLB_TargetGroupWithConnectionTermination (33.89s)
=== CONT  TestAccELBV2TargetGroup_Name_prefix
--- PASS: TestAccELBV2TargetGroup_Name_prefix (18.50s)
=== CONT  TestAccELBV2TargetGroup_Name_generated
--- PASS: TestAccELBV2TargetGroup_NetworkLB_targetGroup (53.80s [...]

2022-11-02 20:11 UTC, ewbankkit commented
@ddericco Thanks for the contribution :tada: :clap:.

2022-11-02 21:27 UTC, merged