Add data source for DX Router Configuration
hashicorp/terraform-provider-aws pull request #27341
Opened 2022-10-19 22:01 UTC by schuylr

### Description

Adds the `aws_dx_router_configuration` data source to allow users to download sample router configurations for their Direct Connect VIF.

### Relations

Closes #26432

### References

https://docs.aws.amazon.com/directconnect/latest/UserGuide/create-vif.html#vif-router-config 
https://docs.aws.amazon.com/sdk-for-go/api/service/directconnect/#DirectConnect.DescribeRouterConfiguration
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/directconnect#Client.DescribeRouterConfiguration 
https://docs.aws.amazon.com/directconnect/latest/APIReference/API_DescribeRouterConfiguration.html 
https://docs.aws.amazon.com/directconnect/latest/APIReference/API_RouterType.html

### Output from Acceptance Testing

Note that a DX VIF must be provided via the `VIRTUAL_INTERFACE_ID` env variable.

```
terraform-provider-aws % AWS_DEFAULT_REGION=eu-west-1 VIRTUAL_INTERFACE_ID=dxvif-xxxxxxxx make testacc TESTS=TestAccDirectConnectRouterConfigurationDataSource_basic PKG=directconnect
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/directconnect/... -v -count 1 -parallel 20 -run='TestAccDirectConnectRouterConfigurationDataSource_basic'  -timeout 180m
=== RUN   TestAccDirectConnectRouterConfigurationDataSource_basic
=== PAUSE TestAccDirectConnectRouterConfigurationDataSource_basic
=== CONT  TestAccDirectConnectRouterConfigurationDataSource_basic
--- PASS: TestAccDirectConnectRouterConfigurationDataSource_basic (19.31s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/directconnect	23.515s
```

2022-10-20 22:38 UTC, GlennChia requested changes
PR looks good, requesting small styling changes, no functional changes required.

2022-10-20 22:38 UTC, GlennChia commented on internal/service/directconnect/router_configuration_data_source.go
> +		tfMap["platform"] = v
We can use an in-built function to return the value of the string value that is passed 

```suggestion
		tfMap["platform"] = aws.StringValue(v)

2022-10-20 22:38 UTC, GlennChia commented on internal/service/directconnect/router_configuration_data_source.go
> +		tfMap["router_type_identifier"] = v
We can use an in-built function to return the value of the string value that is passed

```suggestion
		tfMap["router_type_identifier"] = aws.StringValue(v)

2022-10-20 22:38 UTC, GlennChia commented on internal/service/directconnect/router_configuration_data_source.go
> +		tfMap["software"] = v
We can use an in-built function to return the value of the string value that is passed

```suggestion
		tfMap["software"] = aws.StringValue(v)

2022-10-20 22:38 UTC, GlennChia commented on internal/service/directconnect/router_configuration_data_source.go
> +		tfMap["vendor"] = v
We can use an in-built function to return the value of the string value that is passed

```suggestion
		tfMap["vendor"] = aws.StringValue(v)

2022-10-20 22:38 UTC, GlennChia commented on internal/service/directconnect/router_configuration_data_source.go
> +		tfMap["xslt_template_name"] = v
We can use an in-built function to return the value of the string value that is passed

```suggestion
		tfMap["xslt_template_name"] = aws.StringValue(v)

2022-10-20 22:38 UTC, GlennChia commented on internal/service/directconnect/router_configuration_data_source.go
> +		tfMap["xslt_template_name_for_mac_sec"] = v
We can use an in-built function to return the value of the string value that is passed

```suggestion
		tfMap["xslt_template_name_for_mac_sec"] = aws.StringValue(v)

2022-10-20 22:38 UTC, GlennChia commented on internal/service/directconnect/router_configuration_data_source_test.go
> +func testAccRouterConfigurationDataSourceConfig_basic(virtualInterfaceId string, routerTypeIdentifier string) string {
Small styling change.

```suggestion
func testAccRouterConfigurationDataSourceConfig_basic(virtualInterfaceId, routerTypeIdentifier string) string {

2022-10-20 22:38 UTC, GlennChia commented on website/docs/d/dx_router_configuration.html.markdown
> +}
styling change `terraform fmt`

```suggestion
data "aws_dx_router_configuration" "example" {
  virtual_interface_id   = "dxvif-abcde123"
  router_type_identifier = "CiscoSystemsInc-2900SeriesRouters-IOS124"
}

2022-10-20 22:42 UTC, GlennChia approved these changes
LGTM!

2022-10-25 15:44 UTC, ewbankkit approved these changes
LGTM :rocket:.

```console
% make testacc TESTS=TestAccDirectConnectRouterConfigurationDataSource_ PKG=directconnect
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/directconnect/... -v -count 1 -parallel 20 -run='TestAccDirectConnectRouterConfigurationDataSource_'  -timeout 180m
=== RUN   TestAccDirectConnectRouterConfigurationDataSource_basic
    router_configuration_data_source_test.go:17: Environment variable VIRTUAL_INTERFACE_ID is not set
--- SKIP: TestAccDirectConnectRouterConfigurationDataSource_basic (0.00s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/directconnect	4.891s
```

2022-10-25 15:44 UTC, ewbankkit commented
@schuylr Thanks for the contribution :tada: :clap:.

2022-10-25 16:21 UTC, merged