docs: add `tags` attribute to RDS Cluster data source (#27090)
hashicorp/terraform-provider-aws pull request #27589
Opened 2022-11-02 08:23 UTC by thomasgouveia

### Description

This PR add the `tags` attribute to the RDS Cluster datasource documentation, and fix the error described in #27090. The end user was redirected on the RDS Cluster resource, but the attribute for getting resource tags is different on the datasource than the resource. 

### Relations

Closes #27090

2022-11-25 20:44 UTC, thomasgouveia commented
Hi @breathingdust, I just rebased the PR. It seems it fixed the markdown-lint workflow issue.

2022-11-25 22:45 UTC, breathingdust requested changes
Hi @thomasgouveia! Thanks for the contribution, have one tiny correction for you and then LGTM!

2022-11-25 22:45 UTC, breathingdust commented on website/docs/d/rds_cluster.html.markdown
> +returned attributes - they are identical for all attributes, except the `tags_all`. If you need to get the tags for this resource, use the attribute `tag` described below.
```suggestion
returned attributes - they are identical for all attributes, except the `tags_all`. If you need to get the tags for this resource, use the attribute `tags` as described below.
```

2022-11-26 01:24 UTC, thomasgouveia commented on website/docs/d/rds_cluster.html.markdown
> +returned attributes - they are identical for all attributes, except the `tags_all`. If you need to get the tags for this resource, use the attribute `tag` described below.
It should be ok now !

2023-01-14 11:16 UTC, thomasgouveia commented
Hi @breathingdust , any news on this PR ? I've done the changes requested. Let me know if something is missing !

2023-02-07 18:52 UTC, breathingdust commented
LGTM @thomasgouveia 🚀 Thanks for the contribution!

2023-02-07 18:52 UTC, merged