F added desired capacity type flag in asg
hashicorp/terraform-provider-aws pull request #28658
Opened 2023-01-04 10:42 UTC by ajayOO8

### Description

### Relations

Closes #0000

### References

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccXXX PKG=ec2

...
```

2023-01-04 22:36 UTC, bschaatsbergen requested changes
Added 2 drive-by comments, could you please also create a test for this new attribute?

2023-01-04 22:36 UTC, bschaatsbergen commented on .changelog/28658.txt
> +resource/aws_asg: Add desired_capacity_type flag
`desired_capacity_type` attribute

2023-01-04 22:36 UTC, bschaatsbergen commented on internal/service/autoscaling/group.go
> +				Type:     schema.TypeString,
`Computed: true`
As you mentioned in the docs that there's a default value for it.

2023-01-04 22:40 UTC, bschaatsbergen commented on website/docs/r/autoscaling_group.html.markdown
> +* `desired_capacity_type` - (Optional) specify the desired capacity type
See the `markdown-lint` Github Action that reported a linting issue please.

2023-01-05 15:37 UTC, ewbankkit commented
@ajayOO8 Thanks for the contribution :tada: :clap:.
Everything was great.
In order to get this released today I went ahead and added some acceptance tests.

2023-01-05 16:03 UTC, merged