feat(28538): add manage master user password flag
hashicorp/terraform-provider-aws pull request #28848
Opened 2023-01-12 10:55 UTC by fergoid

### Description

This pull request adds the option for RDS to manage master user passwords.  The default behaviour continues to be to  manage passwords as the resource does today.

### Relations

Closes #28538 

### References

### Output from Acceptance Testing

```
$ make testacc PKG=rds TESTS=TestAccRDSInstance_basic                                                                                    <aws:default>
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSInstance_basic'  -timeout 180m
=== RUN   TestAccRDSInstance_basic
=== PAUSE TestAccRDSInstance_basic
=== CONT  TestAccRDSInstance_basic
--- PASS: TestAccRDSInstance_basic (471.51s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rds        500.343s

$ make testacc PKG=rds TESTS=TestAccRDSInstance_manage_password                                                                          <aws:default>
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSInstance_manage_password'  -timeout 180m
=== RUN   TestAccRDSInstance_manage_password
=== PAUSE TestAccRDSInstance_manage_password
=== CONT  TestAccRDSInstance_manage_password
--- PASS: TestAccRDSInstance_manage_password (529.08s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rds        556.548s

make testacc PKG=rds TESTS=TestAccRDSInstanceDataSource_basic                                                                          <aws:default>
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSInstanceDataSource_basic'  -timeout 180m
=== RUN   TestAccRDSInstanceDataSource_basic
=== PAUSE TestAccRDSInstanceDataSource_basic
=== CONT  TestAccRDSInstanceDataSource_basic
--- PASS: TestAccRDSInstanceDataSource_basic (499.71s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rds        527.915s

$ make testacc PKG=rds TESTS=TestAccRDSInstanceDataSource_manage_password                                                                <aws:default>
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSInstanceDataSource_manage_password'  -timeout 180m
=== RUN   TestAccRDSInstanceDataSource_manage_password
=== PAUSE TestAccRDSInstanceDataSource_manage_password
=== CONT  TestAccRDSInstanceDataSource_manage_password
--- PASS: TestAccRDSInstanceDataSource_manage_password (520.61s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rds        548.706s

...
```

2023-01-12 14:34 UTC, williamlord-wise commented on internal/service/rds/instance.go
> +			"master_user_secret_kms_keyid": {
```suggestion
			"master_user_secret_kms_key_id": {
```

2023-01-12 14:34 UTC, williamlord-wise commented on website/docs/r/db_instance.html.markdown
> +* `master_user_secret_kms_keyid` - (Optional) The ARN of a KMS key used to protect the secret that RDS creates. A default key will be used if not provided.
```suggestion
* `master_user_secret_kms_key_id` - (Optional) The ARN of a KMS key used to protect the secret that RDS creates. A default key will be used if not provided.     
```

2023-01-12 14:35 UTC, williamlord-wise commented on internal/service/rds/instance.go
> +		if v, ok := d.GetOk("master_user_secret_kms_keyid"); ok {
```suggestion
		if v, ok := d.GetOk("master_user_secret_kms_key_id"); ok {
```

2023-01-13 07:31 UTC, fergoid commented
What is the correct definition for this attribute?  It fails the S019 check , although it does work as intended which is to return the secret ARN that RDS creates to the consumer.
```
			"master_user_secret_arn": {
				Type:     schema.TypeString,
				Optional: false,
				Required: false,
				Computed: true,
			},
```

Can I flag it to be ignored (//lintignore:S019) or is there another way to achieve this ?

2023-01-13 07:52 UTC, fergoid commented on internal/service/rds/instance.go
> +			"master_user_secret_kms_keyid": {
Done.

2023-01-13 07:52 UTC, fergoid commented on website/docs/r/db_instance.html.markdown
> +* `master_user_secret_kms_keyid` - (Optional) The ARN of a KMS key used to protect the secret that RDS creates. A default key will be used if not provided.
Done.

2023-01-13 07:52 UTC, fergoid commented on internal/service/rds/instance.go
> +		if v, ok := d.GetOk("master_user_secret_kms_keyid"); ok {
Done.

2023-01-13 07:52 UTC, fergoid commented on internal/service/rds/instance.go
> +		if v, ok := d.GetOk("master_user_secret_kms_keyid"); ok {
Done.

2023-01-16 04:33 UTC, wedge-jarrad commented
Thanks for working on this! Very much looking forward to this functionality.

Unless I'm mistaken, similar changes are needed in `cluster.go`.

2023-01-16 10:21 UTC, fergoid commented
> Thanks for working on this! Very much looking forward to this functionality.
> 
> Unless I'm mistaken, similar changes are needed in `cluster.go`.

I will take look today , thanks.

2023-01-27 09:08 UTC, fergoid commented
I keep getting GH action errors on goreleaser in my forked repo.  Not sure what this mean
<img width="1069" alt="Screenshot 2023-01-27 at 09 07 05" src="https://user-images.githubusercontent.com/11411330/215049183-89d1881b-b317-4e06-81c6-9ce5bed6ee72.png">

2023-02-07 12:51 UTC, bryantbiggs commented
any update on getting this merged, anything left to do?

2023-03-06 12:52 UTC, bryantbiggs commented
@AdamTylerLynch / @ewbankkit would either of you have time to take a look at the PR?

2023-03-10 19:41 UTC, AdamTylerLynch requested changes
A few changes requested. I am going to make some code changes on this PR to expedite the merge.

2023-03-10 19:41 UTC, AdamTylerLynch commented on internal/service/rds/cluster.go
> +				Default:       false,
This attribute does not need to have a default value specified, as it is optional and will be omitted from the CreateDBCluster() call if not provided by the user. Did you experience a specific test case that was failing without this?

2023-03-10 19:41 UTC, AdamTylerLynch commented on internal/service/rds/cluster.go
> +			//lintignore:S019
The S019 analyzer reports cases of schemas including `Computed: false`,`Optional: false`, or `Required: false` which are extraneous. Removing `Optional: false` and `Required: false` would remove the need to ignore the linting rule.

Reference: [https://github.com/hashicorp/terraform-provider-aws/tree/main/.ci/providerlint/vendor/github.com/bflad/tfproviderlint/passes/S019](https://github.com/hashicorp/terraform-provider-aws/tree/main/.ci/providerlint/vendor/github.com/bflad/tfproviderlint/passes/S019)

2023-03-10 19:41 UTC, AdamTylerLynch commented on internal/service/rds/cluster.go
> +			"master_user_secret_arn": {
If we are going to expose the output SecretArn, we should also expose the computed value of SecretStatus.

Reference: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/rds/create-db-cluster.html#:~:text=for%20future%20use.-,MasterUserSecret,-%2D%3E%20(structure)

2023-03-10 19:41 UTC, AdamTylerLynch commented on internal/service/rds/cluster_data_source_test.go
> +func TestAccRDSClusterDataSource_manage_password(t *testing.T) {
We should add another AccTest that updates an existing Cluster from self managed master password to RDS managed to ensure a smooth upgrade path.

2023-03-10 19:41 UTC, AdamTylerLynch commented on internal/service/rds/cluster_data_source_test.go
> +func TestAccRDSClusterDataSource_manage_password(t *testing.T) {
We should add AccTests for Customer Managed keys as well.

2023-03-23 12:20 UTC, AdamTylerLynch commented
### AccTests for `aws_rds_cluster`

Pre-existing failures logged here:

### Output from acceptance testing
```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 10 -run='TestAccRDSCluster_'  -timeout 180m
=== RUN   TestAccRDSCluster_basic
=== PAUSE TestAccRDSCluster_basic
=== RUN   TestAccRDSCluster_disappears
=== PAUSE TestAccRDSCluster_disappears
=== RUN   TestAccRDSCluster_tags
=== PAUSE TestAccRDSCluster_tags
=== RUN   TestAccRDSCluster_identifierGenerated
=== PAUSE TestAccRDSCluster_identifierGenerated
=== RUN   TestAccRDSCluster_identifierPrefix
=== PAUSE TestAccRDSCluster_identifierPrefix
=== RUN   TestAccRDSCluster_allowMajorVersionUpgrade
=== PAUSE TestAccRDSCluster_allowMajorVersionUpgrade
=== RUN   TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParametersApplyImm
=== PAUSE TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParametersApplyImm
=== RUN   TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParameters
=== PAUSE TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParameters
=== RUN   TestAccRDSCluster_onlyMajorVersion
=== PAUSE TestAccRDSCluster_onlyMajorVersion
=== RUN   TestAccRDSCluster_availabilityZones
=== PAUSE TestAccRDSCluster_availabilityZones
=== RUN   TestAccRDSCluster_storageType
=== PAUSE TestAccRDSCluster_storageType
=== RUN   TestAccRDSCluster_allocatedStorage
=== PAUSE TestAccRDSCluster_allocatedStorage
=== RUN   TestAccRDSCluster_iops
=== PAUSE TestAccRDSCluster_iops
=== RUN   TestAccRDSCluster_dbClusterInstanceClass
=== PAUSE TestAccRDSCluster_dbClusterInstanceClass
=== RUN   TestAccRDSCluster_backtrackWindow
=== PAUSE TestAccRDSCluster_backtrackWindow
=== RUN   TestAccRDSCluster_dbSubnetGroupName
=== PAUSE TestAccRDSCluster_dbSubnetGroupName
=== RUN   TestAccRDSCluster_pointInTimeRestore
=== PAUSE TestAccRDSCluster_pointInTimeRestore
=== RUN   TestAccRDSCluster_PointInTimeRestore_enabledCloudWatchLogsExports
=== PAUSE TestAccRDSCluster_PointInTimeRestore_enabledCloudWatchLogsExports
=== RUN   TestAccRDSCluster_takeFinalSnapshot
=== PAUSE TestAccRDSCluster_takeFinalSnapshot
=== RUN   TestAccRDSCluster_missingUserNameCausesError
=== PAUSE TestAccRDSCluster_missingUserNameCausesError
=== RUN   TestAccRDSCluster_EnabledCloudWatchLogsExports_mySQL
=== PAUSE TestAccRDSCluster_EnabledCloudWatchLogsExports_mySQL
=== RUN   TestAccRDSCluster_EnabledCloudWatchLogsExports_postgresql
=== PAUSE TestAccRDSCluster_EnabledCloudWatchLogsExports_postgresql
=== RUN   TestAccRDSCluster_updateIAMRoles
=== PAUSE TestAccRDSCluster_updateIAMRoles
=== RUN   TestAccRDSCluster_kmsKey
=== PAUSE TestAccRDSCluster_kmsKey
=== RUN   TestAccRDSCluster_networkType
=== PAUSE TestAccRDSCluster_networkType
=== RUN   TestAccRDSCluster_encrypted
=== PAUSE TestAccRDSCluster_encrypted
=== RUN   TestAccRDSCluster_copyTagsToSnapshot
=== PAUSE TestAccRDSCluster_copyTagsToSnapshot
=== RUN   TestAccRDSCluster_ReplicationSourceIdentifier_kmsKeyID
=== PAUSE TestAccRDSCluster_ReplicationSourceIdentifier_kmsKeyID
=== RUN   TestAccRDSCluster_backupsUpdate
=== PAUSE TestAccRDSCluster_backupsUpdate
=== RUN   TestAccRDSCluster_iamAuth
=== PAUSE TestAccRDSCluster_iamAuth
=== RUN   TestAccRDSCluster_deletionProtection
=== PAUSE TestAccRDSCluster_deletionProtection
=== RUN   TestAccRDSCluster_engineMode
=== PAUSE TestAccRDSCluster_engineMode
=== RUN   TestAccRDSCluster_EngineMode_global
=== PAUSE TestAccRDSCluster_EngineMode_global
=== RUN   TestAccRDSCluster_EngineMode_multiMaster
=== PAUSE TestAccRDSCluster_EngineMode_multiMaster
=== RUN   TestAccRDSCluster_EngineMode_parallelQuery
=== PAUSE TestAccRDSCluster_EngineMode_parallelQuery
=== RUN   TestAccRDSCluster_engineVersion
=== PAUSE TestAccRDSCluster_engineVersion
=== RUN   TestAccRDSCluster_engineVersionWithPrimaryInstance
=== PAUSE TestAccRDSCluster_engineVersionWithPrimaryInstance
=== RUN   TestAccRDSCluster_GlobalClusterIdentifierEngineMode_global
=== PAUSE TestAccRDSCluster_GlobalClusterIdentifierEngineMode_global
=== RUN   TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_add
=== PAUSE TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_add
=== RUN   TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_remove
=== PAUSE TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_remove
=== RUN   TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_update
=== PAUSE TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_update
=== RUN   TestAccRDSCluster_GlobalClusterIdentifierEngineMode_provisioned
=== PAUSE TestAccRDSCluster_GlobalClusterIdentifierEngineMode_provisioned
=== RUN   TestAccRDSCluster_GlobalClusterIdentifier_primarySecondaryClusters
=== PAUSE TestAccRDSCluster_GlobalClusterIdentifier_primarySecondaryClusters
=== RUN   TestAccRDSCluster_GlobalClusterIdentifier_replicationSourceIdentifier
=== PAUSE TestAccRDSCluster_GlobalClusterIdentifier_replicationSourceIdentifier
=== RUN   TestAccRDSCluster_GlobalClusterIdentifier_secondaryClustersWriteForwarding
=== PAUSE TestAccRDSCluster_GlobalClusterIdentifier_secondaryClustersWriteForwarding
=== RUN   TestAccRDSCluster_ManagedMasterPassword_managed
=== PAUSE TestAccRDSCluster_ManagedMasterPassword_managed
=== RUN   TestAccRDSCluster_ManagedMasterPassword_managedSpecificKMSKey
=== PAUSE TestAccRDSCluster_ManagedMasterPassword_managedSpecificKMSKey
=== RUN   TestAccRDSCluster_ManagedMasterPassword_convertToManaged
=== PAUSE TestAccRDSCluster_ManagedMasterPassword_convertToManaged
=== RUN   TestAccRDSCluster_port
=== PAUSE TestAccRDSCluster_port
=== RUN   TestAccRDSCluster_scaling
=== PAUSE TestAccRDSCluster_scaling
=== RUN   TestAccRDSCluster_serverlessV2ScalingConfiguration
=== PAUSE TestAccRDSCluster_serverlessV2ScalingConfiguration
=== RUN   TestAccRDSCluster_Scaling_defaultMinCapacity
=== PAUSE TestAccRDSCluster_Scaling_defaultMinCapacity
=== RUN   TestAccRDSCluster_snapshotIdentifier
=== PAUSE TestAccRDSCluster_snapshotIdentifier
=== RUN   TestAccRDSCluster_SnapshotIdentifier_deletionProtection
=== PAUSE TestAccRDSCluster_SnapshotIdentifier_deletionProtection
=== RUN   TestAccRDSCluster_SnapshotIdentifierEngineMode_parallelQuery
=== PAUSE TestAccRDSCluster_SnapshotIdentifierEngineMode_parallelQuery
=== RUN   TestAccRDSCluster_SnapshotIdentifierEngineMode_provisioned
=== PAUSE TestAccRDSCluster_SnapshotIdentifierEngineMode_provisioned
=== RUN   TestAccRDSCluster_SnapshotIdentifierEngineMode_serverless
    cluster_test.go:1898: serverless does not support snapshot restore on an empty volume
--- SKIP: TestAccRDSCluster_SnapshotIdentifierEngineMode_serverless (0.00s)
=== RUN   TestAccRDSCluster_SnapshotIdentifierEngineVersion_different
=== PAUSE TestAccRDSCluster_SnapshotIdentifierEngineVersion_different
=== RUN   TestAccRDSCluster_SnapshotIdentifierEngineVersion_equal
=== PAUSE TestAccRDSCluster_SnapshotIdentifierEngineVersion_equal
=== RUN   TestAccRDSCluster_SnapshotIdentifier_kmsKeyID
=== PAUSE TestAccRDSCluster_SnapshotIdentifier_kmsKeyID
=== RUN   TestAccRDSCluster_SnapshotIdentifier_masterPassword
=== PAUSE TestAccRDSCluster_SnapshotIdentifier_masterPassword
=== RUN   TestAccRDSCluster_SnapshotIdentifier_masterUsername
=== PAUSE TestAccRDSCluster_SnapshotIdentifier_masterUsername
=== RUN   TestAccRDSCluster_SnapshotIdentifier_preferredBackupWindow
=== PAUSE TestAccRDSCluster_SnapshotIdentifier_preferredBackupWindow
=== RUN   TestAccRDSCluster_SnapshotIdentifier_preferredMaintenanceWindow
=== PAUSE TestAccRDSCluster_SnapshotIdentifier_preferredMaintenanceWindow
=== RUN   TestAccRDSCluster_SnapshotIdentifier_tags
=== PAUSE TestAccRDSCluster_SnapshotIdentifier_tags
=== RUN   TestAccRDSCluster_SnapshotIdentifier_vpcSecurityGroupIDs
=== PAUSE TestAccRDSCluster_SnapshotIdentifier_vpcSecurityGroupIDs
=== RUN   TestAccRDSCluster_SnapshotIdentifierVPCSecurityGroupIDs_tags
=== PAUSE TestAccRDSCluster_SnapshotIdentifierVPCSecurityGroupIDs_tags
=== RUN   TestAccRDSCluster_SnapshotIdentifier_encryptedRestore
=== PAUSE TestAccRDSCluster_SnapshotIdentifier_e [...]

2023-03-23 12:21 UTC, AdamTylerLynch commented
### AccTests for `rds_cluster_data_source`

```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 10 -run='TestAccRDSClusterDataSource_'  -timeout 180m
=== RUN   TestAccRDSClusterDataSource_basic
=== PAUSE TestAccRDSClusterDataSource_basic
=== RUN   TestAccRDSClusterDataSource_ManagedMasterPassword_managed
=== PAUSE TestAccRDSClusterDataSource_ManagedMasterPassword_managed
=== CONT  TestAccRDSClusterDataSource_basic
=== CONT  TestAccRDSClusterDataSource_ManagedMasterPassword_managed
--- PASS: TestAccRDSClusterDataSource_ManagedMasterPassword_managed (171.14s)
--- PASS: TestAccRDSClusterDataSource_basic (211.98s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	212.094s

```

2023-03-24 13:47 UTC, AdamTylerLynch commented
### AccTests for TestAccRDSInstance_Managed*

### Output from acceptance testing
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 10 -run='TestAccRDSInstance_Managed'  -timeout 180m
=== RUN   TestAccRDSInstance_ManagedMasterPassword_managed
=== PAUSE TestAccRDSInstance_ManagedMasterPassword_managed
=== RUN   TestAccRDSInstance_ManagedMasterPassword_managedSpecificKMSKey
=== PAUSE TestAccRDSInstance_ManagedMasterPassword_managedSpecificKMSKey
=== RUN   TestAccRDSInstance_ManagedMasterPassword_convertToManaged
=== PAUSE TestAccRDSInstance_ManagedMasterPassword_convertToManaged
=== CONT  TestAccRDSInstance_ManagedMasterPassword_managed
=== CONT  TestAccRDSInstance_ManagedMasterPassword_convertToManaged
=== CONT  TestAccRDSInstance_ManagedMasterPassword_managedSpecificKMSKey
--- PASS: TestAccRDSInstance_ManagedMasterPassword_managedSpecificKMSKey (527.76s)
--- PASS: TestAccRDSInstance_ManagedMasterPassword_managed (551.44s)
--- PASS: TestAccRDSInstance_ManagedMasterPassword_convertToManaged (684.42s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	684.529s

2023-03-24 13:54 UTC, AdamTylerLynch commented
### AccTests for `TestAccRDSInstance_`
note, tests do not fully run due to timeout issues on my side. Recommend running full tests.

### Output from acceptance tests
```
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 10 -run='TestAccRDSInstance_'  -timeout 180m
=== RUN   TestAccRDSInstance_basic
=== PAUSE TestAccRDSInstance_basic
=== RUN   TestAccRDSInstance_manage_password
=== PAUSE TestAccRDSInstance_manage_password
=== RUN   TestAccRDSInstance_identifierPrefix
=== PAUSE TestAccRDSInstance_identifierPrefix
=== RUN   TestAccRDSInstance_identifierGenerated
=== PAUSE TestAccRDSInstance_identifierGenerated
=== RUN   TestAccRDSInstance_disappears
=== PAUSE TestAccRDSInstance_disappears
=== RUN   TestAccRDSInstance_tags
=== PAUSE TestAccRDSInstance_tags
=== RUN   TestAccRDSInstance_nameDeprecated
=== PAUSE TestAccRDSInstance_nameDeprecated
=== RUN   TestAccRDSInstance_onlyMajorVersion
=== PAUSE TestAccRDSInstance_onlyMajorVersion
=== RUN   TestAccRDSInstance_kmsKey
=== PAUSE TestAccRDSInstance_kmsKey
=== RUN   TestAccRDSInstance_customIAMInstanceProfile
=== PAUSE TestAccRDSInstance_customIAMInstanceProfile
=== RUN   TestAccRDSInstance_subnetGroup
=== PAUSE TestAccRDSInstance_subnetGroup
=== RUN   TestAccRDSInstance_networkType
=== PAUSE TestAccRDSInstance_networkType
=== RUN   TestAccRDSInstance_optionGroup
=== PAUSE TestAccRDSInstance_optionGroup
=== RUN   TestAccRDSInstance_iamAuth
=== PAUSE TestAccRDSInstance_iamAuth
=== RUN   TestAccRDSInstance_allowMajorVersionUpgrade
=== PAUSE TestAccRDSInstance_allowMajorVersionUpgrade
=== RUN   TestAccRDSInstance_dbSubnetGroupName
=== PAUSE TestAccRDSInstance_dbSubnetGroupName
=== RUN   TestAccRDSInstance_DBSubnetGroupName_ramShared
=== PAUSE TestAccRDSInstance_DBSubnetGroupName_ramShared
=== RUN   TestAccRDSInstance_DBSubnetGroupName_vpcSecurityGroupIDs
=== PAUSE TestAccRDSInstance_DBSubnetGroupName_vpcSecurityGroupIDs
=== RUN   TestAccRDSInstance_deletionProtection
=== PAUSE TestAccRDSInstance_deletionProtection
=== RUN   TestAccRDSInstance_finalSnapshotIdentifier
=== PAUSE TestAccRDSInstance_finalSnapshotIdentifier
=== RUN   TestAccRDSInstance_FinalSnapshotIdentifier_skipFinalSnapshot
=== PAUSE TestAccRDSInstance_FinalSnapshotIdentifier_skipFinalSnapshot
=== RUN   TestAccRDSInstance_isAlreadyBeingDeleted
=== PAUSE TestAccRDSInstance_isAlreadyBeingDeleted
=== RUN   TestAccRDSInstance_maxAllocatedStorage
=== PAUSE TestAccRDSInstance_maxAllocatedStorage
=== RUN   TestAccRDSInstance_password
=== PAUSE TestAccRDSInstance_password
=== RUN   TestAccRDSInstance_ManagedMasterPassword_managed
=== PAUSE TestAccRDSInstance_ManagedMasterPassword_managed
=== RUN   TestAccRDSInstance_ManagedMasterPassword_managedSpecificKMSKey
=== PAUSE TestAccRDSInstance_ManagedMasterPassword_managedSpecificKMSKey
=== RUN   TestAccRDSInstance_ManagedMasterPassword_convertToManaged
=== PAUSE TestAccRDSInstance_ManagedMasterPassword_convertToManaged
=== RUN   TestAccRDSInstance_ReplicateSourceDB_basic
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_basic
=== RUN   TestAccRDSInstance_ReplicateSourceDB_namePrefix
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_namePrefix
=== RUN   TestAccRDSInstance_ReplicateSourceDB_nameGenerated
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_nameGenerated
=== RUN   TestAccRDSInstance_ReplicateSourceDB_addLater
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_addLater
=== RUN   TestAccRDSInstance_ReplicateSourceDB_allocatedStorage
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_allocatedStorage
=== RUN   TestAccRDSInstance_ReplicateSourceDB_iops
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_iops
=== RUN   TestAccRDSInstance_ReplicateSourceDB_allocatedStorageAndIops
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_allocatedStorageAndIops
=== RUN   TestAccRDSInstance_ReplicateSourceDB_allowMajorVersionUpgrade
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_allowMajorVersionUpgrade
=== RUN   TestAccRDSInstance_ReplicateSourceDB_autoMinorVersionUpgrade
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_autoMinorVersionUpgrade
=== RUN   TestAccRDSInstance_ReplicateSourceDB_availabilityZone
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_availabilityZone
=== RUN   TestAccRDSInstance_ReplicateSourceDB_backupRetentionPeriod
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_backupRetentionPeriod
=== RUN   TestAccRDSInstance_ReplicateSourceDB_backupWindow
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_backupWindow
=== RUN   TestAccRDSInstance_ReplicateSourceDB_dbSubnetGroupName
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_dbSubnetGroupName
=== RUN   TestAccRDSInstance_ReplicateSourceDBDBSubnetGroupName_ramShared
=== PAUSE TestAccRDSInstance_ReplicateSourceDBDBSubnetGroupName_ramShared
=== RUN   TestAccRDSInstance_ReplicateSourceDBDBSubnetGroupName_vpcSecurityGroupIDs
=== PAUSE TestAccRDSInstance_ReplicateSourceDBDBSubnetGroupName_vpcSecurityGroupIDs
=== RUN   TestAccRDSInstance_ReplicateSourceDB_deletionProtection
    acctest.go:75: CreateDBInstanceReadReplica API currently ignores DeletionProtection=true with SourceDBInstanceIdentifier set
--- SKIP: TestAccRDSInstance_ReplicateSourceDB_deletionProtection (0.00s)
=== RUN   TestAccRDSInstance_ReplicateSourceDB_iamDatabaseAuthenticationEnabled
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_iamDatabaseAuthenticationEnabled
=== RUN   TestAccRDSInstance_ReplicateSourceDB_maintenanceWindow
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_maintenanceWindow
=== RUN   TestAccRDSInstance_ReplicateSourceDB_maxAllocatedStorage
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_maxAllocatedStorage
=== RUN   TestAccRDSInstance_ReplicateSourceDB_monitoring
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_monitoring
=== RUN   TestAccRDSInstance_ReplicateSourceDB_monitoring_sourceAlreadyExists
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_monitoring_sourceAlreadyExists
=== RUN   TestAccRDSInstance_ReplicateSourceDB_multiAZ
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_multiAZ
=== RUN   TestAccRDSInstance_ReplicateSourceDB_networkType
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_networkType
=== RUN   TestAccRDSInstance_ReplicateSourceDB_parameterGroupNameSameSetOnBoth
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_parameterGroupNameSameSetOnBoth
=== RUN   TestAccRDSInstance_ReplicateSourceDB_parameterGroupNameDifferentSetOnBoth
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_parameterGroupNameDifferentSetOnBoth
=== RUN   TestAccRDSInstance_ReplicateSourceDB_parameterGroupNameReplicaCopiesValue
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_parameterGroupNameReplicaCopiesValue
=== RUN   TestAccRDSInstance_ReplicateSourceDB_parameterGroupNameSetOnReplica
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_parameterGroupNameSetOnReplica
=== RUN   TestAccRDSInstance_ReplicateSourceDB_port
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_port
=== RUN   TestAccRDSInstance_ReplicateSourceDB_vpcSecurityGroupIDs
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_vpcSecurityGroupIDs
=== RUN   TestAccRDSInstance_ReplicateSourceDB_caCertificateIdentifier
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_caCertificateIdentifier
=== RUN   TestAccRDSInstance_ReplicateSourceDB_replicaMode
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_replicaMode
=== RUN   TestAccRDSInstance_ReplicateSourceDB_parameterGroupTwoStep
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_parameterGroupTwoStep
=== RUN   TestAccRDSInstance_S3Import_basic
    acctest.go:75: RestoreDBInstanceFromS3 cannot restore from MySQL version 5.6
--- SKIP: TestAccRDSInstance_S3Import_basic (0.00s)
=== RUN   TestAccRDSInstance_SnapshotIdentifier_basic
=== PAUSE TestAccRDSInstance_SnapshotIdentifier_basic
=== RUN   TestAccRDSInstance_SnapshotIdentifier_namePrefix
=== PAUSE TestAccRDSInstance_SnapshotIdentifier_namePrefix
=== RUN   TestAccRDSInstance_SnapshotIdentifier_nameGenerated
=== PAUSE TestAccRDSInstance_SnapshotIdentifier_nameGenerated
=== RUN   TestAccRDSInstance_SnapshotIdentifier_AssociationRemoved
=== PAUSE TestAccRDSInstance_SnapshotIdentifier_As [...]

2023-03-24 13:56 UTC, AdamTylerLynch commented
### AccTests for `TestAccRDSClusterDataSource_`

### Output for acceptance tests
```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 10 -run='TestAccRDSInstanceDataSource_'  -timeout 180m
=== RUN   TestAccRDSInstanceDataSource_basic
=== PAUSE TestAccRDSInstanceDataSource_basic
=== RUN   TestAccRDSInstanceDataSource_ManagedMasterPassword_managed
=== PAUSE TestAccRDSInstanceDataSource_ManagedMasterPassword_managed
=== CONT  TestAccRDSInstanceDataSource_basic
=== CONT  TestAccRDSInstanceDataSource_ManagedMasterPassword_managed
2023-03-22T22:12:55.516Z [WARN]  sdk.proto: Response contains warning diagnostic: tf_provider_addr=registry.terraform.io/hashicorp/aws tf_proto_version=5.3 tf_resource_type=aws_db_instance diagnostic_severity=WARNING diagnostic_summary="Argument is deprecated" tf_req_id=5d229db6-4fc9-c82b-d657-e4700bb4c1ef tf_rpc=ValidateResourceTypeConfig diagnostic_attribute="AttributeName(\"name\")" diagnostic_detail="Use db_name instead"
2023-03-22T22:12:55.531Z [WARN]  sdk.proto: Response contains warning diagnostic: diagnostic_severity=WARNING diagnostic_summary="Argument is deprecated" tf_req_id=79efa4d8-078b-f28d-d2fb-c3fb5c21f0bf tf_proto_version=5.3 tf_resource_type=aws_db_instance diagnostic_detail="Use db_name instead" tf_provider_addr=registry.terraform.io/hashicorp/aws tf_rpc=ValidateResourceTypeConfig diagnostic_attribute="AttributeName(\"name\")"
2023-03-22T22:13:00.244Z [WARN]  sdk.proto: Response contains warning diagnostic: tf_rpc=ValidateResourceTypeConfig tf_resource_type=aws_db_instance tf_proto_version=5.3 diagnostic_detail="Use db_name instead" tf_req_id=a3de543c-6818-3e65-1a91-617b06fa8ab9 tf_provider_addr=registry.terraform.io/hashicorp/aws diagnostic_attribute="AttributeName(\"name\")" diagnostic_severity=WARNING diagnostic_summary="Argument is deprecated"
2023-03-22T22:13:00.378Z [WARN]  sdk.proto: Response contains warning diagnostic: tf_rpc=ValidateResourceTypeConfig tf_req_id=c0d43cf8-7c65-ee27-7145-67b2d661a0fd tf_provider_addr=registry.terraform.io/hashicorp/aws tf_proto_version=5.3 tf_resource_type=aws_db_instance diagnostic_detail="Use db_name instead" diagnostic_attribute="AttributeName(\"name\")" diagnostic_severity=WARNING diagnostic_summary="Argument is deprecated"
2023-03-22T22:13:01.075Z [WARN]  sdk.proto: Response contains warning diagnostic: tf_provider_addr=registry.terraform.io/hashicorp/aws diagnostic_attribute="AttributeName(\"name\")" diagnostic_detail="Use db_name instead" diagnostic_severity=WARNING tf_proto_version=5.3 tf_rpc=ValidateResourceTypeConfig tf_req_id=236ff0b1-5aa2-9705-6cf4-8e72b7c4be2c tf_resource_type=aws_db_instance diagnostic_summary="Argument is deprecated"
2023-03-22T22:13:01.227Z [WARN]  sdk.proto: Response contains warning diagnostic: tf_resource_type=aws_db_instance tf_proto_version=5.3 diagnostic_detail="Use db_name instead" diagnostic_summary="Argument is deprecated" tf_provider_addr=registry.terraform.io/hashicorp/aws tf_req_id=12a33047-64b8-1d7b-5a95-dc962bb13f6c diagnostic_severity=WARNING diagnostic_attribute="AttributeName(\"name\")" tf_rpc=ValidateResourceTypeConfig
2023-03-22T22:13:06.116Z [WARN]  sdk.proto: Response contains warning diagnostic: tf_resource_type=aws_db_instance tf_req_id=fd24db2b-e9db-475b-a5e7-7989061fe414 tf_proto_version=5.3 diagnostic_summary="Argument is deprecated" tf_provider_addr=registry.terraform.io/hashicorp/aws tf_rpc=ValidateResourceTypeConfig diagnostic_detail="Use db_name instead" diagnostic_severity=WARNING diagnostic_attribute="AttributeName(\"name\")"
2023-03-22T22:13:06.172Z [WARN]  sdk.proto: Response contains warning diagnostic: diagnostic_summary="Argument is deprecated" diagnostic_attribute="AttributeName(\"name\")" tf_proto_version=5.3 tf_resource_type=aws_db_instance tf_provider_addr=registry.terraform.io/hashicorp/aws diagnostic_severity=WARNING tf_rpc=ValidateResourceTypeConfig tf_req_id=0b983d4b-c2ba-7cca-33c4-f0f7d2cd12e4 diagnostic_detail="Use db_name instead"
2023-03-22T22:13:12.457Z [WARN]  sdk.proto: Response contains warning diagnostic: tf_proto_version=5.3 tf_rpc=ValidateResourceTypeConfig tf_provider_addr=registry.terraform.io/hashicorp/aws diagnostic_detail="Use db_name instead" diagnostic_summary="Argument is deprecated" tf_req_id=64a1ff8f-8dd2-05c8-e4c1-86be6b53ba78 tf_resource_type=aws_db_instance diagnostic_severity=WARNING diagnostic_attribute="AttributeName(\"name\")"
2023-03-22T22:13:12.580Z [WARN]  sdk.proto: Response contains warning diagnostic: tf_rpc=ValidateResourceTypeConfig tf_req_id=8590b24d-cb2b-b349-e458-9ae23ce1288a tf_provider_addr=registry.terraform.io/hashicorp/aws diagnostic_attribute="AttributeName(\"name\")" tf_proto_version=5.3 tf_resource_type=aws_db_instance diagnostic_detail="Use db_name instead" diagnostic_severity=WARNING diagnostic_summary="Argument is deprecated"
2023-03-22T22:16:59.769Z [WARN]  sdk.proto: Response contains warning diagnostic: tf_resource_type=aws_db_instance tf_provider_addr=registry.terraform.io/hashicorp/aws tf_proto_version=5.3 diagnostic_severity=WARNING tf_req_id=71ef8509-8a3b-ca5c-1225-67d1684a931c tf_rpc=ValidateResourceTypeConfig diagnostic_detail="Use db_name instead" diagnostic_summary="Argument is deprecated" diagnostic_attribute="AttributeName(\"name\")"
2023-03-22T22:17:04.638Z [WARN]  sdk.proto: Response contains warning diagnostic: tf_req_id=09e5b4b8-a42c-dd44-4be9-31a961e60750 tf_provider_addr=registry.terraform.io/hashicorp/aws tf_proto_version=5.3 diagnostic_detail="Use db_name instead" diagnostic_severity=WARNING diagnostic_summary="Argument is deprecated" tf_rpc=ValidateResourceTypeConfig tf_resource_type=aws_db_instance diagnostic_attribute="AttributeName(\"name\")"
2023-03-22T22:17:06.364Z [WARN]  sdk.proto: Response contains warning diagnostic: tf_proto_version=5.3 tf_rpc=ValidateResourceTypeConfig diagnostic_detail="Use db_name instead" diagnostic_severity=WARNING tf_req_id=470b9c24-01dd-356f-f70e-89887290fe1e tf_provider_addr=registry.terraform.io/hashicorp/aws diagnostic_attribute="AttributeName(\"name\")" tf_resource_type=aws_db_instance diagnostic_summary="Argument is deprecated"
2023-03-22T22:17:10.830Z [WARN]  sdk.proto: Response contains warning diagnostic: tf_rpc=ValidateResourceTypeConfig tf_provider_addr=registry.terraform.io/hashicorp/aws diagnostic_attribute="AttributeName(\"name\")" tf_proto_version=5.3 tf_resource_type=aws_db_instance tf_req_id=1cb2c9da-780d-e8a9-014c-156666888753 diagnostic_detail="Use db_name instead" diagnostic_severity=WARNING diagnostic_summary="Argument is deprecated"
2023-03-22T22:17:11.938Z [WARN]  sdk.proto: Response contains warning diagnostic: diagnostic_detail="Use db_name instead" diagnostic_summary="Argument is deprecated" tf_req_id=c42f462e-d1ed-370b-2bb1-ff0b597ad08b tf_proto_version=5.3 tf_rpc=ValidateResourceTypeConfig diagnostic_attribute="AttributeName(\"name\")" tf_provider_addr=registry.terraform.io/hashicorp/aws tf_resource_type=aws_db_instance diagnostic_severity=WARNING
2023-03-22T22:17:14.502Z [WARN]  sdk.proto: Response contains warning diagnostic: tf_resource_type=aws_db_instance diagnostic_severity=WARNING diagnostic_summary="Argument is deprecated" tf_req_id=e4b56d94-c2ca-590c-1a60-61d2ac4b5b64 tf_proto_version=5.3 diagnostic_detail="Use db_name instead" diagnostic_attribute="AttributeName(\"name\")" tf_provider_addr=registry.terraform.io/hashicorp/aws tf_rpc=ValidateResourceTypeConfig
2023-03-22T22:17:16.890Z [WARN]  sdk.proto: Response contains warning diagnostic: tf_proto_version=5.3 tf_provider_addr=registry.terraform.io/hashicorp/aws diagnostic_severity=WARNING diagnostic_summary="Argument is deprecated" tf_req_id=4cf91b89-7f96-124e-dc20-467b45eb3082 tf_rpc=ValidateResourceTypeConfig tf_resource_type=aws_db_instance diagnostic_detail="Use db_name instead" diagnostic_attribute="AttributeName(\"name\")"
2023-03-22T22:17:18.024Z [WARN]  sdk.helper_schema: Previously configured provider being re-configur [...]

2023-03-24 14:03 UTC, AdamTylerLynch commented
Ready for review.

2023-03-28 11:59 UTC, ewbankkit approved these changes
LGTM :rocket:.

```console
% ACCTEST_TIMEOUT=360m make testacc TESTARGS='-run=TestAccRDSInstance_basic\|TestAccRDSInstance_manage_password\|TestAccRDSInstance_ManagedMasterPassword_\|TestAccRDSInstance_password\|TestAccRDSInstanceDataSource_\|TestAccRDSClusterDataSource_\|TestAccRDSCluster_ManagedMasterPassword_\|TestAccRDSCluster_basic\|TestAccRDSCluster_SnapshotIdentifier_master' PKG=rds ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 3  -run=TestAccRDSInstance_basic\|TestAccRDSInstance_manage_password\|TestAccRDSInstance_ManagedMasterPassword_\|TestAccRDSInstance_password\|TestAccRDSInstanceDataSource_\|TestAccRDSClusterDataSource_\|TestAccRDSCluster_ManagedMasterPassword_\|TestAccRDSCluster_basic\|TestAccRDSCluster_SnapshotIdentifier_master -timeout 360m
=== RUN   TestAccRDSClusterDataSource_basic
=== PAUSE TestAccRDSClusterDataSource_basic
=== RUN   TestAccRDSClusterDataSource_ManagedMasterPassword_managed
=== PAUSE TestAccRDSClusterDataSource_ManagedMasterPassword_managed
=== RUN   TestAccRDSCluster_basic
=== PAUSE TestAccRDSCluster_basic
=== RUN   TestAccRDSCluster_ManagedMasterPassword_managed
=== PAUSE TestAccRDSCluster_ManagedMasterPassword_managed
=== RUN   TestAccRDSCluster_ManagedMasterPassword_managedSpecificKMSKey
=== PAUSE TestAccRDSCluster_ManagedMasterPassword_managedSpecificKMSKey
=== RUN   TestAccRDSCluster_ManagedMasterPassword_convertToManaged
=== PAUSE TestAccRDSCluster_ManagedMasterPassword_convertToManaged
=== RUN   TestAccRDSCluster_SnapshotIdentifier_masterPassword
=== PAUSE TestAccRDSCluster_SnapshotIdentifier_masterPassword
=== RUN   TestAccRDSCluster_SnapshotIdentifier_masterUsername
=== PAUSE TestAccRDSCluster_SnapshotIdentifier_masterUsername
=== RUN   TestAccRDSInstanceDataSource_basic
=== PAUSE TestAccRDSInstanceDataSource_basic
=== RUN   TestAccRDSInstanceDataSource_ManagedMasterPassword_managed
=== PAUSE TestAccRDSInstanceDataSource_ManagedMasterPassword_managed
=== RUN   TestAccRDSInstance_basic
=== PAUSE TestAccRDSInstance_basic
=== RUN   TestAccRDSInstance_manage_password
=== PAUSE TestAccRDSInstance_manage_password
=== RUN   TestAccRDSInstance_password
=== PAUSE TestAccRDSInstance_password
=== RUN   TestAccRDSInstance_ManagedMasterPassword_managed
=== PAUSE TestAccRDSInstance_ManagedMasterPassword_managed
=== RUN   TestAccRDSInstance_ManagedMasterPassword_managedSpecificKMSKey
=== PAUSE TestAccRDSInstance_ManagedMasterPassword_managedSpecificKMSKey
=== RUN   TestAccRDSInstance_ManagedMasterPassword_convertToManaged
=== PAUSE TestAccRDSInstance_ManagedMasterPassword_convertToManaged
=== CONT  TestAccRDSClusterDataSource_basic
=== CONT  TestAccRDSInstanceDataSource_basic
=== CONT  TestAccRDSInstance_password
--- PASS: TestAccRDSClusterDataSource_basic (179.12s)
=== CONT  TestAccRDSInstance_ManagedMasterPassword_managedSpecificKMSKey
--- PASS: TestAccRDSInstanceDataSource_basic (468.10s)
=== CONT  TestAccRDSInstance_ManagedMasterPassword_convertToManaged
--- PASS: TestAccRDSInstance_password (582.65s)
=== CONT  TestAccRDSInstance_basic
--- PASS: TestAccRDSInstance_ManagedMasterPassword_managedSpecificKMSKey (513.79s)
=== CONT  TestAccRDSInstance_manage_password        
--- PASS: TestAccRDSInstance_basic (404.12s)
=== CONT  TestAccRDSInstanceDataSource_ManagedMasterPassword_managed
--- PASS: TestAccRDSInstance_ManagedMasterPassword_convertToManaged (682.88s)
=== CONT  TestAccRDSInstance_ManagedMasterPassword_managed
--- PASS: TestAccRDSInstance_manage_password (540.26s)
=== CONT  TestAccRDSCluster_ManagedMasterPassword_managedSpecificKMSKey
--- PASS: TestAccRDSCluster_ManagedMasterPassword_managedSpecificKMSKey (158.38s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_masterUsername
--- PASS: TestAccRDSInstanceDataSource_ManagedMasterPassword_managed (543.98s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_masterPassword
--- PASS: TestAccRDSInstance_ManagedMasterPassword_managed (524.43s)
=== CONT  TestAccRDSCluster_ManagedMasterPassword_convertToManaged
--- PASS: TestAccRDSCluster_ManagedMasterPassword_convertToManaged (184.19s)
=== CONT  TestAccRDSCluster_basic
--- PASS: TestAccRDSCluster_SnapshotIdentifier_masterUsername (439.00s)
=== CONT  TestAccRDSCluster_ManagedMasterPassword_managed
--- PASS: TestAccRDSCluster_SnapshotIdentifier_masterPassword (388.45s)
=== CONT  TestAccRDSClusterDataSource_ManagedMasterPassword_managed
--- PASS: TestAccRDSCluster_basic (171.62s)
--- PASS: TestAccRDSCluster_ManagedMasterPassword_managed (170.96s)
--- PASS: TestAccRDSClusterDataSource_ManagedMasterPassword_managed (210.08s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	2134.054s
```

2023-03-28 12:00 UTC, ewbankkit commented
@fergoid @AdamTylerLynch Thanks for the contribution :tada: :clap:.

2023-03-28 12:31 UTC, merged

2023-04-17 19:42 UTC, jurajseffer commented
Do these tests cover that Terraform picks up `master_user_secret` as computed attribute for outputs? I'm not sure if I'm doing something wrong but simply using `aws_rds_cluster.this.master_user_secret[0].secret_arn` in an output for an existing/provisioned cluster which hasn't had `manage_master_user_password = true` applied yet results in plan failure: `The given key does not identify an element in this collection value: the collection has no elements.`