New Data Source: aws_redshiftserverless_workgroup
hashicorp/terraform-provider-aws pull request #29208
Opened 2023-02-02 02:17 UTC by bradsheppard

### Description
New Data Source for `aws_redshiftserverless_workgroup`.

### Relations

### References

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccRedshiftServerlessWorkgroupDataSource PKG=redshiftserverless
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/redshiftserverless/... -v -count 1 -parallel 20 -run='TestAccRedshiftServerlessWorkgroupDataSource'  -timeout 180m
=== RUN   TestAccRedshiftServerlessWorkgroupDataSource_basic
=== PAUSE TestAccRedshiftServerlessWorkgroupDataSource_basic
=== CONT  TestAccRedshiftServerlessWorkgroupDataSource_basic
--- PASS: TestAccRedshiftServerlessWorkgroupDataSource_basic (552.32s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/redshiftserverless	552.406s

...
```

2023-03-15 06:56 UTC, DrFaust92 requested changes
Minor issue, otherwise LGTM

2023-03-15 06:56 UTC, DrFaust92 commented on internal/service/redshiftserverless/workgroup_data_source.go
> +				Optional: true,
should be computed

2023-03-29 01:50 UTC, bradsheppard commented
@DrFaust92 Comments addressed! Also fixed merged conflicts, and switched to the `SDKDataSource` annotation, based on recent changes.

2023-04-19 12:22 UTC, ewbankkit approved these changes
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccRedshiftServerlessWorkgroupDataSource_' PKG=redshiftserverless
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/redshiftserverless/... -v -count 1 -parallel 20  -run=TestAccRedshiftServerlessWorkgroupDataSource_ -timeout 180m
=== RUN   TestAccRedshiftServerlessWorkgroupDataSource_basic
=== PAUSE TestAccRedshiftServerlessWorkgroupDataSource_basic
=== CONT  TestAccRedshiftServerlessWorkgroupDataSource_basic
--- PASS: TestAccRedshiftServerlessWorkgroupDataSource_basic (728.21s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/redshiftserverless	733.574s
```

2023-04-19 12:33 UTC, merged