[WIP] AWS IPAM Multi-Org ResourceDiscovery & ResourceDiscoveryAssociation
hashicorp/terraform-provider-aws pull request #29216
Opened 2023-02-02 13:38 UTC by drewmullen

### Description

Add new IPAM Multi-organizational resource types, resource discovery and resource discovery association

### Relations

Closes #29116

### References

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccIPAMResourceDiscovery_ PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccIPAMResourceDiscovery_'  -timeout 180m
=== RUN   TestAccIPAMResourceDiscovery_basic
=== PAUSE TestAccIPAMResourceDiscovery_basic
=== RUN   TestAccIPAMResourceDiscovery_modify
=== PAUSE TestAccIPAMResourceDiscovery_modify
=== RUN   TestAccIPAMResourceDiscovery_disappears
=== PAUSE TestAccIPAMResourceDiscovery_disappears
=== RUN   TestAccIPAMResourceDiscovery_tags
=== PAUSE TestAccIPAMResourceDiscovery_tags
=== CONT  TestAccIPAMResourceDiscovery_basic
=== CONT  TestAccIPAMResourceDiscovery_disappears
=== CONT  TestAccIPAMResourceDiscovery_modify
=== CONT  TestAccIPAMResourceDiscovery_tags
--- PASS: TestAccIPAMResourceDiscovery_disappears (24.35s)
--- PASS: TestAccIPAMResourceDiscovery_basic (26.70s)
--- PASS: TestAccIPAMResourceDiscovery_tags (44.87s)
--- PASS: TestAccIPAMResourceDiscovery_modify (84.00s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        84.112s

$ make testacc TESTS=TestAccIPAMResourceDiscoveryAssociation_ PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccIPAMResourceDiscoveryAssociation_'  -timeout 180m
=== RUN   TestAccIPAMResourceDiscoveryAssociation_basic
=== PAUSE TestAccIPAMResourceDiscoveryAssociation_basic
=== RUN   TestAccIPAMResourceDiscoveryAssociation_tags
=== PAUSE TestAccIPAMResourceDiscoveryAssociation_tags
=== RUN   TestAccIPAMResourceDiscoveryAssociation_disappears
=== PAUSE TestAccIPAMResourceDiscoveryAssociation_disappears
=== CONT  TestAccIPAMResourceDiscoveryAssociation_basic
=== CONT  TestAccIPAMResourceDiscoveryAssociation_disappears
=== CONT  TestAccIPAMResourceDiscoveryAssociation_tags
--- PASS: TestAccIPAMResourceDiscoveryAssociation_basic (37.96s)
--- PASS: TestAccIPAMResourceDiscoveryAssociation_disappears (38.71s)
--- PASS: TestAccIPAMResourceDiscoveryAssociation_tags (57.34s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        57.446s
...
```

2023-02-02 14:32 UTC, drewmullen commented
sweepers working:
1.  build a resource discovery
2. attach to an ipam
3. build another resource discovery
4. run sweepers

youll end up with no associations, and only the default resource discovery:
```
$ SWEEPARGS=-sweep-run=aws_vpc_ipam_resource_discovery make sweep
# make sweep SWEEPARGS=-sweep-run=aws_example_thing
# set SWEEPARGS=-sweep-allow-failures to continue after first failure
WARNING: This will destroy infrastructure. Use only in development accounts.
go test ./internal/sweep -v -tags=sweep -sweep=us-west-2,us-east-1,us-east-2 -sweep-run=aws_vpc_ipam_resource_discovery -timeout 60m
2023/02/02 14:31:26 [DEBUG] Running Sweepers for region (us-west-2):
2023/02/02 14:31:26 [DEBUG] Running Sweeper (aws_vpc_ipam_resource_discovery) in region (us-west-2)
2023/02/02 14:31:26 [INFO] Retrieved credentials from "EnvConfigCredentials"
2023/02/02 14:31:26 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2023/02/02 14:31:27 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2023/02/02 14:31:27 [DEBUG] Completed Sweeper (aws_vpc_ipam_resource_discovery) in region (us-west-2) in 672.158886ms
2023/02/02 14:31:27 Completed Sweepers for region (us-west-2) in 672.218998ms
2023/02/02 14:31:27 Sweeper Tests for region (us-west-2) ran successfully:
        - aws_vpc_ipam_resource_discovery
2023/02/02 14:31:27 [DEBUG] Running Sweepers for region (us-east-1):
2023/02/02 14:31:27 [DEBUG] Running Sweeper (aws_vpc_ipam_resource_discovery) in region (us-east-1)
2023/02/02 14:31:27 [INFO] Retrieved credentials from "EnvConfigCredentials"
2023/02/02 14:31:27 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2023/02/02 14:31:27 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2023/02/02 14:31:27 [DEBUG] Waiting for state to become: [success]
2023/02/02 14:31:27 [DEBUG] Waiting for state to become: [success]
2023/02/02 14:31:27 [DEBUG] Deleting IPAMResourceDiscovery: ipam-res-disco-009445ae4ba7118d9
2023/02/02 14:31:27 [DEBUG] Deleting IPAMResourceDiscovery: ipam-res-disco-0b6ee7c578c4683ae
2023/02/02 14:31:27 [DEBUG] Waiting for state to become: []
2023/02/02 14:31:27 [DEBUG] Waiting for state to become: []
2023/02/02 14:31:32 [DEBUG] Completed Sweeper (aws_vpc_ipam_resource_discovery) in region (us-east-1) in 5.496641656s
2023/02/02 14:31:32 Completed Sweepers for region (us-east-1) in 5.496662633s
2023/02/02 14:31:32 Sweeper Tests for region (us-east-1) ran successfully:
        - aws_vpc_ipam_resource_discovery
2023/02/02 14:31:32 [DEBUG] Running Sweepers for region (us-east-2):
2023/02/02 14:31:32 [DEBUG] Running Sweeper (aws_vpc_ipam_resource_discovery) in region (us-east-2)
2023/02/02 14:31:32 [INFO] Retrieved credentials from "EnvConfigCredentials"
2023/02/02 14:31:32 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2023/02/02 14:31:33 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2023/02/02 14:31:33 [DEBUG] Completed Sweeper (aws_vpc_ipam_resource_discovery) in region (us-east-2) in 221.781903ms
2023/02/02 14:31:33 Completed Sweepers for region (us-east-2) in 221.805348ms
2023/02/02 14:31:33 Sweeper Tests for region (us-east-2) ran successfully:
        - aws_vpc_ipam_resource_discovery
ok      github.com/hashicorp/terraform-provider-aws/internal/sweep      6.414s
```

2023-02-02 18:11 UTC, drewmullen commented
tests still passing after adding missed err check
```
$ make testacc TESTS=TestAccIPAMResourceDiscovery_ PKG=ec2       
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccIPAMResourceDiscovery_'  -timeout 180m
=== RUN   TestAccIPAMResourceDiscovery_basic
=== PAUSE TestAccIPAMResourceDiscovery_basic
=== RUN   TestAccIPAMResourceDiscovery_modify
=== PAUSE TestAccIPAMResourceDiscovery_modify
=== RUN   TestAccIPAMResourceDiscovery_disappears
=== PAUSE TestAccIPAMResourceDiscovery_disappears
=== RUN   TestAccIPAMResourceDiscovery_tags
=== PAUSE TestAccIPAMResourceDiscovery_tags
=== CONT  TestAccIPAMResourceDiscovery_basic
=== CONT  TestAccIPAMResourceDiscovery_disappears
=== CONT  TestAccIPAMResourceDiscovery_tags
=== CONT  TestAccIPAMResourceDiscovery_modify
--- PASS: TestAccIPAMResourceDiscovery_disappears (24.52s)
--- PASS: TestAccIPAMResourceDiscovery_basic (27.07s)
--- PASS: TestAccIPAMResourceDiscovery_tags (45.28s)
--- PASS: TestAccIPAMResourceDiscovery_modify (84.15s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        84.259s
```

2023-02-02 19:55 UTC, AdamTylerLynch requested changes
Requesting a few changes related to context passing and documentation. Thank you so much for this PR!

2023-02-02 19:55 UTC, AdamTylerLynch commented on internal/service/ec2/ipam_resource_discovery.go
> +		_, err := conn.ModifyIpamResourceDiscovery(input)
Please use the WithContext() method from the SDK.

2023-02-02 19:55 UTC, AdamTylerLynch commented on internal/service/ec2/ipam_resource_discovery_association.go
> +	output, err := conn.AssociateIpamResourceDiscovery(input)
Please use WithContext() method from the SDK.

2023-02-02 19:55 UTC, AdamTylerLynch commented on internal/service/ec2/ipam_resource_discovery_association.go
> +		TagSpecifications:       tagSpecificationsFromKeyValueTags(tags, "ipam-resource-discovery-association"),
Can we pull this from the SDK as to not use a magic string?

2023-02-02 19:55 UTC, AdamTylerLynch commented on internal/service/ec2/ipam_resource_discovery_association.go
> +	_, err := conn.DisassociateIpamResourceDiscovery(input)
Please use WithContext() method from the SDK.

2023-02-02 19:55 UTC, AdamTylerLynch commented on website/docs/r/vpc_ipam_resource_discovery_association.html.markdown
> +IPAMs can be imported using the `ipam resource discovery id`, e.g.
Should be association ID?

2023-02-02 19:55 UTC, AdamTylerLynch commented on website/docs/r/vpc_ipam_resource_discovery_association.html.markdown
> +* `id` - The ID of the IPAM Resource Discovery
Should be association ID in the description?

2023-02-02 19:55 UTC, AdamTylerLynch commented on website/docs/r/vpc_ipam_resource_discovery_association.html.markdown
> +* `description` - (Optional) A description for the IPAM Resource Discovery.
```suggestion
* `description` - (Optional) A description for the IPAM Resource Discovery Association.
```

2023-02-02 19:55 UTC, AdamTylerLynch commented on website/docs/r/vpc_ipam_resource_discovery_association.html.markdown
> +* `arn` - Amazon Resource Name (ARN) of IPAM Resource Discovery
```suggestion
* `arn` - Amazon Resource Name (ARN) of IPAM Resource Discovery Association
```

2023-02-02 20:43 UTC, AdamTylerLynch commented
LGTM 🚀

2023-02-16 15:13 UTC, ewbankkit approved these changes
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccIPAMResourceDiscovery_serial/ResourceDiscovery' PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccIPAMResourceDiscovery_serial/ResourceDiscovery -timeout 180m
=== RUN   TestAccIPAMResourceDiscovery_serial
=== PAUSE TestAccIPAMResourceDiscovery_serial
=== CONT  TestAccIPAMResourceDiscovery_serial
=== RUN   TestAccIPAMResourceDiscovery_serial/ResourceDiscovery
=== RUN   TestAccIPAMResourceDiscovery_serial/ResourceDiscovery/basic
=== RUN   TestAccIPAMResourceDiscovery_serial/ResourceDiscovery/modify
=== RUN   TestAccIPAMResourceDiscovery_serial/ResourceDiscovery/disappears
=== RUN   TestAccIPAMResourceDiscovery_serial/ResourceDiscovery/tags
--- PASS: TestAccIPAMResourceDiscovery_serial (220.44s)
    --- PASS: TestAccIPAMResourceDiscovery_serial/ResourceDiscovery (220.44s)
        --- PASS: TestAccIPAMResourceDiscovery_serial/ResourceDiscovery/basic (31.85s)
        --- PASS: TestAccIPAMResourceDiscovery_serial/ResourceDiscovery/modify (101.10s)
        --- PASS: TestAccIPAMResourceDiscovery_serial/ResourceDiscovery/disappears (26.86s)
        --- PASS: TestAccIPAMResourceDiscovery_serial/ResourceDiscovery/tags (60.62s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	228.465s
% make testacc TESTARGS='-run=TestAccIPAMResourceDiscovery_serial/ResourceDiscoveryAssociation' PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccIPAMResourceDiscovery_serial/ResourceDiscoveryAssociation -timeout 180m
=== RUN   TestAccIPAMResourceDiscovery_serial
=== PAUSE TestAccIPAMResourceDiscovery_serial
=== CONT  TestAccIPAMResourceDiscovery_serial
=== RUN   TestAccIPAMResourceDiscovery_serial/ResourceDiscoveryAssociation
=== RUN   TestAccIPAMResourceDiscovery_serial/ResourceDiscoveryAssociation/basic
=== RUN   TestAccIPAMResourceDiscovery_serial/ResourceDiscoveryAssociation/disappears
=== RUN   TestAccIPAMResourceDiscovery_serial/ResourceDiscoveryAssociation/tags
--- PASS: TestAccIPAMResourceDiscovery_serial (97.72s)
    --- PASS: TestAccIPAMResourceDiscovery_serial/ResourceDiscoveryAssociation (147.72s)
        --- PASS: TestAccIPAMResourceDiscovery_serial/ResourceDiscoveryAssociation/basic (39.28s)
        --- PASS: TestAccIPAMResourceDiscovery_serial/ResourceDiscoveryAssociation/disappears (39.15s)
        --- PASS: TestAccIPAMResourceDiscovery_serial/ResourceDiscoveryAssociation/tags (63.53s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	154.254s
```

2023-02-16 15:14 UTC, ewbankkit commented
@drewmullen Thanks for the contribution :tada: :clap:.

2023-02-16 16:34 UTC, merged