patch default AWS values for origin config in the doc
hashicorp/terraform-provider-aws pull request #31146
Opened 2023-05-04 04:28 UTC by ashish-r

### Description

The [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#custom-origin-config-arguments) for CloudFront custom origin states default values for `origin_keepalive_timeout` and `origin_read_timeout` as `60`. However on the AWS console and in the AWS documentation for CloudFront the default value for `origin_keepalive_timeout` is 5 seconds and `origin_read_timeout` is 30 seconds. 
[Reference](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#request-custom-request-timeout) for origin_read_timeout.
[Reference](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesOriginKeepaliveTimeout) for origin_keepalive_timeout

### Relations

Closes #0000

### References

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccXXX PKG=ec2

...
```

2023-05-04 17:03 UTC, justinretzolk requested changes
Hey @ashish-r 👋 Thank you for taking the time to raise this! It looks like the intent of the existing documentation was to note the maximum value that AWS will accept by default without requesting an increase, rather than to document the default values that will be used. I've suggested updates to make both of these things more clear.

2023-05-04 17:03 UTC, justinretzolk commented on website/docs/r/cloudfront_distribution.html.markdown
> +* `origin_read_timeout` - (Optional) The Custom Read timeout, in seconds. By default, AWS enforces a limit of `30`. But you can request an [increase](http://docs.aws.amazon.com/AmazonCloudFront/lates
```suggestion
* `origin_read_timeout` - (Optional) The Custom Read timeout, in seconds. By default, AWS enforces an upper limit of `60`. But you can request an [increase](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#request-custom-request-timeout). Defaults to `30`.
```

2023-05-08 18:13 UTC, ashish-r commented
Hi @justinretzolk 👋🏼 I have committed the suggested changes.

2023-05-12 16:32 UTC, justinretzolk approved these changes
Thank you for taking the time to submit this, and for committing those changes! I've approved the additional workflows to run, and will get this merged in as soon as we can.

2023-05-12 19:43 UTC, merged