securityhub_standards_control: improve docs for control ARNs
hashicorp/terraform-provider-aws pull request #31795
Opened 2023-06-06 15:22 UTC by ulfjack

### Description

Improve docs to help users find the right control ARNs.

2023-06-08 15:49 UTC, justinretzolk requested changes
Thank you for taking the time to raise this! I made a couple of minor suggestions here that I think we should do prior to merging this:

- Updated the links to point to AWC CLI v2 documentation
- Updated to use formatted links rather than bare URLs

2023-06-08 15:49 UTC, justinretzolk commented on website/docs/r/securityhub_standards_control.markdown
> +* `standards_control_arn` - (Required) The standards control ARN. See the AWS tool documentation for how to list existing controls, https://docs.aws.amazon.com/cli/latest/reference/securityhub/get-en
```suggestion
* `standards_control_arn` - (Required) The standards control ARN. See the AWS documentation for how to list existing controls using [`get-enabled-standards`](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/securityhub/get-enabled-standards.html) and [`describe-standards-controls`](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/securityhub/describe-standards-controls.html).
```

2023-06-15 10:49 UTC, ulfjack commented
Thanks! Any other feedback?

2023-07-10 17:07 UTC, justinretzolk approved these changes
Looks good to me! Thank you again for taking the time to raise this! I'll get this merged once the checks finish up 🚀

2023-07-10 18:52 UTC, merged