d/ mq broker versions
hashicorp/terraform-provider-aws pull request #34232
Opened 2023-11-02 22:20 UTC by danquack

### Description

Adds Data lookup for Engine Versions

### Relations

Closes #34168

### References

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccMQEngineVersionsDataSource_ PKG=mq                                                                            
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/mq/... -v -count 1 -parallel 20 -run='TestAccMQEngineVersionsDataSource_'  -timeout 360m
=== RUN   TestAccMQEngineVersionsDataSource_basic
=== PAUSE TestAccMQEngineVersionsDataSource_basic
=== CONT  TestAccMQEngineVersionsDataSource_basic
--- PASS: TestAccMQEngineVersionsDataSource_basic (16.78s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/mq 19.028s
```

Notes to maintainers:
- It doesn't looks like there's a v2 client to use sdkv2, so I just used the existing conn.
- I created a filters block. Im happy to remove that and just have engine_type in the root of the schema to better align with the sdk, since there's technically no filters, but this way more aligned to how other resources are setup.

2023-11-03 18:42 UTC, drewmullen requested changes

2023-11-03 18:42 UTC, drewmullen commented on internal/service/mq/engine_versions_data_source.go
> +	"github.com/hashicorp/terraform-provider-aws/internal/conns"
😅 You should make this SDKv2. You'll probably need to generate a client for this. Here is a doc that will help: https://github.com/hashicorp/terraform-provider-aws/tree/main/names

2023-12-22 16:14 UTC, ewbankkit approved these changes
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccMQBrokerEngineTypesDataSource_' PKG=mq
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/mq/... -v -count 1 -parallel 20  -run=TestAccMQBrokerEngineTypesDataSource_ -timeout 360m
=== RUN   TestAccMQBrokerEngineTypesDataSource_basic
=== PAUSE TestAccMQBrokerEngineTypesDataSource_basic
=== CONT  TestAccMQBrokerEngineTypesDataSource_basic
--- PASS: TestAccMQBrokerEngineTypesDataSource_basic (12.15s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/mq	17.498s
```

2023-12-22 16:15 UTC, ewbankkit commented
@danquack Thanks for the contribution :tada: :clap:.
I renamed the data source to `aws_mq_broker_engine_types`, matching the [underlying AWS API](https://docs.aws.amazon.com/amazon-mq/latest/api-reference/broker-engine-types.html).

2023-12-22 17:15 UTC, merged