d/aws_batch_job_definition
hashicorp/terraform-provider-aws pull request #34663
Opened 2023-11-30 18:59 UTC by danquack

### Description
Creates a data source for `batch_job_definition`.

This PR has a prerequisite dependency of #34281.

I am probably doing something stupid, but mixing internal fwTypes and extensions are a bit confusing me. Some of the problems I am running into:
- Single Nested Object Type with `fwtypes.NewObjectTypeOf` is causing a panic. If I comment those fields out, the test itself passes.
- Node Properties, EKS Properties not being set onto flex.flatten (maybe the same cause as above)

Some of the work still to do:
- [ ] Docs
- [ ] Additional Tests

### Relations
closes #28665

### References

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccBatchJobDefinitionDataSource_basicName PKG=batch                                              
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/batch/... -v -count 1 -parallel 20 -run='TestAccBatchJobDefinitionDataSource_basicName'  -timeout 360m
=== RUN   TestAccBatchJobDefinitionDataSource_basicName
=== PAUSE TestAccBatchJobDefinitionDataSource_basicName
=== CONT  TestAccBatchJobDefinitionDataSource_basicName
panic: ObjectValueMust received error(s): Error | Invalid Object Attribute Type | While creating a Object value, an invalid attribute value was detected. A Object must use a matching attribute type for the value. This is always an issue with the provider and should be reported to the provider developers.

Object Attribute Name (node_properties) Expected Type: ObjectTypeOf[batch.frameworkNodeProperties]
Object Attribute Name (node_properties) Given Type: ObjectTypeOf[batch.frameworkNodeProperties]

```

2024-01-03 16:20 UTC, drewmullen requested changes
1 requested change

2024-01-03 16:20 UTC, drewmullen commented on internal/service/batch/job_definition_data_source.go
> +			"arn": schema.StringAttribute{
Can you add an `arn_prefix` attribute please

2024-01-04 01:55 UTC, drewmullen approved these changes
LGTM!

```shell
make testacc TESTS="TestAccBatchJobDefinitionDataSource" PKG=batch  
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/batch/... -v -count 1 -parallel 20 -run='TestAccBatchJobDefinitionDataSource'  -timeout 360m
=== RUN   TestAccBatchJobDefinitionDataSource_basicName
=== PAUSE TestAccBatchJobDefinitionDataSource_basicName
=== RUN   TestAccBatchJobDefinitionDataSource_basicARN
=== PAUSE TestAccBatchJobDefinitionDataSource_basicARN
=== RUN   TestAccBatchJobDefinitionDataSource_basicARN_NodeProperties
=== PAUSE TestAccBatchJobDefinitionDataSource_basicARN_NodeProperties
=== RUN   TestAccBatchJobDefinitionDataSource_basicARN_EKSProperties
=== PAUSE TestAccBatchJobDefinitionDataSource_basicARN_EKSProperties
=== CONT  TestAccBatchJobDefinitionDataSource_basicName
=== CONT  TestAccBatchJobDefinitionDataSource_basicARN_NodeProperties
=== CONT  TestAccBatchJobDefinitionDataSource_basicARN
=== CONT  TestAccBatchJobDefinitionDataSource_basicARN_EKSProperties
--- PASS: TestAccBatchJobDefinitionDataSource_basicARN_EKSProperties (41.02s)
--- PASS: TestAccBatchJobDefinitionDataSource_basicARN_NodeProperties (42.70s)
--- PASS: TestAccBatchJobDefinitionDataSource_basicName (57.54s)
--- PASS: TestAccBatchJobDefinitionDataSource_basicARN (67.12s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/batch      69.494s
```

2024-02-19 20:07 UTC, ewbankkit approved these changes
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccBatchJobDefinitionDataSource_' PKG=batch ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/batch/... -v -count 1 -parallel 2  -run=TestAccBatchJobDefinitionDataSource_ -timeout 360m
=== RUN   TestAccBatchJobDefinitionDataSource_basicName
=== PAUSE TestAccBatchJobDefinitionDataSource_basicName
=== RUN   TestAccBatchJobDefinitionDataSource_basicARN
=== PAUSE TestAccBatchJobDefinitionDataSource_basicARN
=== RUN   TestAccBatchJobDefinitionDataSource_basicARN_NodeProperties
=== PAUSE TestAccBatchJobDefinitionDataSource_basicARN_NodeProperties
=== RUN   TestAccBatchJobDefinitionDataSource_basicARN_EKSProperties
=== PAUSE TestAccBatchJobDefinitionDataSource_basicARN_EKSProperties
=== CONT  TestAccBatchJobDefinitionDataSource_basicName
=== CONT  TestAccBatchJobDefinitionDataSource_basicARN_EKSProperties
--- PASS: TestAccBatchJobDefinitionDataSource_basicARN_EKSProperties (17.97s)
=== CONT  TestAccBatchJobDefinitionDataSource_basicARN_NodeProperties
--- PASS: TestAccBatchJobDefinitionDataSource_basicName (30.52s)
=== CONT  TestAccBatchJobDefinitionDataSource_basicARN
--- PASS: TestAccBatchJobDefinitionDataSource_basicARN_NodeProperties (16.76s)
--- PASS: TestAccBatchJobDefinitionDataSource_basicARN (26.84s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/batch	68.476s
```

2024-02-19 20:15 UTC, ewbankkit commented
@danquack Thanks for the contribution :tada: :clap:.

2024-02-19 21:07 UTC, danquack commented
I noticed you switched the data source from using Single Object -> List to work with autoflex. By switching to lists, should these tests also work without an index? One of the reasons I did object originally was for the purity of not having to do `.0`, but that may be something we want to do with the provider (#35813).

https://github.com/hashicorp/terraform-provider-aws/blob/4a89becdea4f21ee3985ef3e61499becb741e3da/internal/service/batch/job_definition_data_source_test.go#L132-L133

Also, when I run the test command I am seeing some panics in the auto flexing. I see yours passed, but maybe it is something in my local development setup, just borked?

```shell
make testacc TESTARGS='-run=TestAccBatchJobDefinitionDataSource_' PKG=batch ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/batch/... -v -count 1 -parallel 2  -run=TestAccBatchJobDefinitionDataSource_ -timeout 360m
=== RUN   TestAccBatchJobDefinitionDataSource_basicName
=== PAUSE TestAccBatchJobDefinitionDataSource_basicName
=== RUN   TestAccBatchJobDefinitionDataSource_basicARN
=== PAUSE TestAccBatchJobDefinitionDataSource_basicARN
=== RUN   TestAccBatchJobDefinitionDataSource_basicARN_NodeProperties
=== PAUSE TestAccBatchJobDefinitionDataSource_basicARN_NodeProperties
=== RUN   TestAccBatchJobDefinitionDataSource_basicARN_EKSProperties
=== PAUSE TestAccBatchJobDefinitionDataSource_basicARN_EKSProperties
=== CONT  TestAccBatchJobDefinitionDataSource_basicName
=== CONT  TestAccBatchJobDefinitionDataSource_basicARN_NodeProperties
=== NAME  TestAccBatchJobDefinitionDataSource_basicName
    job_definition_data_source_test.go:23: Step 1/2 error: Check failed: Check 3/3 error: data.aws_batch_job_definition.test: Attribute 'retry_strategy.attempts' not found
=== NAME  TestAccBatchJobDefinitionDataSource_basicARN_NodeProperties
    job_definition_data_source_test.go:91: Step 1/1 error: Check failed: Check 1/3 error: data.aws_batch_job_definition.test: Attribute 'node_properties.main_node' not found
--- FAIL: TestAccBatchJobDefinitionDataSource_basicName (10.53s)
=== CONT  TestAccBatchJobDefinitionDataSource_basicARN_EKSProperties
--- FAIL: TestAccBatchJobDefinitionDataSource_basicARN_NodeProperties (10.59s)
=== CONT  TestAccBatchJobDefinitionDataSource_basicARN
panic: Value Conversion Error

An unexpected error was encountered trying to convert from struct value. This is always an error in the provider. Please report the following to the provider developer:

error retrieving field names from struct tags: [0].limits: can't use field name for both Limits and Requests
[0]

goroutine 10330 [running]:
github.com/hashicorp/terraform-provider-aws/internal/errs.Must[...](...)
	/Users/danielquackenbush/code/aws/terraform-provider-aws/internal/errs/must.go:13
github.com/hashicorp/terraform-provider-aws/internal/errs/fwdiag.Must[...](...)
	/Users/danielquackenbush/code/aws/terraform-provider-aws/internal/errs/fwdiag/must.go:17
github.com/hashicorp/terraform-provider-aws/internal/framework/types.newListNestedObjectValueOf[...]({0x113262c30, 0x14004633860}, {0x110558960, 0x14002d68de0})
	/Users/danielquackenbush/code/aws/terraform-provider-aws/internal/framework/types/list_nested_objectof.go:236 +0x138
github.com/hashicorp/terraform-provider-aws/internal/framework/types.NewListNestedObjectValueOfSlice[...](...)
	/Users/danielquackenbush/code/aws/terraform-provider-aws/internal/framework/types/list_nested_objectof.go:228
github.com/hashicorp/terraform-provider-aws/internal/framework/types.NewListNestedObjectValueOfPtr[...](...)
	/Users/danielquackenbush/code/aws/terraform-provider-aws/internal/framework/types/list_nested_objectof.go:224
github.com/hashicorp/terraform-provider-aws/internal/framework/types.listNestedObjectTypeOf[...].ValueFromObjectPtr(0x1132e1280?, {0x113262c30?, 0x14004633860}, {0x110510600, 0x14002d4b180})
	/Users/danielquackenbush/code/aws/terraform-provider-aws/internal/framework/types/list_nested_objectof.go:115 +0xd4
github.com/hashicorp/terraform-provider-aws/internal/framework/flex.autoFlattener.structToNestedObject({}, {0x113262c30, 0x14004633860}, {0x11234ea20?, 0x14002d68b10?, 0x140036247e8?}, 0xc4?, {0x1295abcd8, 0x14004f47930}, {0x112d84860?, ...})
	/Users/danielquackenbush/code/aws/terraform-provider-aws/internal/framework/flex/auto_flatten.go:721 +0x22c
github.com/hashicorp/terraform-provider-aws/internal/framework/flex.autoFlattener.struct_({}, {0x113262c30, 0x14004633860}, {0x11234ea20?, 0x14002d68b10?, 0x14004f47920?}, 0x68?, {0x113278ad8?, 0x14004f47930?}, {0x112d84860?, ...})
	/Users/danielquackenbush/code/aws/terraform-provider-aws/internal/framework/flex/auto_flatten.go:304 +0x20c
github.com/hashicorp/terraform-provider-aws/internal/framework/flex.autoFlattener.ptr({}, {0x113262c30, 0x14004633860}, {0x1111436e0?, 0x1400b3b5ad0?, 0x1132d85e8?}, {0x113278ad8?, 0x14004f47930?}, {0x112d84860?, 0x1400b5f9bd8?, ...})
	/Users/danielquackenbush/code/aws/terraform-provider-aws/internal/framework/flex/auto_flatten.go:284 +0x3d4
github.com/hashicorp/terraform-provider-aws/internal/framework/flex.autoFlattener.convert({}, {0x113262c30, 0x14004633860}, {0x1111436e0?, 0x1400b3b5ad0?, 0x1400acae780?}, {0x112d84860?, 0x1400b5f9bd8?, 0x102ee53a0?})
	/Users/danielquackenbush/code/aws/terraform-provider-aws/internal/framework/flex/auto_flatten.go:76 +0x250
github.com/hashicorp/terraform-provider-aws/internal/framework/flex.autoFlexConvertStruct({0x113262c30, 0x14004633860}, {0x112d8f700?, 0x1400b3b5a70?}, {0x1105106c0?, 0x1400b5f9b00?}, {0x1130dea00, 0x11aff1940})
	/Users/danielquackenbush/code/aws/terraform-provider-aws/internal/framework/flex/autoflex.go:110 +0x2c4
github.com/hashicorp/terraform-provider-aws/internal/framework/flex.autoFlattener.sliceOfStructNestedObjectCollection({}, {0x113262c30, 0x14004633860}, {0x1105614e0?, 0x1400d950f00?, 0x1121355c0?}, {0x1295abba8, 0x14004f478c0}, {0x112d84c80?, 0x14002cf4480?, ...})
	/Users/danielquackenbush/code/aws/terraform-provider-aws/internal/framework/flex/auto_flatten.go:762 +0x42c
github.com/hashicorp/terraform-provider-aws/internal/framework/flex.autoFlattener.slice({}, {0x113262c30, 0x14004633860}, {0x1105614e0?, 0x1400d950f00?, 0x1132d85e8?}, {0x113278778?, 0x14004f478c0}, {0x112d84c80?, 0x14002cf4480?, ...})
	/Users/danielquackenbush/code/aws/terraform-provider-aws/internal/framework/flex/auto_flatten.go:489 +0x450
github.com/hashicorp/terraform-provider-aws/internal/framework/flex.autoFlattener.convert({}, {0x113262c30, 0x14004633860}, {0x1105614e0?, 0x1400d950f00?, 0x1400acae648?}, {0x112d84c80?, 0x14002cf4480?, 0x102ee53a0?})
	/Users/danielquackenbush/code/aws/terraform-provider-aws/internal/framework/flex/auto_flatten.go:80 +0x2a4
github.com/hashicorp/terraform-provider-aws/internal/framework/flex.autoFlexConvertStruct({0x113262c30, 0x14004633860}, {0x112bd4820?, 0x1400d950f00?}, {0x110510840?, 0x14002cf4480?}, {0x1130dea00, 0x11aff1940})
	/Users/danielquackenbush/code/aws/terraform-provider-aws/internal/framework/flex/autoflex.go:110 +0x2c4
github.com/hashicorp/terraform-provider-aws/internal/framework/flex.autoFlattener.structToNestedObject({}, {0x113262c30, 0x14004633860}, {0x112bd4820?, 0x1400d950cc0?, 0x111b68800?}, 0x0?, {0x1295abb48, 0x14004f47830}, {0x112d854c0?, ...})
	/Users/danielquackenbush/code/aws/terraform-provider-aws/internal/framework/flex/auto_flatten.go:715 +0x190
github.com/hashicorp/terraform-provider-aws/internal/framework/flex.autoFlattener.struct_({}, {0x113262c30, 0x14004633860}, {0x112bd4820?, 0x1400d950cc0?, 0x112d85360?}, 0xa9?, {0x1132780b8?, 0x14004f47830?}, {0x112d854c0?, ...})
	/Users/danielquackenbush/code/aws/terraform-provider-aws/internal/framework/flex/auto_flatten.go:304 +0x20c
github.com/hashicorp/terraform-provider-aws/internal/framework/flex.autoFlattener.ptr({}, {0x113262c30, 0x14004633860}, {0x111143b00?, 0x14004f47730?, 0x1132d85e8?}, {0x1132780b8?, 0x14004f47830?}, {0x112d854c0?, 0x14006ee6de0?, ...})
	/Users/danielquacke [...]

2024-02-19 21:15 UTC, ewbankkit commented
Actually, something seems to have gone awry with that last merge. They were working...

2024-02-19 21:17 UTC, ewbankkit commented
374458ac696367a1556a85022fde13b014b3273a fixes those final problems.

2024-02-19 21:43 UTC, merged