docs: Add access_control_translation cfg block desc to aws_s3_bucket resource doc
hashicorp/terraform-provider-aws pull request #35293
Opened 2024-01-14 00:27 UTC by acwwat

### Description

This PR adds more details for the `access_control_translation` configuration block that is relevant to replication configuration for the `aws_s3_bucket` resource.

### Relations

Closes #33894

### References

Referenced the [AccessControlTranslation API data type](https://docs.aws.amazon.com/AmazonS3/latest/API/API_AccessControlTranslation.html) for wordings.

### Output from Acceptance Testing

n/a

2024-01-16 22:08 UTC, justinretzolk requested changes
A couple of minor suggestions to preserve anchor links, but otherwise looks good to me! Thank you for taking the time to contribute again!

2024-01-16 22:08 UTC, justinretzolk commented on website/docs/r/s3_bucket.html.markdown
> +* `access_control_translation` - (Optional) Specifies the overrides to use for object owners on replication ([documented below](#access-control-translation)). Must be used in conjunction with `accoun
This, in conjunction with the other suggestion, will make sure that we don't wind up with duplicate anchor links

```suggestion
* `access_control_translation` - (Optional) Specifies the overrides to use for object owners on replication ([documented below](#access_control_translation-block)). Must be used in conjunction with `account_id` owner override configuration.
```

2024-01-16 22:08 UTC, justinretzolk commented on website/docs/r/s3_bucket.html.markdown
> +#### Access Control Translation
```suggestion
#### `access_control_translation` Block
```

2024-01-17 05:39 UTC, acwwat commented
@justinretzolk Thanks for the review. I've made this one change, but there are 10s of other configuration blocks in the resource doc that are following the old style. Let me know if you'd like me to update the whole doc so that the style is consistent. Otherwise the PR is ready for your re-review.

2024-01-17 17:21 UTC, justinretzolk approved these changes
Hey @acwwat -- Let's merge the changes that you were targeting with this PR and then we can either open an issue so that we can come back for the others, or open a fresh PR to correct the rest. Since this is in good shape, I'll get it merged in shortly 🚀

2024-01-17 17:21 UTC, merged