docs: Identify cfg blocks more explicitly for option and param group docs
hashicorp/terraform-provider-aws pull request #35297
Opened 2024-01-14 01:17 UTC by acwwat

### Description

This PR is to add more clarity to the configuration block arguments in the `aws_db_option_group` and `aws_db_parameter_group` resource documentation.

### Relations

Closes #33887

### References

Used the [aws_vpn_connection resource doc](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpn_connection) as guidance for better structuring the configuration block descriptions.

### Output from Acceptance Testing

n/a

2024-01-16 21:30 UTC, justinretzolk requested changes
Thank you for another awesome contribution! 

On the registry page, argument names have anchor links generated for them. I've found that in those cases, if there's also a header that exactly matched the argument name, the anchor links don't work properly. With that in mind, I suggested some changes, using the format of "`argument_name` Block" for the headers.

2024-01-16 21:30 UTC, justinretzolk commented on website/docs/r/db_option_group.html.markdown
> +### Option
```suggestion
### `option` Block
```

2024-01-16 21:30 UTC, justinretzolk commented on website/docs/r/db_option_group.html.markdown
> +* `option` - (Optional) The options to apply. See [Option](#option) below for more details.
```suggestion
* `option` - (Optional) The options to apply. See [`option` Block](#option-block) below for more details.
```

2024-01-16 21:30 UTC, justinretzolk commented on website/docs/r/db_option_group.html.markdown
> +* `option_settings` - (Optional) The option settings to apply. See [Option Settings](#option-settings) below for more details.
```suggestion
* `option_settings` - (Optional) The option settings to apply. See [`option_settings` Block](#option_settings-block) below for more details.
```

2024-01-16 21:30 UTC, justinretzolk commented on website/docs/r/db_option_group.html.markdown
> +#### Option Settings
```suggestion
#### `option_settings` Block
```

2024-01-16 21:30 UTC, justinretzolk commented on website/docs/r/db_parameter_group.html.markdown
> +### Parameter
```suggestion
### `parameter` Block
```

2024-01-16 21:33 UTC, acwwat commented
> Thank you for another awesome contribution!
> 
> On the registry page, argument names have anchor links generated for them. I've found that in those cases, if there's also a header that exactly matched the argument name, the anchor links don't work properly. With that in mind, I suggested some changes, using the format of "`argument_name` Block" for the headers.

Thanks, good to know that there's a convention because I've seen multiple styles throughout the docs. I will amend with the proposed changes later today.

2024-01-17 17:18 UTC, justinretzolk approved these changes
Looks good! Thanks for making that change. This is definitely something we need to standardize across all of the docs, but there's some other docs-related things I'd like to sort out first 🙂 . Thanks again for the stream of contributions! I'll get this one merged in shortly.

2024-01-17 17:18 UTC, merged