aws_iam _role upgrade to framework and inline policy change
hashicorp/terraform-provider-aws pull request #35634
Opened 2024-02-05 00:51 UTC by teddylear

### Description
Upgrades `aws_iam_role` to `terraform-plugin-framework` and resolve issue with `inline_policy` being a set in `sdkv2` to a `map` in the `terraform-plugin-framework` to resolve linked issue below with inline policy plans and fully deleting then recrating policies on changes instead of just updating in place and then removing policies that are no longer present. Using terraform from that issue with base terraform update here in new version of provider: 
```terraform
resource "aws_iam_role" "main" {
  assume_role_policy = data.aws_iam_policy_document.trust.json
  name               = "terraform-issue-reproduction"

  inline_policies = {
    "InlinePolicy" = data.aws_iam_policy_document.inline.json
  }
}

# Inline policy document that we'll be changing
data "aws_iam_policy_document" "inline" {
  statement {
    sid     = "S3"
    actions = ["s3:ListBucket"]
    resources = [
      "arn:aws:s3:::some-bucket-a",
      # After the first apply, uncomment this next line
      # "arn:aws:s3:::some-bucket-b",
    ]
  }
}

# Minimal, arbitrary trust statement to make the role valid
data "aws_iam_policy_document" "trust" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["apigateway.amazonaws.com"]
    }
  }
}
```

And the plan to add second bucket in inline policy produces this plan which is close to original one in ticket: 
```terraform
  # aws_iam_role.main will be updated in-place
  ~ resource "aws_iam_role" "main" {
        id                    = "terraform-issue-reproduction"
      ~ inline_policies       = {
          ~ "InlinePolicy" = jsonencode(
              ~ {
                  ~ Statement = [
                      ~ {
                          ~ Resource = "arn:aws:s3:::some-bucket-a" -> [
                              + "arn:aws:s3:::some-bucket-b",
                              + "arn:aws:s3:::some-bucket-a",
                            ]
                            # (3 unchanged attributes hidden)
                        },
                    ]
                    # (1 unchanged attribute hidden)
                }
            )
        }
        name                  = "terraform-issue-reproduction"
        # (8 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

Adding a third bucket produces this plan which is even more user friendly:
```terraform
  # aws_iam_role.main will be updated in-place
  ~ resource "aws_iam_role" "main" {
        id                    = "terraform-issue-reproduction"
      ~ inline_policies       = {
          ~ "InlinePolicy" = jsonencode(
              ~ {
                  ~ Statement = [
                      ~ {
                          ~ Resource = [
                              + "arn:aws:s3:::some-bucket-c",
                                "arn:aws:s3:::some-bucket-b",
                                # (1 unchanged element hidden)
                            ]
                            # (3 unchanged attributes hidden)
                        },
                    ]
                    # (1 unchanged attribute hidden)
                }
            )
        }
        name                  = "terraform-issue-reproduction"
        # (8 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

Please let me know if there's any other test or anything else I should be adding here. I tried to document as many behavior changes as possible in the existing tests. There are some import changes which are best noted in the tests and code itself. Also please let me know if I should squash commits. 

### Relations
Closes #22336

### Output from Acceptance Testing
Added some new tests to confirm some validation functionality as well as upgrade from previous version of prodiver. Some existing tests had to be changed as result of migration to `terraform-plugin-framework`. I tried to document them as best as possible in `role_test.go` file. 
```console
 > make testacc TESTS=TestAccIAMRole_ PKG=iam

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMRole_'  -timeout 360m
=== RUN   TestAccIAMRole_basic
=== PAUSE TestAccIAMRole_basic
=== RUN   TestAccIAMRole_MigrateFromPluginSDK_basic
=== PAUSE TestAccIAMRole_MigrateFromPluginSDK_basic
=== RUN   TestAccIAMRole_description
=== PAUSE TestAccIAMRole_description
=== RUN   TestAccIAMRole_nameGenerated
=== PAUSE TestAccIAMRole_nameGenerated
=== RUN   TestAccIAMRole_namePrefix
=== PAUSE TestAccIAMRole_namePrefix
=== RUN   TestAccIAMRole_testNameChange
=== PAUSE TestAccIAMRole_testNameChange
=== RUN   TestAccIAMRole_diffsNoCondition
=== PAUSE TestAccIAMRole_diffsNoCondition
=== RUN   TestAccIAMRole_diffsCondition
=== PAUSE TestAccIAMRole_diffsCondition
=== RUN   TestAccIAMRole_badJSON
=== PAUSE TestAccIAMRole_badJSON
=== RUN   TestAccIAMRole_disappears
=== PAUSE TestAccIAMRole_disappears
=== RUN   TestAccIAMRole_policiesForceDetach
=== PAUSE TestAccIAMRole_policiesForceDetach
=== RUN   TestAccIAMRole_maxSessionDuration
=== PAUSE TestAccIAMRole_maxSessionDuration
=== RUN   TestAccIAMRole_permissionsBoundary
=== PAUSE TestAccIAMRole_permissionsBoundary
=== RUN   TestAccIAMRole_tags
=== PAUSE TestAccIAMRole_tags
=== RUN   TestAccIAMRole_InlinePolicy_basic
=== PAUSE TestAccIAMRole_InlinePolicy_basic
=== RUN   TestAccIAMRole_MigrateFromPluginSDK_InlinePolicy
=== PAUSE TestAccIAMRole_MigrateFromPluginSDK_InlinePolicy
=== RUN   TestAccIAMRole_InlinePolicy_badJSON
=== PAUSE TestAccIAMRole_InlinePolicy_badJSON
=== RUN   TestAccIAMRole_InlinePolicy_ignoreOrder
=== PAUSE TestAccIAMRole_InlinePolicy_ignoreOrder
=== RUN   TestAccIAMRole_InlinePolicy_empty
=== PAUSE TestAccIAMRole_InlinePolicy_empty
=== RUN   TestAccIAMRole_ManagedPolicy_basic
=== PAUSE TestAccIAMRole_ManagedPolicy_basic
=== RUN   TestAccIAMRole_ManagedPolicy_badARN
=== PAUSE TestAccIAMRole_ManagedPolicy_badARN
=== RUN   TestAccIAMRole_ManagedPolicy_outOfBandRemovalAddedBack
=== PAUSE TestAccIAMRole_ManagedPolicy_outOfBandRemovalAddedBack
=== RUN   TestAccIAMRole_InlinePolicy_outOfBandRemovalAddedBack
=== PAUSE TestAccIAMRole_InlinePolicy_outOfBandRemovalAddedBack
=== RUN   TestAccIAMRole_ManagedPolicy_outOfBandAdditionRemoved
=== PAUSE TestAccIAMRole_ManagedPolicy_outOfBandAdditionRemoved
=== RUN   TestAccIAMRole_InlinePolicy_outOfBandAdditionRemoved
=== PAUSE TestAccIAMRole_InlinePolicy_outOfBandAdditionRemoved
=== RUN   TestAccIAMRole_InlinePolicy_outOfBandAdditionIgnored
=== PAUSE TestAccIAMRole_InlinePolicy_outOfBandAdditionIgnored
=== RUN   TestAccIAMRole_ManagedPolicy_outOfBandAdditionIgnored
=== PAUSE TestAccIAMRole_ManagedPolicy_outOfBandAdditionIgnored
=== RUN   TestAccIAMRole_InlinePolicy_outOfBandAdditionRemovedEmpty
=== PAUSE TestAccIAMRole_InlinePolicy_outOfBandAdditionRemovedEmpty
=== RUN   TestAccIAMRole_ManagedPolicy_outOfBandAdditionRemovedEmpty
=== PAUSE TestAccIAMRole_ManagedPolicy_outOfBandAdditionRemovedEmpty
=== CONT  TestAccIAMRole_basic
=== CONT  TestAccIAMRole_MigrateFromPluginSDK_InlinePolicy
=== CONT  TestAccIAMRole_ManagedPolicy_outOfBandAdditionRemovedEmpty
=== CONT  TestAccIAMRole_InlinePolicy_outOfBandAdditionIgnored
=== CONT  TestAccIAMRole_InlinePolicy_outOfBandAdditionRemoved
=== CONT  TestAccIAMRole_badJSON
=== CONT  TestAccIAMRole_InlinePolicy_outOfBandAdditionRemovedEmpty
=== CONT  TestAccIAMRole_InlinePolicy_outOfBandRemovalAddedBack
=== CONT  TestAccIAMRole_ManagedPolicy_outOfBandRemovalAddedBack
=== CONT  TestAccIAMRole_ManagedPolicy_badARN
=== CONT  TestAccIAMRole_ManagedPolicy_basic
=== CONT  TestAccIAMRole_InlinePolicy_empty
=== CONT  TestAccIAMRole_InlinePolicy_ignoreOrder
=== CONT  TestAccIAMRole_InlinePolicy_basic
=== CONT  TestAccIAMRole_tags
=== CONT  TestAccIAMRole_permissionsBoundary
=== CONT  TestAccIAMRole_maxSessionDuration
=== CONT  TestAccIAMRole_policiesForceDetach
=== CONT  TestAccIAMRole_InlinePolicy_badJSON
=== CONT  TestAccIAMRole_ManagedP [...]

2024-02-08 18:34 UTC, mbevc1 approved these changes

2024-02-12 22:01 UTC, justinretzolk commented
Hey @teddylear 👋 Thanks for taking the time to raise this, and apologies for missing your pings on the original issue. I brought this up internally as well, to try to get a bit more traction 🙂

2024-02-12 23:58 UTC, teddylear commented
@justinretzolk Hey! No worries and thanks for the reply. If there's anything I need to add to change please let me know or if one of the maintainers needs to edit the branch directly that works as well. This is my first time doing a migration from `sdkv2` to the `plugin-framework` so I may have missed something 😅. Also happy to help with more of these too as this was a good learning experience and could do for the `aws_iam_role` data source as well along with doing for other terraform provider resources.

2024-04-16 00:09 UTC, gdavison requested changes
Thanks for submitting this, @teddylear. I have a number of comments on the PR. The biggest is that the change from `inline_policy` to `inline_policies` should be in a separate PR, and also still needs to support `inline_policy` because of backwards compatibility guarantees.

2024-04-16 00:09 UTC, gdavison commented on internal/service/iam/role_test.go
> +			},
We can't change the acceptable values here until the next major version. `permissions_boundary` will have to accept an empty string and treat it as no value. Validation should only check for a valid ARN if it's not an empty string

2024-04-17 22:25 UTC, teddylear commented on internal/service/iam/role_test.go
> +				},
The Linked issue above describes what is happening, it was a  `Failed to marshal state to json:` error when upgrading no matter what I did. The upstream `terraform-plugin-testing` plugin has updated documentation to use this instead.

2026-08-14 17:58 UTC, closed without merging