cross account attachment
hashicorp/terraform-provider-aws pull request #35991
Opened 2024-02-27 20:30 UTC by kathmbeck

### Description

### Relations

Closes #0000

### References

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccXXX PKG=ec2

...
```

2024-04-03 13:30 UTC, kathmbeck commented
Hi @ewbankkit! 👋 Wanted to check in here on anything I can do to push this along?

2024-04-09 17:36 UTC, coolfrood commented
Hi @ewbankkit! I'm on the AWS Global Accelerator team and I've previously contributed to Global Accelerator's Terraform implementation. In this case, one of our key partners would like to merge in this PR so that they can use a new resource type supported by Global Accelerator. Could you help us?

2024-04-10 13:58 UTC, AdamTylerLynch requested changes
What a great first Pull Request! We very much appreciate your contribution! I have requested a few small changes. 

I do appreciate the unit tests, and they provide value, I have asked Hashi engineer @ewbankkit to provide feedback on the unit tests, as we generally only conduct integration tests.

2024-04-10 13:58 UTC, AdamTylerLynch commented on internal/service/globalaccelerator/cross_account_attachment.go
> +		Attributes: map[string]schema.Attribute{
Attributes should be defined in alphabetical order (not the order that the AWS API defines them in).

2024-04-10 13:58 UTC, AdamTylerLynch commented on internal/service/globalaccelerator/cross_account_attachment.go
> +			"attachment_arn": framework.ARNAttributeComputedOnly(),
We preference using simply `arn` for consistency across resource types.

Cite: https://hashicorp.github.io/terraform-provider-aws/raising-a-pull-request/#resource-contribution-guidelines:~:text=Implements%20arn%20Attribute

"attachment_arn": framework.ARNAttributeComputedOnly(),
```suggestion
			"arn": framework.ARNAttributeComputedOnly(),
```

2024-04-10 13:58 UTC, AdamTylerLynch commented on internal/service/globalaccelerator/cross_account_attachment_test.go
> +func TestExpandResources(t *testing.T) {
@ewbankkit we don't normally see unit test, thought on this?

2024-04-10 16:57 UTC, kathmbeck commented
@AdamTylerLynch Thank you for the review! I've implemented your suggestions and will await feedback on inclusion of the unit tests.

2024-04-23 15:33 UTC, ewbankkit approved these changes
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccEC2EIPDataSource_filter\|TestAccEC2EIP_basic' PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccEC2EIPDataSource_filter\|TestAccEC2EIP_basic -timeout 360m
=== RUN   TestAccEC2EIPDataSource_filter
=== PAUSE TestAccEC2EIPDataSource_filter
=== RUN   TestAccEC2EIP_basic
=== PAUSE TestAccEC2EIP_basic
=== CONT  TestAccEC2EIPDataSource_filter
=== CONT  TestAccEC2EIP_basic
--- PASS: TestAccEC2EIPDataSource_filter (18.78s)
--- PASS: TestAccEC2EIP_basic (21.89s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	32.160s
```
```console
% make testacc TESTARGS='-run=TestAccGlobalAcceleratorCrossAccountAttachment_' PKG=globalaccelerator ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/globalaccelerator/... -v -count 1 -parallel 2  -run=TestAccGlobalAcceleratorCrossAccountAttachment_ -timeout 360m
=== RUN   TestAccGlobalAcceleratorCrossAccountAttachment_basic
=== PAUSE TestAccGlobalAcceleratorCrossAccountAttachment_basic
=== RUN   TestAccGlobalAcceleratorCrossAccountAttachment_principals
=== PAUSE TestAccGlobalAcceleratorCrossAccountAttachment_principals
=== RUN   TestAccGlobalAcceleratorCrossAccountAttachment_resources
=== PAUSE TestAccGlobalAcceleratorCrossAccountAttachment_resources
=== RUN   TestAccGlobalAcceleratorCrossAccountAttachment_disappears
=== PAUSE TestAccGlobalAcceleratorCrossAccountAttachment_disappears
=== RUN   TestAccGlobalAcceleratorCrossAccountAttachment_tags
=== PAUSE TestAccGlobalAcceleratorCrossAccountAttachment_tags
=== CONT  TestAccGlobalAcceleratorCrossAccountAttachment_basic
=== CONT  TestAccGlobalAcceleratorCrossAccountAttachment_disappears
--- PASS: TestAccGlobalAcceleratorCrossAccountAttachment_disappears (17.46s)
=== CONT  TestAccGlobalAcceleratorCrossAccountAttachment_tags
--- PASS: TestAccGlobalAcceleratorCrossAccountAttachment_basic (32.11s)
=== CONT  TestAccGlobalAcceleratorCrossAccountAttachment_resources
--- PASS: TestAccGlobalAcceleratorCrossAccountAttachment_tags (43.36s)
=== CONT  TestAccGlobalAcceleratorCrossAccountAttachment_principals
--- PASS: TestAccGlobalAcceleratorCrossAccountAttachment_principals (28.81s)
--- PASS: TestAccGlobalAcceleratorCrossAccountAttachment_resources (227.81s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/globalaccelerator	269.545s
```

2024-04-23 21:34 UTC, ewbankkit commented
@kathmbeck Thanks for the contribution :tada: :clap:.

2024-04-23 21:34 UTC, merged