[NEW RESOURCE] AWS Backup Restore Testing
hashicorp/terraform-provider-aws pull request #37039
Opened 2024-04-22 13:19 UTC by Thomas-Franklin

### Description

Introduces the `aws_backup_restore_testing_plan` and `aws_backup-restore_selection` resources. These resources manages the AWS Backup Restore Testing functionality within AWS.

### Relations

Closes https://github.com/hashicorp/terraform-provider-aws/issues/34699

### References

* https://docs.aws.amazon.com/cli/latest/reference/backup/create-restore-testing-selection.html
* https://docs.aws.amazon.com/cli/latest/reference/backup/create-restore-testing-plan.html
* https://aws.amazon.com/blogs/aws/automatic-restore-testing-and-validation-is-now-available-in-aws-backup/

### Output from Acceptance Testing

BackupRestoreTestingPlan:

```console
make testacc TESTS=TestAccBackupRestoreTestingPlan_\* PKG=backup
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/backup/... -v -count 1 -parallel 20 -run='TestAccBackupRestoreTestingPlan_*'  -timeout 360m
=== RUN   TestAccBackupRestoreTestingPlan_basic
=== PAUSE TestAccBackupRestoreTestingPlan_basic
=== RUN   TestAccBackupRestoreTestingPlan_disappears
=== PAUSE TestAccBackupRestoreTestingPlan_disappears
=== RUN   TestAccBackupRestoreTestingPlan_tags
=== PAUSE TestAccBackupRestoreTestingPlan_tags
=== RUN   TestAccBackupRestoreTestingPlan_includevaults
=== PAUSE TestAccBackupRestoreTestingPlan_includevaults
=== RUN   TestAccBackupRestoreTestingPlan_excludevaults
=== PAUSE TestAccBackupRestoreTestingPlan_excludevaults
=== RUN   TestAccBackupRestoreTestingPlan_additionals
=== PAUSE TestAccBackupRestoreTestingPlan_additionals
=== RUN   TestAccBackupRestoreTestingPlan_additionalwithupdates
=== PAUSE TestAccBackupRestoreTestingPlan_additionalwithupdates
=== CONT  TestAccBackupRestoreTestingPlan_basic
=== CONT  TestAccBackupRestoreTestingPlan_excludevaults
=== CONT  TestAccBackupRestoreTestingPlan_tags
=== CONT  TestAccBackupRestoreTestingPlan_additionalwithupdates
=== CONT  TestAccBackupRestoreTestingPlan_additionals
=== CONT  TestAccBackupRestoreTestingPlan_includevaults
=== CONT  TestAccBackupRestoreTestingPlan_disappears
--- PASS: TestAccBackupRestoreTestingPlan_disappears (11.29s)
--- PASS: TestAccBackupRestoreTestingPlan_basic (13.65s)
--- PASS: TestAccBackupRestoreTestingPlan_additionals (13.67s)
--- PASS: TestAccBackupRestoreTestingPlan_includevaults (19.38s)
--- PASS: TestAccBackupRestoreTestingPlan_excludevaults (19.41s)
--- PASS: TestAccBackupRestoreTestingPlan_tags (20.19s)
--- PASS: TestAccBackupRestoreTestingPlan_additionalwithupdates (21.60s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/backup	25.337s
```

BackupRestoreTestingSelection:

```console
make testacc TESTS=TestAccBackupRestoreTestingSelection_\* PKG=backup
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/backup/... -v -count 1 -parallel 20 -run='TestAccBackupRestoreTestingSelection_*'  -timeout 360m
=== RUN   TestAccBackupRestoreTestingSelection_basic
=== PAUSE TestAccBackupRestoreTestingSelection_basic
=== RUN   TestAccBackupRestoreTestingSelection_disappears
=== PAUSE TestAccBackupRestoreTestingSelection_disappears
=== RUN   TestAccBackupRestoreTestingSelection_updates
=== PAUSE TestAccBackupRestoreTestingSelection_updates
=== CONT  TestAccBackupRestoreTestingSelection_basic
=== CONT  TestAccBackupRestoreTestingSelection_disappears
=== CONT  TestAccBackupRestoreTestingSelection_updates
--- PASS: TestAccBackupRestoreTestingSelection_disappears (17.21s)
--- PASS: TestAccBackupRestoreTestingSelection_basic (20.33s)
--- PASS: TestAccBackupRestoreTestingSelection_updates (29.72s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/backup	33.571s
```

2024-05-30 13:56 UTC, mervin-hemaraju-cko commented
Heyy, when is this getting merged?

2024-07-02 13:17 UTC, Nirrleybo commented
Any update on this being merged in?

2024-07-10 14:00 UTC, Thomas-Franklin commented
> Any update on this being merged in?

Not heard anything, but I have rebased it to make it easier for the owners to merge.

2024-07-19 09:00 UTC, ricoleabricot commented
Up-ing this PR, as I think it could be merged as it (and recently rebased).
@justinretzolk any way we could have an ETA of merge + next provider version?

2024-07-19 19:48 UTC, aristosvo requested changes
Hi @Thomas-Franklin!

Thanks for this PR! I'm 'just' another contributor who is also eager to get this resource in (better today than tomorrow 😄 ). I went through your PR and flagged some stuff that could use some change on a first look. I'm not a maintainer and cannot push this PR through, so don't expect too much of it 😺 

If my comments are a bit short and need some explanation, please let me know.

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/find.go
> +	"github.com/aws/aws-sdk-go/aws"
I think there are some changes not rebased entirely correct, like this one:
```suggestion
	"github.com/aws/aws-sdk-go-v2/aws"
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/find.go
> +func FindRestoreTestingPlanByName(ctx context.Context, conn *backup.Client, name string) (*backup.GetRestoreTestingPlanOutput, error) {
Lowercase/private seems to be the standard for now
```suggestion
func findRestoreTestingPlanByName(ctx context.Context, conn *backup.Client, name string) (*backup.GetRestoreTestingPlanOutput, error) {
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/find.go
> +func FindRestoreTestingSelectionByName(ctx context.Context, conn *backup.Client, name string, restoreTestingPlanName string) (*backup.GetRestoreTestingSelectionOutput, error) {
Same here
```suggestion
func findRestoreTestingSelectionByName(ctx context.Context, conn *backup.Client, name string, restoreTestingPlanName string) (*backup.GetRestoreTestingSelectionOutput, error) {
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_plan.go
> +	"github.com/aws/aws-sdk-go/aws"
v2 again :)
```suggestion
	"github.com/aws/aws-sdk-go-v2/aws"
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_plan.go
> +// ==== SCHEMA ==== //
Clean :)
```suggestion
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_plan.go
> +// ==== FUNCTIONS ==== //
I think these aren't necessary
```suggestion
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_plan.go
> +// ==== STATE REFRESH ==== //
Unnecessary comment I think?
```suggestion
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_plan.go
> +
```suggestion
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_plan.go
> +
```suggestion
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_plan.go
> +// ==== DATA STRUCTURES ==== //
```suggestion
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_plan_test.go
> +// ==== ACCEPTANCE TESTS ==== //
```suggestion
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_plan_test.go
> +					resource.TestCheckResourceAttr(resourceName, "tags.%", "1"), // has tags
```suggestion
					resource.TestCheckResourceAttr(resourceName, "tags.%", "1"),
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_plan_test.go
> +					resource.TestCheckResourceAttr(resourceName, "tags.%", "1"), // has tags
```suggestion
					resource.TestCheckResourceAttr(resourceName, "tags.%", "1"),
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_plan_test.go
> +func TestAccBackupRestoreTestingPlan_includevaults(t *testing.T) {
```suggestion
func TestAccBackupRestoreTestingPlan_includeVaults(t *testing.T) {
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_plan_test.go
> +				Config: testAccRestoreTestingPlanConfig_includevaults(rName),
```suggestion
				Config: testAccRestoreTestingPlanConfig_includeVaults(rName),
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_plan_test.go
> +func TestAccBackupRestoreTestingPlan_excludevaults(t *testing.T) {
```suggestion
func TestAccBackupRestoreTestingPlan_excludeVaults(t *testing.T) {
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_plan_test.go
> +				Config: testAccRestoreTestingPlanConfig_excludevaults(rName),
```suggestion
				Config: testAccRestoreTestingPlanConfig_excludeVaults(rName),
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_plan_test.go
> +// ====== Helper Functions ====== //
```suggestion
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_plan_test.go
> +// ====== Terraform Configuration Functions ====== //
```suggestion
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_plan_test.go
> +func testAccRestoreTestingPlanConfig_includevaults(rName string) string {
```suggestion
func testAccRestoreTestingPlanConfig_includeVaults(rName string) string {
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_plan_test.go
> +func testAccRestoreTestingPlanConfig_excludevaults(rName string) string {
```suggestion
func testAccRestoreTestingPlanConfig_excludeVaults(rName string) string {
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_selection.go
> +// ==== SCHEMA ==== //
```suggestion
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_selection.go
> +// ==== DATA STRUCTURES ==== //
```suggestion
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_selection_test.go
> +// ==== ACCEPTANCE TESTS ==== //
```suggestion
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_selection_test.go
> +// ====== Helper Functions ====== //
```suggestion
```

2024-07-19 19:48 UTC, aristosvo commented on internal/service/backup/restore_testing_selection_test.go
> +// ====== Terraform Configuration Functions ====== //
```suggestion
```

2024-07-19 19:48 UTC, aristosvo commented on names/data/names_data.csv
Please delete, this is due to the rebase out of date

2024-07-22 08:25 UTC, Thomas-Franklin commented
@aristosvo - I believe I have addressed all your suggestions, appreciate the kind review!

2024-07-22 12:22 UTC, aristosvo commented on internal/service/backup/exports_test.go
> +	findRestoreTestingSelectionByName = findRestoreTestingSelectionByName
```suggestion
	FindRestoreTestingSelectionByName = findRestoreTestingSelectionByName
```

2024-07-23 19:03 UTC, aristosvo commented
@Thomas-Franklin I asked the HC maintainers to enable all linters/checks, some work to do😅

2024-07-23 19:50 UTC, Thomas-Franklin commented
> @Thomas-Franklin I asked the HC maintainers to enable all linters/checks, some work to do😅

I will take a look tomorrow at the failing actions, thanks for all the support 🙏

2024-07-24 14:07 UTC, Thomas-Franklin commented
Okay I did run the lint fix @aristosvo but it changed 4000 markdown files... I suppose I should commit just my markdown files?

2024-07-24 14:11 UTC, aristosvo commented
> Okay I did run the lint fix @aristosvo but it changed 4000 markdown files... I suppose I should commit just my markdown files?

Yes, definitely. Besides that, I noticed you changed a lot in `names/data/names_data.hcl`, that might be the cause of some of these issues as well.

2024-08-13 09:18 UTC, Thomas-Franklin commented
Hi @justinretzolk - rebased and solved conflicts again, with a clean up of suggestions by @aristosvo ; just wondering what we can do to get this further along in for a release. 🤞

2024-09-13 05:55 UTC, mervin-hemaraju-cko commented
Hello all, could we please take a look and merge this? 🙌🏽

2024-10-04 18:37 UTC, ewbankkit approved these changes
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccBackupRestoreTesting' PKG=backup ACCTEST_PARALLELISM=3 
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.1 test ./internal/service/backup/... -v -count 1 -parallel 3  -run=TestAccBackupRestoreTesting -timeout 360m
=== RUN   TestAccBackupRestoreTestingPlan_basic
=== PAUSE TestAccBackupRestoreTestingPlan_basic
=== RUN   TestAccBackupRestoreTestingPlan_disappears
=== PAUSE TestAccBackupRestoreTestingPlan_disappears
=== RUN   TestAccBackupRestoreTestingPlan_tags
=== PAUSE TestAccBackupRestoreTestingPlan_tags
=== RUN   TestAccBackupRestoreTestingPlan_includeVaults
=== PAUSE TestAccBackupRestoreTestingPlan_includeVaults
=== RUN   TestAccBackupRestoreTestingPlan_excludeVaults
=== PAUSE TestAccBackupRestoreTestingPlan_excludeVaults
=== RUN   TestAccBackupRestoreTestingPlan_additionals
=== PAUSE TestAccBackupRestoreTestingPlan_additionals
=== RUN   TestAccBackupRestoreTestingPlan_additionalsWithUpdate
=== PAUSE TestAccBackupRestoreTestingPlan_additionalsWithUpdate
=== RUN   TestAccBackupRestoreTestingSelection_basic
=== PAUSE TestAccBackupRestoreTestingSelection_basic
=== RUN   TestAccBackupRestoreTestingSelection_disappears
=== PAUSE TestAccBackupRestoreTestingSelection_disappears
=== RUN   TestAccBackupRestoreTestingSelection_updates
=== PAUSE TestAccBackupRestoreTestingSelection_updates
=== CONT  TestAccBackupRestoreTestingPlan_basic
=== CONT  TestAccBackupRestoreTestingPlan_additionals
=== CONT  TestAccBackupRestoreTestingPlan_includeVaults
--- PASS: TestAccBackupRestoreTestingPlan_basic (13.85s)
=== CONT  TestAccBackupRestoreTestingPlan_excludeVaults
--- PASS: TestAccBackupRestoreTestingPlan_additionals (13.86s)
=== CONT  TestAccBackupRestoreTestingPlan_tags
--- PASS: TestAccBackupRestoreTestingPlan_includeVaults (20.99s)
=== CONT  TestAccBackupRestoreTestingPlan_disappears
--- PASS: TestAccBackupRestoreTestingPlan_disappears (10.45s)
=== CONT  TestAccBackupRestoreTestingSelection_disappears
--- PASS: TestAccBackupRestoreTestingPlan_excludeVaults (19.68s)
=== CONT  TestAccBackupRestoreTestingSelection_updates
--- PASS: TestAccBackupRestoreTestingPlan_tags (27.97s)
=== CONT  TestAccBackupRestoreTestingPlan_additionalsWithUpdate
--- PASS: TestAccBackupRestoreTestingSelection_disappears (16.80s)
=== CONT  TestAccBackupRestoreTestingSelection_basic
--- PASS: TestAccBackupRestoreTestingSelection_updates (26.94s)
--- PASS: TestAccBackupRestoreTestingPlan_additionalsWithUpdate (20.10s)
--- PASS: TestAccBackupRestoreTestingSelection_basic (18.62s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/backup	72.175s
```

2024-10-04 19:19 UTC, jeroenhabets commented
@ewbankkit as [per your comment](https://github.com/hashicorp/terraform-provider-aws/pull/37039#pullrequestreview-2348865278) this PR seems to be about to get merged, could you please close competing PR https://github.com/hashicorp/terraform-provider-aws/pull/36907? TIA!

2024-10-04 19:38 UTC, merged