Correction to Cerificate typo, missing `t`
hashicorp/terraform-provider-aws pull request #37798
Opened 2024-06-01 16:48 UTC by heldersepu

### Description
Just a small correction to `Cerificate` typo, missing `t` in Certificate

2024-06-04 15:59 UTC, breathingdust requested changes
Thanks for the contribution @heldersepu! Just need to remove the language specific file changes (as these are generated files) and this will be good to go.

2024-06-04 15:59 UTC, breathingdust commented on website/docs/cdktf/python/r/acm_certificate.html.markdown
> +Private certificates are issued by an ACM Private Certificate Authority, which can be created using the resource type [`aws_acmpca_certificate_authority`](acmpca_certificate_authority.html).
The language specific files are generated automatically from the main file in `/website/docs/r` so this change should be removed.

```suggestion
Private certificates are issued by an ACM Private Cerificate Authority, which can be created using the resource type [`aws_acmpca_certificate_authority`](acmpca_certificate_authority.html).
```

2024-06-04 15:59 UTC, breathingdust commented on website/docs/cdktf/typescript/r/acm_certificate.html.markdown
> +Private certificates are issued by an ACM Private Certificate Authority, which can be created using the resource type [`aws_acmpca_certificate_authority`](acmpca_certificate_authority.html).
The language specific files are generated automatically from the main file in /website/docs/r so this change should be removed.

```suggestion
Private certificates are issued by an ACM Private Cerificate Authority, which can be created using the resource type [`aws_acmpca_certificate_authority`](acmpca_certificate_authority.html).
```

2024-06-04 22:13 UTC, heldersepu commented
@breathingdust suggestions applied...

2024-06-04 22:21 UTC, heldersepu commented
@breathingdust suggestions applied...

If you have time can you please also review this othe PR of mine: https://github.com/hashicorp/terraform-provider-aws/pull/37800

2024-06-05 16:49 UTC, breathingdust commented
LGTM 🚀 Thanks for the contribution @heldersepu!

2024-06-05 16:50 UTC, merged