f: add enable_private_gua argument to aws_vpc_ipam resource
hashicorp/terraform-provider-aws pull request #38838
Opened 2024-08-13 02:06 UTC by JulesPatry

### Description
Add tier argument to aws_vpc_ipam resource

### Relations

### References

### Output from Acceptance Testing
```
go test -timeout 100s -run ^TestAccIPAM_enablePrivateGua$ github.com/hashicorp/terraform-provider-aws/internal/service/ec2
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2  44.929s
```

2024-08-13 13:40 UTC, jmpatry commented
@drewmullen, it's been a minute! Do you have a chance to take a look at this pull request?

2024-08-13 23:59 UTC, drewmullen commented on internal/service/ec2/ipam_test.go
> +		region_name = data.aws_region.current.name
Gotta fix the spacing in this test file, CI is going to complain once it runs

2024-08-14 00:00 UTC, drewmullen commented
@JulesPatry long time no see! 1 small request in the test HCL string but otherwise looks good!

2024-08-14 00:01 UTC, drewmullen commented on .changelog/38838.txt
> +```release-note:note
Should be “enhancement” I think instead of note

2024-08-14 00:06 UTC, drewmullen commented on internal/service/ec2/ipam_test.go
> +							Config: testAccIPAMConfig_enablePrivateGua("false"),
Probably need to replace “false” with “acctest.CtFalse”

2024-08-14 00:07 UTC, drewmullen requested changes
Ok. Nice work. Few comments above

please also remove the changes to go.mod/sum - those are bumped by external processes

2024-10-08 21:54 UTC, closed without merging