r/aws_eks_cluster: Add support for EKS Auto Mode
hashicorp/terraform-provider-aws pull request #40370
Opened 2024-12-01 21:05 UTC by bryantbiggs

### Description
- Add support for EKS Auto Mode

:warning: Requires AWS SDK Go v2 changes which are still pending release

### Relations
- N/A

### References

- https://aws.amazon.com/blogs/aws/streamline-kubernetes-cluster-management-with-new-amazon-eks-auto-mode/
- https://aws.amazon.com/eks/auto-mode/?trk=ea66575f-9c47-4d58-9bbe-a262d8aa74fd&sc_channel=el

### Output from Acceptance Testing

```console
make testacc PKG=eks TESTS=TestAccEKSCluster_ComputeConfig
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/eks/... -v -count 1 -parallel 20 -run='TestAccEKSCluster_ComputeConfig'  -timeout 360m
2024/12/01 09:32:13 Initializing Terraform AWS Provider...
=== RUN   TestAccEKSCluster_ComputeConfig
=== PAUSE TestAccEKSCluster_ComputeConfig
=== CONT  TestAccEKSCluster_ComputeConfig
--- PASS: TestAccEKSCluster_ComputeConfig (929.76s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/eks	936.338s
```

2024-12-02 18:22 UTC, gdavison requested changes
I missed a comment when reviewing

2024-12-02 18:22 UTC, gdavison commented on website/docs/r/eks_cluster.html.markdown
> +-> For an example of `aws_eks_cluster` in use, follow the [Provision an EKS Cluster](https://learn.hashicorp.com/tutorials/terraform/eks) tutorial on HashiCorp Learn.
This should stay as `> **Hands-on:**`

```suggestion
> **Hands-on:** For an example of `aws_eks_cluster` in use, follow the [Provision an EKS Cluster](https://learn.hashicorp.com/tutorials/terraform/eks) tutorial on HashiCorp Learn.
```

2024-12-02 23:10 UTC, johnsonaj approved these changes

2024-12-03 00:22 UTC, gdavison approved these changes

2024-12-03 00:24 UTC, merged